import type { Metadata } from "next";
import { CANONICAL_LOGO_PATH } from "../../lib/brand";

export const siteUrl = "https://shadowscore.io";
export type MarketingPage = {
  slug: string; title: string; description: string; h1: string; eyebrow: string; intro: string;
  sections: { title: string; body: string }[]; faqs?: { question: string; answer: string }[];
};

const sharedFaqs = [
  { question: "What is business due diligence?", answer: "Business due diligence is a structured review of identity, source records, relationships, inconsistencies, and evidence gaps before a business decision." },
  { question: "Does ShadowScore guarantee that a business is safe?", answer: "No. ShadowScore presents source-backed findings and limitations. It does not guarantee payment recovery, legal outcomes, investment performance, or third-party decisions." },
  { question: "What happens when evidence is unavailable?", answer: "The review records the missing evidence. Missing evidence is not treated as confirmed misconduct." },
];

export const englishPages: Record<string, MarketingPage> = {
  "business-due-diligence": { slug: "business-due-diligence", title: "Business Due Diligence | ShadowScore", description: "Make better-informed business decisions with source-backed business due diligence, identity verification, risk findings, and evidence coverage.", h1: "Business Due Diligence for Better Business Decisions", eyebrow: "Business decision intelligence", intro: "Review a company, supplier, partner, seller, website, or investment opportunity before you trust, pay, partner, or invest.", sections: [{ title: "A decision record, not just a document", body: "ShadowScore compares available identity, registry, domain, and business-information sources. It records supporting evidence, unresolved questions, risk findings, confidence, and recommended next actions." }, { title: "Built for commercial decisions", body: "Use business due diligence before supplier payment, partner onboarding, marketplace purchases, procurement decisions, and investment reviews." }], faqs: sharedFaqs },
  "company-check": { slug: "company-check", title: "Company Check and Company Verification | ShadowScore", description: "Check and verify a company with source-backed business identity, registry, domain, relationship, and risk information.", h1: "Company Check and Business Verification", eyebrow: "Verify a company", intro: "Compare a company’s claims with available registry and business-information sources before you enter an agreement or make a payment.", sections: [{ title: "What a company check reviews", body: "A company check can review legal identity, registration status, directors or ownership signals where available, contact consistency, domains, and related entities." }, { title: "Go beyond a single record", body: "Connect a company registry search to a broader business due diligence review when the decision depends on identity, relationships, contradictions, or unresolved risks." }], faqs: sharedFaqs },
  "company-registry-search": { slug: "company-registry-search", title: "Company Registry Search and Business Verification | ShadowScore", description: "Search company registry information, registration status, and company details, then extend the review with business verification.", h1: "Company Registry Search and Business Verification", eyebrow: "Company registry information", intro: "Use a company registry search to find available registration information, then assess what the record can and cannot establish for your decision.", sections: [{ title: "What a company registry search provides", body: "Registry information may include official company details, registration status, and directors or officers. Available fields differ by source and jurisdiction." }, { title: "What a registry record may not reveal", body: "A registry record alone may not resolve digital identity, website consistency, connected entities, conflicting claims, or payment-related questions. ShadowScore adds a multi-source business verification layer." }], faqs: sharedFaqs },
  "company-extract": { slug: "company-extract", title: "Company Extract and Company Due Diligence | ShadowScore", description: "Understand what a company extract can provide and when broader company due diligence is needed before a business decision.", h1: "Company Extract and Company Due Diligence", eyebrow: "Company extract", intro: "A company extract is useful for retrieving available official registration information. It is not the same as a full business due diligence review.", sections: [{ title: "When a company extract may be sufficient", body: "A registry extract can suit a narrow request for official company details or registration status." }, { title: "When to extend the review", body: "Use business due diligence when you need to compare claims, digital identity, relationships, source records, and unresolved risks before paying or partnering." }], faqs: sharedFaqs },
  "supplier-verification": { slug: "supplier-verification", title: "Verify a Supplier Before You Pay | ShadowScore", description: "Verify a supplier before payment with company status, identity, domain consistency, ownership signals, evidence gaps, and recommended controls.", h1: "Verify a Supplier Before You Pay", eyebrow: "Supplier verification", intro: "Create a source-backed record before onboarding a supplier, changing payment instructions, or transferring funds.", sections: [{ title: "Review the supplier behind the invoice", body: "Check legal identity, company status, domain and email consistency, ownership signals where available, connected entities, and missing evidence." }, { title: "Use proportionate payment controls", body: "When payment-account ownership remains unresolved, record that gap and verify the beneficiary account before transferring funds." }], faqs: sharedFaqs },
  "business-background-check": { slug: "business-background-check", title: "Business Background Check | ShadowScore", description: "Run a source-backed business background check for identity, relationships, inconsistencies, evidence gaps, and decision risks.", h1: "Business Background Check for Commercial Decisions", eyebrow: "Business background check", intro: "Assess the identity and decision risks around a business, not only a single company record.", sections: [{ title: "Investigate the business context", body: "Review business identity, online presence, connected entities, contact details, contradictions, and source references." }, { title: "Keep uncertainty visible", body: "Risk and confidence are independent. A review can identify risks while still showing where source coverage is incomplete." }], faqs: sharedFaqs },
  "marketplace-seller-verification": { slug: "marketplace-seller-verification", title: "Marketplace Seller Verification | ShadowScore", description: "Verify a marketplace seller with business identity, domain, contact, reputation, related-account, and evidence analysis.", h1: "Marketplace Seller Verification", eyebrow: "Online business verification", intro: "Review a marketplace seller or online business before payment or onboarding.", sections: [{ title: "Connect the seller signals", body: "Compare marketplace presence, identity reuse, contact details, domain signals, reputation signals, and related accounts." }, { title: "Document the next action", body: "Use the evidence record to request missing documentation or apply a payment control before proceeding." }], faqs: sharedFaqs },
};

export const hebrewPages: Record<string, MarketingPage> = {
  "business-due-diligence": { slug: "business-due-diligence", title: "ShadowScore | בדיקת נאותות עסקית", description: "בדיקת נאותות עסקית מבוססת מקורות לבדיקת חברות, ספקים, שותפים ומוכרים לפני תשלום או התקשרות.", h1: "בדיקת נאותות עסקית לפני החלטה", eyebrow: "מודיעין להחלטה עסקית", intro: "בדקו חברה, ספק, שותף, מוכר, אתר או הזדמנות השקעה לפני תשלום או התקשרות.", sections: [{ title: "ראיות והמלצה", body: "ShadowScore מצליבה מידע על זהות, רישום, דומיין וקשרים עסקיים, ומציגה ראיות, פערים, סיכונים ופעולות מומלצות." }], faqs: [{ question: "מהי בדיקת נאותות עסקית?", answer: "זוהי בדיקה מובנית של זהות, מקורות, קשרים, סתירות ופערי ראיות לפני החלטה עסקית." }, { question: "מה קורה כאשר אין מספיק מידע?", answer: "המערכת מציגה את פער הראיות. מידע חסר אינו הוכחה להתנהלות פסולה." }] },
  "company-check": { slug: "company-check", title: "ShadowScore | בדיקת חברה ומידע עסקי", description: "בדיקת חברה ומידע עסקי מבוססי מקורות לפני תשלום, התקשרות או שותפות עסקית.", h1: "בדיקת חברה ומידע עסקי", eyebrow: "אימות חברה", intro: "השוו את טענות החברה מול מידע עסקי, רישום חברה ומקורות זמינים.", sections: [{ title: "מה כוללת בדיקת חברה", body: "בדיקת חברה יכולה לכלול זהות משפטית, מצב רישום, בעלי תפקידים או בעלות כאשר המידע זמין, דומיין, פרטי קשר וקשרים עסקיים." }], faqs: [{ question: "האם אפשר לבדוק חברה לפני תשלום?", answer: "כן. הבדיקה מתעדת זהות, מקורות ופערי ראיות לפני העברת כספים או התקשרות." }] },
  "company-registry": { slug: "company-registry", title: "ShadowScore | בדיקת חברה, רשם חברות ונסח חברה", description: "בדיקת חברה ברשם החברות, מידע על חברה ונסח חברה, לצד בדיקת נאותות עסקית מבוססת מקורות.", h1: "בדיקת חברה, רשם חברות ונסח חברה", eyebrow: "מידע על חברה", intro: "ניתן לאתר פרטי רישום בסיסיים של חברה באמצעות רשם החברות או נסח חברה. ShadowScore מוסיפה שכבת בדיקת נאותות עסקית לפני תשלום או התקשרות.", sections: [{ title: "מה ניתן לקבל מרשם החברות", body: "רשם חברות ונסח חברה עשויים לכלול פרטי רישום ומצב חברה. היקף המידע משתנה לפי מקור ותחום שיפוט." }, { title: "מה מוסיפה בדיקת נאותות", body: "אימות זהות, הצלבת מקורות, בדיקת אתר ודומיין, קשרים עסקיים, סתירות, ראיות חסרות והמלצה להמשך פעולה." }], faqs: [{ question: "מה ההבדל בין נסח חברה לבין בדיקת נאותות?", answer: "נסח חברה מספק מידע רישומי זמין. בדיקת נאותות בוחנת גם זהות, קשרים, סתירות ופערי ראיות." }] },
  "company-extract": { slug: "company-extract", title: "ShadowScore | נסח חברה ובדיקת נאותות עסקית", description: "נסח חברה ובדיקת נאותות עסקית: הבינו מה כולל מידע רישומי ומתי נדרשת בדיקה רחבה יותר.", h1: "נסח חברה ובדיקת נאותות עסקית", eyebrow: "נסח חברה", intro: "נסח חברה שימושי לאיסוף מידע רישומי זמין. בדיקת נאותות עסקית בוחנת הקשר רחב יותר לפני החלטה.", sections: [{ title: "מתי נסח חברה מספיק", body: "נסח חברה עשוי להתאים כאשר נדרש מידע רישומי רשמי בלבד." }, { title: "מתי להרחיב את הבדיקה", body: "לפני תשלום או התקשרות, ניתן לבדוק גם זהות, דומיין, קשרים, סתירות וראיות חסרות." }] },
  "supplier-check": { slug: "supplier-check", title: "ShadowScore | בדיקת ספק לפני תשלום", description: "בדיקת ספק לפני תשלום עם אימות זהות, מצב חברה, דומיין, בעלות, קשרים עסקיים ופערי ראיות.", h1: "בדיקת ספק לפני תשלום", eyebrow: "אימות ספק", intro: "בדקו ספק לפני העברת כספים, קליטה לרכש או שינוי הוראות תשלום.", sections: [{ title: "מה בודקים", body: "זהות משפטית, מצב חברה, התאמת דומיין ודוא״ל, בעלות כאשר היא זמינה, קשרים עסקיים, ראיות חסרות ובקרות מומלצות." }, { title: "אימות חשבון מוטב", body: "כאשר בעלות על חשבון מוטב אינה פתורה, יש לתעד את הפער ולאמת את החשבון לפני העברה." }] },
  "business-information": { slug: "business-information", title: "ShadowScore | דוח מידע עסקי ובדיקת חברה לפני התקשרות", description: "דוח מידע עסקי ובדיקת חברה לפני התקשרות, עם הצלבת מקורות, סיכונים, פערי ראיות והמלצות.", h1: "דוח מידע עסקי ובדיקת חברה לפני התקשרות", eyebrow: "מידע עסקי", intro: "הבינו את ההבדל בין מידע עסקי בסיסי, נסח חברה, דוח מידע עסקי, בדיקת נאותות עסקית וניטור מתמשך.", sections: [{ title: "מידע עסקי לעומת בדיקת נאותות", body: "מידע עסקי בסיסי ונסח חברה מתמקדים בפרטי רישום זמינים. בדיקת נאותות עסקית מחברת בין מקורות, זהות, קשרים, סתירות ופערים." }] },
};

export function marketingMetadata(page: MarketingPage, locale: "en" | "he" = "en"): Metadata {
  const path = locale === "he" ? `/he/${page.slug}` : `/${page.slug}`;
  const alternate = locale === "he" ? `/${page.slug}` : `/he/${page.slug}`;
  return { title: page.title, description: page.description, alternates: { canonical: path, languages: { en: locale === "en" ? path : alternate, he: locale === "he" ? path : alternate, "x-default": locale === "en" ? path : alternate } }, openGraph: { title: page.title, description: page.description, url: `${siteUrl}${path}`, locale: locale === "he" ? "he_IL" : "en_US", type: "website", images: [CANONICAL_LOGO_PATH] }, twitter: { card: "summary_large_image", title: page.title, description: page.description, images: [CANONICAL_LOGO_PATH] } };
}
