export type PublicPage = {
  path: string;
  title: string;
  description: string;
  eyebrow: string;
  heading: string;
  intro: string;
  capabilities: { title: string; body: string }[];
  related: { href: string; label: string; description: string }[];
  faq?: { question: string; answer: string }[];
};

const related = {
  platform: { href: "/platform", label: "Explore the intelligence platform", description: "See how investigations, evidence, reports, and monitoring work together." },
  graph: { href: "/data/entity-graph", label: "Understand the Entity Graph", description: "See how identifiers, entities, evidence, and relationships connect." },
  investigate: { href: "/product/investigations", label: "Review the investigation workflow", description: "Move from an initial identifier to a documented decision." },
  reports: { href: "/product/executive-reports", label: "Explore Executive Reports", description: "Turn findings and provenance into a clear decision record." },
  security: { href: "/security", label: "Review security practices", description: "Learn how ShadowScore approaches access and investigation data." },
};

const pageEntries = [
  ["/platform", "Entity Intelligence Platform | ShadowScore", "Investigate people, companies, domains, emails, sellers, and related entities with connected public evidence and clear provenance.", "Platform", "Understand who or what you are dealing with", "ShadowScore connects fragmented public signals into an Entity Graph. Investigators can follow relationships, assess evidence quality, produce an Executive Report, and monitor material changes.", [["Start with an entity", "Open an Investigation from a company, person, email, domain, seller account, or another known identifier."], ["Connect the evidence", "Bring public records and open-web signals into one view while retaining the source and collection context."], ["Reach a documented decision", "Separate Discovery Candidates from Corroborated Evidence and Verified Facts, then share the reasoning in an Executive Report."]], [related.investigate, related.graph, related.reports]],
  ["/solutions", "Entity Intelligence Solutions | ShadowScore", "Apply source-backed entity intelligence to due diligence, vendor risk, seller verification, fraud investigation, and digital identity research.", "Solutions", "Intelligence for decisions about people and organizations", "Use a consistent investigation method across onboarding, procurement, marketplace, fraud, and counterparty reviews. Each solution keeps evidence, uncertainty, and provenance visible.", [["Business decisions", "Investigate counterparties before an agreement, payment, or other consequential decision."], ["Operational reviews", "Give risk and operations teams a shared record of findings, gaps, and follow-up actions."], ["Ongoing awareness", "Monitor investigated entities and route material changes into Alerts for review."]], [related.platform, related.investigate, related.security]],
  ["/solutions/business-due-diligence", "Business Due Diligence Platform | ShadowScore", "Investigate a company or counterparty with source-backed identity, relationship, risk, and provenance intelligence.", "Business due diligence", "Build a source-backed view before a business decision", "Investigate the organization, people, domains, and other identifiers behind a commercial relationship. Record what is known, what is only a lead, and what still requires verification.", [["Confirm the subject", "Resolve the legal and digital identity of the business under review."], ["Review relationships", "Explore connected people, companies, domains, and accounts that may affect the decision."], ["Document the outcome", "Create an Executive Report with material findings, evidence gaps, provenance, and next actions."]], [related.graph, related.reports, related.security]],
  ["/solutions/vendor-risk", "Vendor Risk Intelligence | ShadowScore", "Investigate vendor identity, relationships, digital signals, and evidence gaps before onboarding and throughout the relationship.", "Vendor risk", "Know the vendor behind the proposal or invoice", "Create an evidence record for supplier selection, onboarding, renewal, and payment reviews. Monitoring helps teams revisit the decision when relevant public signals change.", [["Vendor identity", "Compare submitted details with available business, registry, domain, and open-web evidence."], ["Risk context", "Review relationships and inconsistencies without treating a missing record as proof of wrongdoing."], ["Review over time", "Monitor approved vendors and assess new Alerts against the original investigation."]], [related.investigate, { href: "/product/monitoring", label: "Explore continuous monitoring", description: "Keep reviewed vendors connected to their evidence history." }, related.reports]],
  ["/solutions/marketplace-seller-risk", "Marketplace Seller Risk and Verification | ShadowScore", "Investigate seller accounts, businesses, domains, emails, and related identities with traceable public evidence.", "Marketplace seller risk", "Connect a seller account to the entities behind it", "Start with a seller name, account, email, domain, or company. Follow public relationships and preserve the basis for each identity match or risk finding.", [["Resolve the seller", "Compare account details with business and digital identity signals."], ["Find related entities", "Explore reused identifiers and relevant relationships without assuming that similarity proves common control."], ["Support a review", "Give marketplace teams a clear record for verification, escalation, or continued monitoring."]], [related.graph, { href: "/data/digital-identity-signals", label: "Review digital identity signals", description: "Understand how emails, domains, and accounts contribute context." }, related.reports]],
  ["/solutions/fraud-investigation", "Fraud Investigation and Entity Intelligence | ShadowScore", "Connect public identity and relationship signals for fraud investigations while preserving evidence status and provenance.", "Fraud investigation", "Follow leads without confusing them with facts", "Move from an initial person, company, email, domain, seller, or account to related public signals. ShadowScore makes the status and source of each finding explicit.", [["Develop leads", "Use Discovery Candidates to identify useful paths for further investigation."], ["Corroborate carefully", "Compare independent sources before elevating an observation to Corroborated Evidence or a Verified Fact."], ["Preserve reasoning", "Keep source references, timestamps, relationships, and limitations with the investigation record."]], [related.investigate, related.graph, related.reports]],
  ["/solutions/entity-intelligence", "Entity Intelligence for Business | ShadowScore", "Resolve entities and relationships across public business, registry, open-web, and digital identity signals.", "Entity intelligence", "See the entities and relationships behind a decision", "Organize scattered signals around people, companies, domains, emails, sellers, and other identifiers. Use provenance and evidence status to understand why a connection appears.", [["Entity resolution", "Bring identifiers and observations together around the subject being investigated."], ["Relationship intelligence", "Explore relevant connections while keeping inferred and verified relationships distinct."], ["Decision context", "Translate the graph into findings that a business stakeholder can understand and review."]], [related.graph, { href: "/data/open-web-intelligence", label: "Explore open-web intelligence", description: "See how public web signals enter an investigation." }, related.reports]],
  ["/solutions/digital-identity", "Digital Identity Investigation | ShadowScore", "Investigate emails, domains, accounts, people, and companies through connected, source-backed public signals.", "Digital identity", "Understand the identity behind an email, domain, or account", "Start with a digital identifier and examine relevant public connections. Candidate matches remain leads until evidence supports stronger attribution.", [["Start from a signal", "Investigate an email, domain, username, seller account, or related identifier."], ["Connect identity context", "Link relevant people, companies, infrastructure, and public profiles through visible relationships."], ["Control attribution", "Keep discovery scores separate from evidence status and record the source for every claim."]], [{ href: "/data/digital-identity-signals", label: "How digital signals work", description: "Review the role and limits of digital identity evidence." }, related.graph, related.investigate]],
  ["/data", "Public Data and Entity Intelligence | ShadowScore", "Connect open-web, business, registry, and digital identity signals in a provenance-aware Entity Graph.", "Data", "Turn fragmented public signals into usable evidence", "ShadowScore organizes public information around entities and relationships. Every useful signal retains its provenance, evidence status, and investigation context.", [["Open-web intelligence", "Discover relevant public pages and records while preserving the path that led to them."], ["Business and registry data", "Compare available legal and commercial identity information across source families."], ["Digital identity signals", "Use domains, emails, accounts, and related identifiers to develop and test identity leads."]], [related.graph, related.investigate, related.security]],
  ["/data/entity-graph", "Entity Graph and Relationship Intelligence | ShadowScore", "Explore people, companies, domains, emails, sellers, evidence, and relationships in a provenance-aware Entity Graph.", "Entity Graph", "See how entities, evidence, and relationships connect", "The Entity Graph gives each public signal a place in the investigation. It shows what connects two entities, where the information came from, and how strongly the evidence supports the relationship.", [["Entities and identifiers", "Represent people, companies, domains, emails, accounts, and other identifiers without collapsing uncertain matches."], ["Evidence-aware relationships", "Distinguish observed, inferred, corroborated, and verified connections."], ["Traceable exploration", "Follow a relationship back to its source, collection time, and investigation path."]], [related.investigate, { href: "/data/open-web-intelligence", label: "Open-web intelligence", description: "See how public discoveries become graph context." }, related.reports]],
  ["/data/open-web-intelligence", "Open-Source Intelligence for Business | ShadowScore", "Use relevant open-web intelligence in business investigations with visible provenance, limitations, and evidence status.", "Open-web intelligence", "Collect public web signals with their context intact", "Open-web intelligence can reveal useful identity and relationship leads. ShadowScore records the query path, source, timing, and evidence status so that discovery remains reviewable.", [["Targeted discovery", "Search from the submitted entity and bounded, relevant identity clues."], ["Source context", "Retain the public source and the reason a result was considered relevant."], ["Evidence discipline", "Treat search results as candidates until independent support justifies a stronger status."]], [related.graph, related.investigate, related.reports]],
  ["/data/business-and-registry-data", "Business and Registry Data Intelligence | ShadowScore", "Compare available company, registry, business identity, and relationship data within a source-backed investigation.", "Business and registry data", "Put company records in the context of the whole entity", "A registry record can establish useful facts, but a decision may also depend on digital identity, relationships, contradictions, and evidence gaps. ShadowScore keeps these source families connected and distinct.", [["Business identity", "Compare names, registration details, status, addresses, and other available attributes."], ["Cross-source review", "Identify alignment or contradictions across registry, business, domain, and open-web sources."], ["Coverage limits", "Show unavailable fields and source limitations rather than filling gaps with assumptions."]], [{ href: "/solutions/business-due-diligence", label: "Business due diligence", description: "Apply company data to a complete commercial review." }, related.graph, related.reports]],
  ["/data/digital-identity-signals", "Digital Identity Signals | ShadowScore", "Connect domains, emails, accounts, and public identity signals while keeping candidate matches and verified facts distinct.", "Digital identity signals", "Use digital identifiers as evidence, not shortcuts", "Emails, domains, usernames, seller accounts, and public profiles can connect an investigation. ShadowScore preserves match reasons and avoids presenting similarity alone as verified identity.", [["Identifier context", "Understand where an identifier appeared and how it relates to the submitted subject."], ["Candidate matching", "Rank potentially relevant discoveries while keeping them clearly labeled as candidates."], ["Independent support", "Elevate identity claims only when the available evidence meets the required standard."]], [{ href: "/solutions/digital-identity", label: "Digital identity investigations", description: "See the complete workflow for investigating an online identifier." }, related.graph, related.investigate]],
  ["/product/investigations", "Entity Investigations | ShadowScore", "Investigate companies, people, domains, emails, sellers, counterparties, and related entities in one evidence-aware workflow.", "Investigations", "Move from an identifier to a reviewable decision", "An Investigation keeps the subject, discoveries, evidence, relationships, findings, and decision together. It supports research without hiding uncertainty from the reviewer.", [["Define the subject", "Start with the identifier you know and retain it as the investigation anchor."], ["Review and verify", "Assess Discovery Candidates, Corroborated Evidence, Verified Facts, provenance, and remaining gaps."], ["Complete the record", "Document findings and prepare an Executive Report for the decision owner."]], [related.graph, related.reports, { href: "/product/monitoring", label: "Continue with monitoring", description: "Keep watching investigated entities after the initial decision." }]],
  ["/product/executive-reports", "Executive Investigation Reports | ShadowScore", "Share entity findings, evidence, relationships, provenance, limitations, and next actions in a clear Executive Report.", "Executive Reports", "Give decision owners the evidence and the conclusion", "Executive Reports turn investigation work into a structured business record. Readers can understand the subject, material findings, supporting evidence, unresolved gaps, and recommended controls.", [["Decision first", "Lead with the outcome, material findings, and actions that matter to the reviewer."], ["Evidence behind the finding", "Connect conclusions to sources, confidence, evidence status, and provenance."], ["Visible limitations", "Keep missing coverage and unresolved questions in the report so they can inform the decision."]], [related.investigate, related.graph, { href: "/sample-report", label: "View an illustrative report", description: "Review the structure using clearly labeled sample data." }]],
  ["/product/monitoring", "Entity Monitoring | ShadowScore", "Monitor investigated companies, people, domains, sellers, and related entities for relevant public signal changes.", "Monitoring", "Continue the review after the first decision", "Monitoring keeps an investigated entity connected to its evidence history. New public signals can be assessed in context instead of starting each review from the beginning.", [["Watch the entity", "Select investigated subjects and relationships that warrant continued attention."], ["Compare change", "Assess new signals against the evidence and conclusions already in the investigation."], ["Trigger review", "Route relevant changes into Alerts so a person can decide whether action is required."]], [{ href: "/product/alerts", label: "Explore Alerts", description: "See how monitoring changes become review tasks." }, related.investigate, related.reports]],
  ["/product/alerts", "Entity Intelligence Alerts | ShadowScore", "Review relevant monitoring changes with entity context, evidence provenance, and a clear path back to the Investigation.", "Alerts", "Focus attention on changes that need review", "Alerts connect a new signal to the monitored entity and its investigation history. Reviewers can examine the evidence before changing a decision or taking action.", [["Relevant context", "See which monitored entity and prior evidence relate to the new signal."], ["Human review", "Evaluate the source and materiality before treating an alert as a confirmed change."], ["Connected action", "Return to the Investigation to update findings, controls, or the Executive Report."]], [{ href: "/product/monitoring", label: "Entity monitoring", description: "Understand the monitoring workflow behind Alerts." }, related.investigate, related.reports]],
  ["/resources", "Entity Intelligence Resources | ShadowScore", "Read practical guides and research about business due diligence, entity intelligence, evidence, provenance, and risk decisions.", "Resources", "Use entity intelligence with greater clarity", "Explore plain-language material about investigations, public evidence, identity resolution, and business risk decisions.", [["Practical guides", "Learn how to structure a review and interpret evidence status, provenance, and gaps."], ["Research", "Read analysis of public intelligence methods and decision-quality questions."], ["Product methodology", "Understand how ShadowScore separates discovery, evidence, and verification."]], [{ href: "/resources/guides", label: "Browse practical guides", description: "Start with investigation and evidence fundamentals." }, { href: "/resources/research", label: "Browse research", description: "Explore methods and questions in entity intelligence." }, { href: "/methodology", label: "Read the methodology", description: "Review how ShadowScore evaluates information." }]],
  ["/resources/guides", "Entity Intelligence and Due Diligence Guides | ShadowScore", "Practical guides to entity investigations, business due diligence, evidence review, provenance, and monitoring.", "Guides", "Build a clearer investigation process", "These guides introduce the questions behind a reliable entity review. Start with the subject, assess each source, record uncertainty, and connect the evidence to a decision.", [["Plan the investigation", "Define the subject, decision, identifiers, and evidence needed before collecting information."], ["Assess evidence", "Distinguish a Discovery Candidate from Corroborated Evidence and a Verified Fact."], ["Communicate the result", "Present findings, provenance, limitations, and next actions in language the decision owner can use."]], [related.investigate, related.reports, { href: "/methodology", label: "ShadowScore methodology", description: "Read the product's evidence and decision approach." }]],
  ["/resources/research", "Entity Intelligence Research | ShadowScore", "Research and analysis on public entity data, relationship intelligence, provenance, and evidence-led business decisions.", "Research", "Examine how public intelligence supports business decisions", "Research notes explore entity resolution, relationship analysis, evidence quality, and the limits of public information. Content focuses on methods and decision questions rather than unsupported coverage claims.", [["Entity resolution", "Consider when two identifiers support one identity and when uncertainty should remain."], ["Relationship analysis", "Examine how source quality and context affect the meaning of a connection."], ["Decision integrity", "Study how provenance and explicit evidence gaps improve reviewability."]], [related.graph, { href: "/data/open-web-intelligence", label: "Open-web intelligence", description: "Review the product approach to public web signals." }, { href: "/resources/guides", label: "Practical guides", description: "Apply the research concepts to an investigation workflow." }]],
  ["/company", "Company | ShadowScore", "Learn about ShadowScore and its approach to accessible, source-backed entity intelligence for business decisions.", "Company", "Entity intelligence that more teams can understand", "ShadowScore helps people investigate the entities behind business decisions. The platform connects public signals, preserves provenance, separates discovery from verification, and communicates findings in plain language.", [["Our focus", "Build a reliable path from fragmented public information to a reviewable business decision."], ["Our standard", "Keep sources, uncertainty, evidence status, and limitations visible throughout the investigation."], ["Our product", "Support investigations, Entity Graph analysis, Executive Reports, Monitoring, and Alerts in one platform."]], [related.platform, related.security, { href: "/contact", label: "Contact ShadowScore", description: "Discuss your investigation or evaluation needs." }]],
] satisfies [string, string, string, string, string, string, [string, string][], PublicPage["related"]][];

export const publicPages: Record<string, PublicPage> = Object.fromEntries(pageEntries.map(([path, title, description, eyebrow, heading, intro, items, links]) => [path, { path, title, description, eyebrow, heading, intro, capabilities: items.map(([itemTitle, body]) => ({ title: itemTitle, body })), related: links }]));

export const publicPaths = Object.keys(publicPages);
