import { createHash } from "node:crypto";
import type { Assertion } from "@/lib/evidenceV2/types";
import type { AssertionReader, ConflictRepository, FactLedgerRepository, IdentityCandidateRepository, KnowledgeEventRepository, KnowledgeProjectionRepository, RelationshipLedgerRepository, ResolutionPolicyRepository, ResolutionScope, ResolvedFact, KnowledgeConflict } from "./types";
const stable=(v:unknown):string=>JSON.stringify(v&&typeof v==="object"&&!Array.isArray(v)?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,JSON.parse(stable(x))])):v);
const id=(...parts:unknown[])=>createHash("sha256").update(stable(parts)).digest("hex");
type Repositories={assertions:AssertionReader;facts:FactLedgerRepository;relationships:RelationshipLedgerRepository;candidates:IdentityCandidateRepository;conflicts:ConflictRepository;projections:KnowledgeProjectionRepository;policies:ResolutionPolicyRepository;events:KnowledgeEventRepository};
export class KnowledgeResolutionPipeline {
 private r:Repositories; private now:()=>string;
 constructor(r:Repositories,now=()=>new Date().toISOString()){this.r=r;this.now=now;}
 async rebuild(scope:ResolutionScope,subjectType="*"){
  const assertions=await this.r.assertions.current(scope);const subjects=[...new Set(assertions.map(a=>a.subjectId))].sort();const output=[];
  for(const subjectId of subjects){const own=assertions.filter(a=>a.subjectId===subjectId);const taxonomies=[...new Set(own.map(a=>a.taxonomy))].sort();const facts:ResolvedFact[]=[];const conflicts:KnowledgeConflict[]=[];const versions=new Set<string>();
   for(const taxonomy of taxonomies){const policy=(await this.r.policies.applicable(taxonomy,subjectType))[0];if(!policy)continue;versions.add(`${policy.policyKey}@${policy.version}`);const group=own.filter(a=>a.taxonomy===taxonomy).sort((a,b)=>a.assertionId.localeCompare(b.assertionId));const byValue=new Map<string,Assertion[]>();for(const a of group){const h=id(a.value);byValue.set(h,[...(byValue.get(h)??[]),a]);}const ranked=[...byValue].sort((a,b)=>b[1].length-a[1].length||a[0].localeCompare(b[0]));const winner=ranked[0];if(!winner)continue;const disputed=ranked.length>1;const confidence=winner[1].reduce((n,a)=>n+a.confidence.overall,0)/group.length;const factId=id(scope.workspaceId,subjectId,taxonomy,winner[0],policy.policyKey,policy.version);const provenance=group.map(a=>({assertionId:a.assertionId,contributionType:(winner[1].includes(a)?"supports":"contradicts") as "supports"|"contradicts",contributionWeight:a.confidence.overall}));const fact:ResolvedFact={factId,workspaceId:scope.workspaceId,subjectId,taxonomyKey:taxonomy,canonicalValue:winner[1][0].value,canonicalValueHash:winner[0],confidence,resolutionStatus:disputed?(policy.conflictBehavior==="dispute"?"disputed":"unresolved"):"current",policyKey:policy.policyKey,policyVersion:policy.version,validFrom:winner[1].map(a=>a.validFrom).sort()[0],validTo:null,createdAt:this.now(),supersededByFactId:null,provenance};await this.r.facts.appendFact(fact);facts.push(fact);
    if(disputed){const conflict={conflictId:id(factId,"conflict"),workspaceId:scope.workspaceId,subjectId,taxonomyKey:taxonomy,severity:Math.min(1,(ranked.length-1)/ranked.length+0.25),status:"open" as const,policyKey:policy.policyKey,policyVersion:policy.version,assertionIds:group.map(a=>a.assertionId),explanation:`${ranked.length} canonical values remain for ${taxonomy}.`,createdAt:this.now()};await this.r.conflicts.appendConflict(conflict);conflicts.push(conflict);}
   }
   const projection={subjectId,facts,relationships:[],conflicts,identityCandidates:[],confidenceSummary:{minimum:facts.length?Math.min(...facts.map(f=>f.confidence)):0,average:facts.length?facts.reduce((n,f)=>n+f.confidence,0)/facts.length:0},projectedAt:this.now()};await this.r.projections.replace({...scope,subjectId},projection);await this.r.events.appendEvent({eventId:id(scope.workspaceId,subjectId,[...versions]),workspaceId:scope.workspaceId,type:"knowledge.projection.rebuilt",aggregateId:subjectId,policyVersions:[...versions].sort(),occurredAt:this.now()});output.push(projection);
  }return output;
 }
}
