import type { CollectorRegistry } from "./registry";
import { RetryManager, TimeoutManager } from "./services";
import type { CollectorExecution, CollectorOutput, ExecutionContext, ExecutionRepository, ExecutionStatus } from "./types";
type RuntimeServices={repository:ExecutionRepository;timeoutManager?:TimeoutManager;retryManager?:RetryManager;now?:()=>string;sleep?:(ms:number)=>Promise<void>};
export class CollectorRuntime {private readonly registry:CollectorRegistry;private readonly services:RuntimeServices;private readonly timeout:TimeoutManager;private readonly retry:RetryManager;private readonly now:()=>string;private readonly sleep:(ms:number)=>Promise<void>;constructor(registry:CollectorRegistry,services:RuntimeServices){this.registry=registry;this.services=services;this.timeout=services.timeoutManager??new TimeoutManager();this.retry=services.retryManager??new RetryManager();this.now=services.now??(()=>new Date().toISOString());this.sleep=services.sleep??(ms=>new Promise(r=>setTimeout(r,ms)));}
 async execute(input:{collectorKey:string;version?:string;idempotencyKey:string;leaseOwner:string;leaseMs:number;context:Omit<ExecutionContext,"execution">}):Promise<{execution:CollectorExecution;output:CollectorOutput|null;created:boolean}>{const collector=this.registry.get(input.collectorKey,input.version);if(!collector)throw new Error(`Collector ${input.collectorKey} is not registered.`);const createdAt=this.now();let execution:CollectorExecution={executionId:crypto.randomUUID(),investigationId:input.context.investigation.investigationId,collectorKey:collector.definition.collectorKey,collectorVersion:collector.definition.version,idempotencyKey:input.idempotencyKey,status:"pending",attemptCount:0,leaseOwner:null,leaseExpiresAt:null,createdAt,completedAt:null};const result=await this.services.repository.create(execution);if(!result.created)return {execution:result.execution,output:null,created:false};execution=result.execution;await this.transition(execution,"queued");execution.leaseOwner=input.leaseOwner;execution.leaseExpiresAt=new Date(Date.parse(this.now())+input.leaseMs).toISOString();let last:unknown;
  for(let attempt=1;attempt<=collector.definition.retryPolicy.maxAttempts;attempt++){execution.attemptCount=attempt;await this.transition(execution,"running");const context=Object.freeze({...input.context,execution:Object.freeze({executionId:execution.executionId,attempt})});try{context.cancellationToken.throwIfCancelled();await collector.validate(context);const output=await this.timeout.run(()=>collector.collect(context),collector.definition.timeoutMs);await this.transition(execution,"succeeded");execution.leaseOwner=null;execution.leaseExpiresAt=null;execution.completedAt=this.now();await this.transition(execution,"completed");return {execution,output,created:true};}catch(error){last=error;await this.transition(execution,"failed",{message:error instanceof Error?error.message:"Collector failed."});if(context.cancellationToken.cancelled){execution.leaseOwner=null;execution.leaseExpiresAt=null;execution.completedAt=this.now();await this.transition(execution,"cancelled");throw error;}if(attempt<collector.definition.retryPolicy.maxAttempts){await this.transition(execution,"retried");await this.sleep(this.retry.delay(attempt,collector.definition.retryPolicy.baseDelayMs,collector.definition.retryPolicy.maxDelayMs));}}}execution.leaseOwner=null;execution.leaseExpiresAt=null;execution.completedAt=this.now();await this.services.repository.save(execution);throw last; }
 private async transition(execution:CollectorExecution,status:ExecutionStatus,details:Record<string,unknown>={}){execution.status=status;await this.services.repository.save(execution);await this.services.repository.appendEvent({eventId:crypto.randomUUID(),executionId:execution.executionId,status,occurredAt:this.now(),attempt:execution.attemptCount,details});}
}
