import type { CancellationToken, CollectorExecution, ExecutionEvent, ExecutionRepository, RuntimeLogger, RuntimeMetrics } from "./types";
export class CancellationManager implements CancellationToken { cancelled=false;cancel(){this.cancelled=true;}throwIfCancelled(){if(this.cancelled)throw new Error("Collector execution was cancelled.");} }
export class ConsoleRuntimeLogger implements RuntimeLogger {info(message:string,fields={}){console.info(message,fields);}warn(message:string,fields={}){console.warn(message,fields);}error(message:string,fields={}){console.error(message,fields);} }
export class MemoryMetrics implements RuntimeMetrics {readonly values=new Map<string,number>();increment(name:string,value=1){this.values.set(name,(this.values.get(name)??0)+value);}timing(name:string,milliseconds:number){this.values.set(name,milliseconds);} }
export class RetryManager {delay(attempt:number,base:number,max:number){return Math.min(max,base*2**Math.max(0,attempt-1));} }
export class TimeoutManager {async run<T>(operation:()=>Promise<T>,milliseconds:number){let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([operation(),new Promise<T>((_,reject)=>{timer=setTimeout(()=>reject(new Error(`Collector timed out after ${milliseconds}ms.`)),milliseconds);})]);}finally{if(timer)clearTimeout(timer);}}}
export class CostRecorder {readonly records:Array<{executionId:string;amount:number;currency:string}>=[];record(executionId:string,cost:{amount:number;currency:string}){if(cost.amount<0)throw new Error("Execution cost cannot be negative.");this.records.push({executionId,...cost});}}
export class AuditPublisher {private readonly repository:ExecutionRepository;constructor(repository:ExecutionRepository){this.repository=repository;}publish(event:ExecutionEvent){return this.repository.appendEvent(event);}}
export class MemoryExecutionRepository implements ExecutionRepository {readonly executions=new Map<string,CollectorExecution>();readonly events:ExecutionEvent[]=[];async create(value:CollectorExecution){const existing=[...this.executions.values()].find(e=>e.idempotencyKey===value.idempotencyKey);if(existing)return {execution:structuredClone(existing),created:false};this.executions.set(value.executionId,structuredClone(value));return {execution:value,created:true};}async get(id:string){const value=this.executions.get(id);return value?structuredClone(value):null;}async save(value:CollectorExecution){this.executions.set(value.executionId,structuredClone(value));}async appendEvent(value:ExecutionEvent){this.events.push(structuredClone(value));}async history(id:string){return this.events.filter(e=>e.executionId===id).map(e=>structuredClone(e));}}
