"use client";

import { useCallback, useEffect, useId, useRef, useState } from "react";
import ShadowScoreLayout from "@/app/components/ShadowScoreLayout";
import { useLocale } from "@/components/LocaleProvider";
import type { CaseDto } from "@/lib/workspace/cases";
import type { TimelineCategory, TimelineEventDto, TimelinePageDto } from "@/lib/workspace/domain";
import { caseDetailsCopy, type CaseDetailsCopy } from "@/lib/workspace/caseDetailsCopy";
import { FindingsWorkspace } from "./FindingsWorkspace";

type Tab = "overview" | "timeline" | "evidence" | "findings" | "decision" | "report";
const tabs: Tab[] = ["overview", "timeline", "evidence", "findings", "decision", "report"];
const filters: TimelineCategory[] = ["all", "case", "evidence", "finding", "analyst", "decision", "monitoring", "report"];

export function CaseDetailsWorkspace({ caseDetail, ownerName, canEdit }: { caseDetail: CaseDto; ownerName: string; canEdit: boolean }) {
  const { locale } = useLocale();
  const copy = caseDetailsCopy[locale];
  const [tab, setTab] = useState<Tab>("overview");
  const tabRefs = useRef<Array<HTMLButtonElement | null>>([]);
  const tabId = useId();
  function moveTab(event: React.KeyboardEvent<HTMLButtonElement>, index: number) {
    const key = event.key;
    if (!(["ArrowRight", "ArrowLeft", "Home", "End"].includes(key))) return;
    event.preventDefault();
    const next = key === "Home" ? 0 : key === "End" ? tabs.length - 1 : (index + (key === "ArrowRight" ? 1 : -1) + tabs.length) % tabs.length;
    setTab(tabs[next]); tabRefs.current[next]?.focus();
  }
  return <ShadowScoreLayout><main className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:py-10">
    <header className="border-b border-white/10 pb-6"><p className="ui-label">{copy.caseWorkspace}</p><div className="mt-2 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-black tracking-tight text-white sm:text-4xl">{caseDetail.title}</h1><p className="mt-2 text-sm text-zinc-400">{copy.investigationCase} · <span className="font-medium text-zinc-300">{caseDetail.investigationId}</span></p></div><div className="flex gap-2"><Badge>{formatLabel(caseDetail.status)}</Badge><Badge tone={caseDetail.priority}>{formatLabel(caseDetail.priority)}</Badge></div></div>
      <dl className="mt-6 grid gap-x-6 gap-y-4 border-t border-white/10 pt-5 text-sm sm:grid-cols-2 lg:grid-cols-4"><Meta label={copy.owner} value={ownerName || copy.unassigned} /><Meta label={copy.dueDate} value={caseDetail.dueAt ? exactDate(caseDetail.dueAt, locale) : copy.noDueDate} /><Meta label={copy.lastUpdated} value={relativeTime(caseDetail.updatedAt)} title={exactDate(caseDetail.updatedAt, locale)} /><Meta label={copy.caseReference} value={caseDetail.id} /><Meta label={copy.investigationType} value={copy.businessDueDiligence} /></dl>
    </header>
    <div className="mt-5 overflow-x-auto border-b border-white/10"><div role="tablist" aria-label={copy.caseSections} className="flex min-w-max gap-1">{tabs.map((item, index) => <button key={item} ref={(node) => { tabRefs.current[index] = node; }} id={`${tabId}-${item}-tab`} role="tab" aria-selected={tab === item} aria-controls={`${tabId}-${item}-panel`} tabIndex={tab === item ? 0 : -1} onKeyDown={(event) => moveTab(event, index)} onClick={() => setTab(item)} className={`min-h-11 border-b-2 px-4 text-sm font-bold focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-3px] focus-visible:outline-sky-300 ${tab === item ? "border-sky-400 text-sky-200" : "border-transparent text-zinc-400 hover:text-zinc-100"}`}>{copy.tabs[item]}</button>)}</div></div>
    {tabs.map((item) => <section key={item} id={`${tabId}-${item}-panel`} role="tabpanel" aria-labelledby={`${tabId}-${item}-tab`} hidden={tab !== item} className="pt-6">{item === "timeline" ? <Timeline caseId={caseDetail.id} copy={copy} /> : item === "findings" ? <FindingsWorkspace caseId={caseDetail.id} canEdit={canEdit} /> : <Placeholder tab={copy.tabs[item]} copy={copy} />}</section>)}
  </main></ShadowScoreLayout>;
}

function Timeline({ caseId, copy }: { caseId: string; copy: CaseDetailsCopy }) {
  const [category, setCategory] = useState<TimelineCategory>("all"); const [events, setEvents] = useState<TimelineEventDto[]>([]); const [cursor, setCursor] = useState<string | null>(null); const [state, setState] = useState<"loading" | "ready" | "error">("loading"); const [expanded, setExpanded] = useState<string | null>(null);
  const load = useCallback(async (next?: string, nextCategory: TimelineCategory = category) => { setState(next ? "ready" : "loading"); try { const params = new URLSearchParams({ category: nextCategory, limit: "25" }); if (next) params.set("cursor", next); const response = await fetch(`/api/cases/${encodeURIComponent(caseId)}/timeline?${params}`); if (!response.ok) throw new Error("timeline"); const page = await response.json() as TimelinePageDto; setEvents((current) => next ? [...current, ...page.events] : [...page.events]); setCursor(page.nextCursor); setState("ready"); } catch { setState("error"); } }, [caseId, category]);
  useEffect(() => { const task = window.setTimeout(() => { void load(undefined, category); }, 0); return () => window.clearTimeout(task); }, [category, load]);
  return <div className="rounded-2xl border border-white/10 bg-white/[.025] p-4 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="ui-label">{copy.activityHistory}</p><h2 className="mt-1 text-2xl font-black text-white">{copy.timeline}</h2><p className="mt-2 text-sm text-zinc-400">{copy.timelineDescription}</p></div><div role="group" aria-label={copy.filterTimelineEvents} className="flex max-w-full flex-wrap gap-2">{filters.map((filter) => <button key={filter} onClick={() => setCategory(filter)} aria-pressed={category === filter} className={`min-h-9 rounded-lg border px-3 text-xs font-bold focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-300 ${category === filter ? "border-sky-400 bg-sky-400 text-slate-950" : "border-white/10 text-zinc-300 hover:bg-white/5"}`}>{copy.filters[filter]}</button>)}</div></div>
    {state === "loading" && <div role="status" className="mt-6 space-y-3"><span className="sr-only">{copy.loadingTimeline}</span>{[1,2,3].map((i) => <div key={i} className="h-20 animate-pulse rounded-xl bg-white/[.05]" />)}</div>}
    {state === "error" && <div role="alert" className="mt-6 rounded-xl border border-red-400/30 bg-red-950/25 p-4 text-sm text-red-100"><p className="font-bold">{copy.timelineUnavailable}</p><p className="mt-1 text-red-200/80">{copy.timelineRetryHelp}</p><button onClick={() => void load()} className="mt-3 min-h-10 rounded-lg border border-red-300/50 px-3 font-bold focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-200">{copy.retry}</button></div>}
    {state === "ready" && !events.length && <div className="mt-6 rounded-xl border border-dashed border-white/15 p-6 text-center"><p className="font-bold text-white">{copy.noActivity}</p><p className="mt-1 text-sm text-zinc-400">{copy.noActivityHelp}</p></div>}
    {state === "ready" && events.length > 0 && <ol className="mt-6 divide-y divide-white/10">{events.map((event) => <li key={event.id} className="py-4 first:pt-0"><button onClick={() => setExpanded(expanded === event.id ? null : event.id)} aria-expanded={expanded === event.id} className="group grid w-full grid-cols-[2rem_minmax(0,1fr)_auto] gap-3 text-left focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-sky-300"><span aria-hidden className="flex h-8 w-8 items-center justify-center rounded-lg bg-white/8 text-sm">{iconFor(event.category)}</span><span><span className="block font-bold text-white group-hover:text-sky-200">{event.title}</span>{event.detail && <span className="mt-1 block text-sm leading-6 text-zinc-400">{event.detail}</span>}<span className="mt-2 block text-xs text-zinc-500">{actorLabel(event.actorType)} · {event.category}</span></span><time dateTime={event.occurredAt} title={exactDate(event.occurredAt, "en")} className="whitespace-nowrap text-xs text-zinc-500">{relativeTime(event.occurredAt)}</time></button>{expanded === event.id && <div className="ml-11 mt-3 rounded-lg border border-white/10 bg-black/20 p-3 text-sm text-zinc-300"><p>{copy.eventType}: <span className="font-medium text-zinc-100">{event.eventType}</span></p>{event.referenceIds.length > 0 && <div className="mt-3"><p className="text-xs font-bold uppercase tracking-wide text-zinc-500">{copy.relatedRecords}</p><div className="mt-2 flex flex-wrap gap-2">{event.referenceIds.map((reference) => <a key={reference} href={`#reference-${encodeURIComponent(reference)}`} className="rounded border border-sky-400/30 px-2 py-1 text-xs font-bold text-sky-200 hover:bg-sky-400/10 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-300">{copy.viewRelatedRecord}</a>)}</div></div>}</div>}</li>)}</ol>}
    {state === "ready" && cursor && <button onClick={() => void load(cursor)} className="mt-5 min-h-11 rounded-xl border border-white/15 px-4 text-sm font-bold text-zinc-200 hover:bg-white/5 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-300">{copy.loadOlderActivity}</button>}
  </div>;
}
function Placeholder({ tab, copy }: { tab: string; copy: CaseDetailsCopy }) { return <div className="rounded-2xl border border-dashed border-white/15 bg-white/[.02] p-8"><p className="ui-label">{tab}</p><h2 className="mt-2 text-xl font-black text-white">{copy.sectionPending}</h2><p className="mt-2 text-sm text-zinc-400">{copy.sectionPendingHelp}</p></div>; }
function Meta({ label, value, title }: { label: string; value: string; title?: string }) { return <div><dt className="text-xs font-bold uppercase tracking-wide text-zinc-500">{label}</dt><dd title={title} className="mt-1 font-medium text-zinc-200">{value}</dd></div>; }
function Badge({ children, tone }: { children: React.ReactNode; tone?: string }) { return <span className={`rounded-full border px-3 py-1.5 text-xs font-bold ${tone === "critical" ? "border-red-400/40 bg-red-500/10 text-red-200" : tone === "high" ? "border-amber-400/40 bg-amber-500/10 text-amber-200" : "border-sky-400/35 bg-sky-500/10 text-sky-200"}`}>{children}</span>; }
function formatLabel(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function iconFor(category: TimelineEventDto["category"]) { return ({ case: "▣", evidence: "⌁", finding: "!", analyst: "✎", decision: "✓", monitoring: "◉", report: "▤" })[category]; }
function actorLabel(actor: TimelineEventDto["actorType"]) { return actor === "user" ? "Analyst" : actor === "provider" ? "Source" : "System"; }
function relativeTime(value: string) { const seconds = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 1000)); if (seconds < 60) return "just now"; const minutes = Math.floor(seconds / 60); if (minutes < 60) return `${minutes}m ago`; const hours = Math.floor(minutes / 60); if (hours < 24) return `${hours}h ago`; const days = Math.floor(hours / 24); return `${days}d ago`; }
function exactDate(value: string, locale: string) { return new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
