import Link from "next/link";
import ShadowScoreLayout from "@/components/ShadowScoreLayout";

const entityTypes = ["Company", "Person", "Email", "Domain", "Seller or account", "Other identifier"];
const workflow = [
  ["Investigate an entity", "Begin with the identifier you know. Keep it as the anchor for the Investigation."],
  ["Connect fragmented public signals", "Organize relevant business, registry, open-web, and digital identity signals in the Entity Graph."],
  ["Separate leads from verified evidence", "Keep Discovery Candidates, Corroborated Evidence, and Verified Facts clearly labeled."],
  ["See relationships and provenance", "Understand how entities connect and return every useful finding to its source."],
  ["Make a decision", "Document material findings, evidence gaps, and next actions in an Executive Report."],
  ["Continue monitoring", "Review Alerts when relevant public signals change after the initial decision."],
];

export default function MarketingHome() {
  return <ShadowScoreLayout hideReviewMessaging><main className="bg-[#07111f] text-slate-100">
    <section className="bg-[radial-gradient(circle_at_78%_15%,rgba(14,165,233,.22),transparent_32%)] px-6 py-20 sm:py-28"><div className="mx-auto grid max-w-6xl gap-14 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-sky-300">Entity intelligence for business decisions</p><h1 className="mt-5 text-5xl font-black leading-[1.02] tracking-[-.045em] sm:text-7xl">Understand who or what you are dealing with</h1><p className="mt-7 max-w-2xl text-xl leading-8 text-slate-300">Investigate people, companies, domains, emails, sellers, counterparties, and related entities. ShadowScore connects public signals, preserves provenance, and turns evidence into a decision record.</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/intake" className="rounded-full bg-sky-400 px-7 py-4 font-bold text-slate-950 hover:bg-sky-300">Start an Investigation</Link><Link href="/platform" className="rounded-full border border-white/20 px-7 py-4 font-bold hover:bg-white/10">Explore the platform</Link></div></div><aside className="rounded-[2rem] border border-white/15 bg-slate-950/80 p-7" aria-labelledby="start-heading"><h2 id="start-heading" className="text-2xl font-bold">Start from what you know</h2><p className="mt-3 text-slate-400">One identifier can open a path to relevant entities, relationships, and evidence.</p><ul className="mt-6 grid grid-cols-2 gap-3">{entityTypes.map(type=><li key={type} className="rounded-2xl border border-white/10 bg-white/[.04] p-4 font-bold text-slate-200">{type}</li>)}</ul></aside></div></section>
    <section className="border-y border-white/10 bg-slate-950 px-6 py-20" aria-labelledby="workflow-heading"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-sky-300">Investigation workflow</p><h2 id="workflow-heading" className="mt-4 max-w-3xl text-4xl font-bold">Move from an initial signal to a decision you can explain</h2><ol className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{workflow.map(([title,body],index)=><li key={title} className="rounded-3xl border border-white/10 bg-white/[.035] p-7"><span className="text-sm font-black text-sky-300">0{index+1}</span><h3 className="mt-3 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-300">{body}</p></li>)}</ol></div></section>
    <section className="px-6 py-20"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-amber-300">Evidence discipline</p><h2 className="mt-4 text-3xl font-bold">Discovery supports the investigation. Evidence supports the decision.</h2><p className="mt-5 leading-7 text-slate-300">A promising public match remains a Discovery Candidate. Independent support can make it Corroborated Evidence. Only evidence that meets the investigation standard becomes a Verified Fact. ShadowScore keeps these states visible to non-specialist reviewers.</p></div><div className="rounded-3xl border border-white/10 bg-[#0a1626] p-8"><h2 className="text-2xl font-bold">One connected record</h2><ul className="mt-5 space-y-4 text-slate-300"><li><strong className="text-white">Entity Graph:</strong> people, organizations, identifiers, and Relationships.</li><li><strong className="text-white">Provenance:</strong> the source and context behind each finding.</li><li><strong className="text-white">Executive Report:</strong> the decision, evidence, gaps, and next actions.</li><li><strong className="text-white">Monitoring and Alerts:</strong> continued review after the first decision.</li></ul></div></div></section>
    <section className="border-t border-white/10 bg-[#0a1626] px-6 py-16 text-center"><h2 className="text-3xl font-bold">Investigate the entity behind your next decision</h2><p className="mx-auto mt-4 max-w-2xl text-slate-300">Build a source-backed view of identity, relationships, evidence, and remaining questions.</p><Link href="/intake" className="mt-7 inline-flex rounded-full bg-sky-400 px-7 py-4 font-bold text-slate-950 hover:bg-sky-300">Start an Investigation</Link></section>
  </main></ShadowScoreLayout>;
}
