import Link from "next/link";
import ShadowScoreLayout from "@/components/ShadowScoreLayout";
import type { PublicPage } from "../lib/public-pages";

export default function PublicContentPage({ page }: { page: PublicPage }) {
  const crumbs = page.path.split("/").filter(Boolean);
  const jsonLd = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home", item: "https://shadowscore.io/" },
    ...crumbs.map((crumb, index) => ({ "@type": "ListItem", position: index + 2, name: index === crumbs.length - 1 ? page.heading : crumb.replaceAll("-", " "), item: `https://shadowscore.io/${crumbs.slice(0,index+1).join("/")}` }))
  ] };
  return <ShadowScoreLayout hideReviewMessaging>
    <main className="bg-[#07111f] text-slate-100">
      <nav aria-label="Breadcrumb" className="border-b border-white/10 px-6 py-4"><ol className="mx-auto flex max-w-6xl flex-wrap gap-2 text-sm text-slate-400"><li><Link className="hover:text-white" href="/">Home</Link></li>{crumbs.map((crumb,index)=><li key={crumb} className="flex gap-2"><span aria-hidden="true">/</span>{index === crumbs.length-1 ? <span aria-current="page" className="text-slate-200">{page.heading}</span> : <Link className="capitalize hover:text-white" href={`/${crumbs.slice(0,index+1).join("/")}`}>{crumb.replaceAll("-"," ")}</Link>}</li>)}</ol></nav>
      <section className="bg-[radial-gradient(circle_at_75%_20%,rgba(14,165,233,.18),transparent_32%)] px-6 py-20 sm:py-28"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-[.24em] text-sky-300">{page.eyebrow}</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[1.04] tracking-[-.04em] sm:text-6xl">{page.heading}</h1><p className="mt-7 max-w-3xl text-xl leading-8 text-slate-300">{page.intro}</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/intake" className="rounded-full bg-sky-400 px-6 py-3 font-bold text-slate-950 hover:bg-sky-300">Start an Investigation</Link><Link href="/contact" className="rounded-full border border-white/20 px-6 py-3 font-bold hover:bg-white/10">Talk to ShadowScore</Link></div></div></section>
      <section className="border-y border-white/10 bg-slate-950 px-6 py-20" aria-labelledby="capabilities"><div className="mx-auto max-w-6xl"><h2 id="capabilities" className="text-3xl font-bold">From public signal to usable intelligence</h2><div className="mt-9 grid gap-5 md:grid-cols-3">{page.capabilities.map(item=><article key={item.title} className="rounded-3xl border border-white/10 bg-white/[.035] p-7"><h3 className="text-xl font-bold text-white">{item.title}</h3><p className="mt-3 leading-7 text-slate-300">{item.body}</p></article>)}</div></div></section>
      <section className="px-6 py-20"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-amber-300">Evidence and provenance</p><h2 className="mt-4 text-3xl font-bold">Know why every finding appears</h2><p className="mt-5 leading-7 text-slate-300">ShadowScore records sources and relationship context. A Discovery Candidate is a lead. Corroborated Evidence has independent support. A Verified Fact meets the investigation standard for use in a decision. The distinction stays visible in the Entity Graph and Executive Report.</p></div><div><h2 className="text-2xl font-bold">Continue exploring</h2><div className="mt-5 space-y-3">{page.related.map(item=><Link key={item.href} href={item.href} className="block rounded-2xl border border-white/10 p-5 hover:border-sky-300/50 hover:bg-white/[.035]"><span className="font-bold text-sky-200">{item.label}</span><span className="mt-1 block text-sm leading-6 text-slate-400">{item.description}</span></Link>)}</div></div></div></section>
      <section className="border-t border-white/10 bg-[#0a1626] px-6 py-16 text-center"><h2 className="text-3xl font-bold">Investigate the entity behind your next decision</h2><p className="mx-auto mt-4 max-w-2xl text-slate-300">Start with a company, person, email, domain, seller account, or another identifier.</p><Link href="/intake" className="mt-7 inline-flex rounded-full bg-sky-400 px-6 py-3 font-bold text-slate-950 hover:bg-sky-300">Start an Investigation</Link></section>
    </main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd).replace(/</g,"\\u003c")}} />
  </ShadowScoreLayout>;
}
