export type SubjectType = "domain" | "website" | "business" | "marketplace_account" | "email" | "phone" | "person" | "payment_account" | "social_account" | "wallet" | "ip_address" | "unknown";
export type SubjectVisibility = "private" | "public";
export type JobStatus = "queued" | "running" | "waiting_retry" | "completed" | "failed" | "cancelled";
export type StageStatus = "pending" | "running" | "completed" | "failed" | "skipped" | "waiting_retry";
export type FreshnessStatus = "fresh" | "stale" | "expired" | "unknown";

export type Subject = { subjectId:string; subjectType:SubjectType; canonicalName:string; displayName:string; status:"active"|"merged"|"archived"; workspaceId:string|null; visibility:SubjectVisibility; mergedIntoSubjectId:string|null; metadata:Record<string,unknown>; createdAt:string; updatedAt:string };
export type SubjectIdentifier = { identifierId:string; subjectId:string; identifierType:string; normalizedValue:string; displayValue:string; source:string; verificationStatus:"unverified"|"verified"|"disputed"; firstSeenAt:string; lastSeenAt:string; metadata:Record<string,unknown> };
export type InvestigationStage = { stageId:string; investigationJobId:string; stageName:string; status:StageStatus; attemptCount:number; startedAt:string|null; completedAt:string|null; nextRetryAt:string|null; failureCode:string|null; sanitizedFailureMessage:string|null; inputReference:string|null; outputReference:string|null; metadata:Record<string,unknown> };
export type InvestigationJob = { investigationJobId:string; subjectId:string; workspaceId:string|null; requestedByUserId:string|null; investigationType:string; status:JobStatus; priority:number; attemptCount:number; maxAttempts:number; idempotencyKey:string; currentStage:string|null; createdAt:string; queuedAt:string; startedAt:string|null; completedAt:string|null; failedAt:string|null; nextRetryAt:string|null; leaseOwner:string|null; leaseExpiresAt:string|null; sanitizedFailureCode:string|null; sanitizedFailureMessage:string|null; metadata:Record<string,unknown> };
export type EvidenceObservation = { observationId:string; subjectId:string; investigationJobId:string; provider:string; evidenceType:string; normalizedKey:string; normalizedValue:string|null; structuredValue:unknown; confidence:number|null; observedAt:string; validFrom:string; expiresAt:string|null; freshnessStatus:FreshnessStatus; sourceReference:string|null; rawPayloadReference:string|null; providerVersion:string|null; collectorVersion:string; policyVersion:string; createdAt:string; metadata:Record<string,unknown> };
