import test from "node:test";
import assert from "node:assert/strict";
import { CancellationManager, CollectorRegistry, CollectorRuntime, InvestigationPlanner, MemoryExecutionRepository, MemoryMetrics, WebsiteCollector } from "../lib/collectorRuntime/index.ts";
import { MemoryEvidenceRepository } from "../lib/evidenceV2/index.ts";

const subject={subjectId:"subject-1",subjectType:"domain",canonicalName:"example.com",displayName:"example.com",status:"active",workspaceId:"workspace-1",visibility:"private",mergedIntoSubjectId:null,metadata:{},createdAt:"2026-07-26T00:00:00Z",updatedAt:"2026-07-26T00:00:00Z"};
const identifier={identifierId:"identifier-1",subjectId:"subject-1",identifierType:"domain",normalizedValue:"example.com",displayValue:"example.com",source:"user",verificationStatus:"unverified",firstSeenAt:"2026-07-26T00:00:00Z",lastSeenAt:"2026-07-26T00:00:00Z",metadata:{}};
function definition(overrides={}){return {collectorKey:"fixture",version:"1.0.0",capability:"fixture",supportedSubjectTypes:["domain"],supportedIdentifierTypes:["domain"],requiredProviders:[],requiredEntitlements:["investigation"],pricingCategory:"fixture",timeoutMs:100,retryPolicy:{maxAttempts:2,baseDelayMs:0,maxDelayMs:0},priority:10,dependencies:[],healthStatus:"healthy",...overrides};}
function context(){return {subject,identifiers:[identifier],workspace:{workspaceId:"workspace-1"},investigation:{investigationId:"investigation-1"},pricing:{currency:"USD",category:"fixture"},permissions:["investigation"],cancellationToken:new CancellationManager(),logger:{info(){},warn(){},error(){}},metrics:new MemoryMetrics(),evidenceRepository:new MemoryEvidenceRepository()};}

test("planner selects collectors from registry metadata",()=>{const registry=new CollectorRegistry().register({definition:definition(),async validate(){},async collect(){throw new Error("unused");}});const plan=new InvestigationPlanner(registry,()=>"2026-07-26T00:00:00Z").plan({subject,identifiers:[identifier],workspace:{workspaceId:"workspace-1"},investigationId:"investigation-1",enabledCapabilities:["fixture"],pricingPlan:"standard",entitlements:["investigation"]});assert.deepEqual(plan.collectors.map(item=>item.collectorKey),["fixture"]);});
test("planner excludes disabled and unentitled collectors",()=>{const registry=new CollectorRegistry().register({definition:definition({requiredEntitlements:["premium"]}),async validate(){},async collect(){throw new Error("unused");}});const plan=new InvestigationPlanner(registry).plan({subject,identifiers:[identifier],workspace:{workspaceId:"workspace-1"},investigationId:"investigation-1",enabledCapabilities:["fixture"],pricingPlan:"standard",entitlements:["investigation"]});assert.equal(plan.collectors.length,0);});
test("runtime records lifecycle and successful output",async()=>{const registry=new CollectorRegistry().register({definition:definition(),async validate(){},async collect(){return {observations:[],metrics:{ok:1},warnings:[],errors:[],executionCost:{amount:0,currency:"USD"}};}});const repository=new MemoryExecutionRepository();const result=await new CollectorRuntime(registry,{repository,sleep:async()=>{}}).execute({collectorKey:"fixture",idempotencyKey:"same",leaseOwner:"worker-1",leaseMs:1000,context:context()});assert.equal(result.execution.status,"completed");assert.deepEqual((await repository.history(result.execution.executionId)).map(event=>event.status),["queued","running","succeeded","completed"]);});
test("runtime retries failed collection",async()=>{let calls=0;const registry=new CollectorRegistry().register({definition:definition(),async validate(){},async collect(){if(++calls===1)throw new Error("temporary");return {observations:[],metrics:{},warnings:[],errors:[],executionCost:{amount:0,currency:"USD"}};}});const repository=new MemoryExecutionRepository();const result=await new CollectorRuntime(registry,{repository,sleep:async()=>{}}).execute({collectorKey:"fixture",idempotencyKey:"retry",leaseOwner:"worker-1",leaseMs:1000,context:context()});assert.equal(calls,2);assert.equal(result.execution.attemptCount,2);assert.ok((await repository.history(result.execution.executionId)).some(event=>event.status==="retried"));});
test("runtime enforces collector timeout",async()=>{const registry=new CollectorRegistry().register({definition:definition({timeoutMs:5,retryPolicy:{maxAttempts:1,baseDelayMs:0,maxDelayMs:0}}),async validate(){},async collect(){await new Promise(resolve=>setTimeout(resolve,30));throw new Error("late");}});await assert.rejects(()=>new CollectorRuntime(registry,{repository:new MemoryExecutionRepository()}).execute({collectorKey:"fixture",idempotencyKey:"timeout",leaseOwner:"worker-1",leaseMs:1000,context:context()}),/timed out/);});
test("runtime idempotency returns the original execution",async()=>{let calls=0;const registry=new CollectorRegistry().register({definition:definition(),async validate(){},async collect(){calls++;return {observations:[],metrics:{},warnings:[],errors:[],executionCost:{amount:0,currency:"USD"}};}});const repository=new MemoryExecutionRepository();const runtime=new CollectorRuntime(registry,{repository});const input={collectorKey:"fixture",idempotencyKey:"duplicate",leaseOwner:"worker-1",leaseMs:1000,context:context()};const first=await runtime.execute(input);const second=await runtime.execute(input);assert.equal(second.execution.executionId,first.execution.executionId);assert.equal(second.created,false);assert.equal(calls,1);});
test("Website Collector preserves the existing scan boundary and observation-only contract",()=>{const collector=new WebsiteCollector();assert.equal(collector.definition.collectorKey,"website_intelligence");assert.deepEqual(collector.definition.supportedSubjectTypes,["domain","website"]);assert.equal("scan" in collector,false);assert.equal("report" in collector,false);});
