import test from "node:test";
import assert from "node:assert/strict";
import { ContinuousResolutionEngine, IdentityIndex, ResolutionScheduler } from "../lib/continuousResolution/index.ts";
import { createObservation, DEFAULT_RESOLVER_POLICY } from "../lib/entityIntelligence/index.ts";
import { demoEntities, demoObservations } from "../lib/entityIntelligence/seed.ts";

const now="2026-07-26T12:00:00.000Z";
const observation=(id,attribute,value,reliability=.9)=>createObservation({observationId:id,workspaceId:"demo-workspace",source:"runtime-test",sourceRecordId:id,attribute,observedValue:value,observedAt:now,jurisdiction:"IL",evidenceReference:`evidence://test/${id}`,reliability});

test("indexes every identity anchor and updates entries without stale values",()=>{const index=new IdentityIndex(),entity={...structuredClone(demoEntities[0]),aliases:["Atlas Shop"]};index.upsert(entity);for(const [attribute,value] of [["registration_id","515001234"],["domain","atlas.co.il"],["email","legal@atlas.co.il"],["phone","97235550140"],["name","atlas commerce"],["address","14 haarbaa street tel aviv"],["director","noa levi"]])assert.deepEqual(index.candidates(attribute,value),[entity.entityId]);assert.deepEqual(index.candidates("name","atlas shop"),[entity.entityId]);index.upsert({...entity,domains:["new.example"]});assert.deepEqual(index.candidates("domain","atlas.co.il"),[]);});

test("new observations resolve only indexed candidates and append versioned events",()=>{const engine=new ContinuousResolutionEngine({entities:demoEntities,observations:demoObservations});const result=engine.addObservation(observation("new-domain","domain","atlas.co.il"),"ent-atlas-il");assert.deepEqual(result.candidates,["ent-atlas-market"]);assert.equal(result.decisions.length,1);const events=engine.eventPage(null,100).data;assert.equal(events[0].type,"ObservationAdded");assert.ok(events.some(event=>event.type==="EntityMatched"));assert.ok(events.some(event=>event.type==="EntityProjectionUpdated"));assert.ok(events.every(event=>event.schemaVersion===1));assert.equal(engine.addObservation(observation("new-domain","domain","atlas.co.il"),"ent-atlas-il").idempotent,true);});

test("projections rebuild from the append-only history",()=>{const engine=new ContinuousResolutionEngine({entities:demoEntities,observations:demoObservations});engine.addObservation(observation("merge-domain","domain","atlas.co.il"),"ent-atlas-il");const before=engine.projection("ent-atlas-il");assert.ok(before.aliases.includes("אטלס מסחר בע\"מ"));assert.equal(engine.rebuildProjections(),demoEntities.length);assert.deepEqual(engine.projection("ent-atlas-il"),before);assert.equal(demoEntities[0].aliases.includes("אטלס מסחר בע\"מ"),false);});

test("confidence drift emits an event when evidence crosses a threshold",()=>{const entity={...structuredClone(demoEntities[3]),observationIds:[]};const engine=new ContinuousResolutionEngine({entities:[entity]});engine.addObservation(observation("strong","email","ops@northstar.systems",.9),entity.entityId);assert.ok(engine.eventPage(null,100).data.some(event=>event.type==="ConfidenceChanged"&&event.payload.threshold==="high"));});

test("event and timeline cursors are stable and bounded",()=>{const engine=new ContinuousResolutionEngine({entities:demoEntities,observations:demoObservations});engine.addObservation(observation("cursor-domain","domain","atlas.co.il"),"ent-atlas-il");const first=engine.eventPage(null,2),second=engine.eventPage(first.nextCursor,2);assert.equal(first.data.length,2);assert.ok(first.nextCursor);assert.notEqual(first.data[0].eventId,second.data[0].eventId);const timeline=engine.timeline("ent-atlas-il",null,2);assert.equal(timeline.data.length,2);assert.ok(timeline.data.every(item=>item.event.entityId==="ent-atlas-il"||JSON.stringify(item.event.payload).includes("ent-atlas-il")));});

test("scheduler retries failed jobs and deduplicates idempotency keys",async()=>{const engine=new ContinuousResolutionEngine({entities:demoEntities}),scheduler=new ResolutionScheduler(engine);const input={idempotencyKey:"observation-1",reason:"new_observation",workspaceId:"demo-workspace",entityId:"missing",observation:observation("scheduled","domain","atlas.co.il"),maxAttempts:2};assert.equal(scheduler.enqueue(input).jobId,scheduler.enqueue(input).jobId);await scheduler.drain();assert.equal(scheduler.snapshot()[0].status,"queued");await scheduler.drain();assert.equal(scheduler.snapshot()[0].status,"failed");assert.equal(scheduler.snapshot()[0].attempts,2);});

test("policy changes and evidence expiration are represented as immutable events",()=>{const engine=new ContinuousResolutionEngine({entities:demoEntities,observations:demoObservations});engine.changePolicy({...DEFAULT_RESOLVER_POLICY,version:"organization-resolution-policy@1.1.0"},"demo-workspace",now);assert.equal(engine.expireEvidence("ent-atlas-il-reg",now),true);const events=engine.eventPage(null,100).data;assert.ok(events.some(event=>event.type==="PolicyChanged"));assert.ok(events.some(event=>event.type==="EvidenceExpired"));});
