import test from "node:test";
import assert from "node:assert/strict";
import { MemoryEvidenceRepository, NormalizationPipeline, EvidenceQuarantineError } from "../lib/evidenceV2/index.ts";
const policy={version:"website-v1",allowedObservationTypes:new Set(["website.dns"]),taxonomyFor:o=>o.observationType==="website.dns"?"website.dns.nameserver":null,canonicalize:o=>String(o.value).trim().toLowerCase(),assertionKey:(o,t)=>`${o.subjectId}:${t}:${o.key}`,confidence:()=>({sourceReliability:.9,extractionQuality:.8,corroboration:.7,freshness:1})};
const input=(id,value=" NS1.EXAMPLE.COM ")=>({observationId:id,sourceInstanceId:"source-instance-1",subjectId:"subject-1",investigationId:"investigation-1",observationType:"website.dns",key:"nameserver",value,observedAt:"2026-07-26T10:00:00Z",validFrom:"2026-07-26T10:00:00Z",validTo:null});
test("normalization appends observations, assertions, evidence links, projections, and outbox",async()=>{const repo=new MemoryEvidenceRepository();const result=await new NormalizationPipeline(repo,policy,()=>"2026-07-26T12:00:00Z").process(input("observation-1"));assert.equal(result.assertion.value,"ns1.example.com");assert.equal(result.assertion.version,1);assert.equal(repo.links[0].observationId,"observation-1");assert.equal(repo.projections.size,1);assert.equal(repo.outbox[0].type,"evidence.assertion.appended")});
test("identical canonical values deduplicate assertions while retaining observations",async()=>{const repo=new MemoryEvidenceRepository();const pipeline=new NormalizationPipeline(repo,policy);await pipeline.process(input("observation-1"));const second=await pipeline.process(input("observation-2","ns1.example.com"));assert.equal(second.deduplicated,true);assert.equal(repo.observations.length,2);assert.equal(repo.assertions.length,1)});
test("a changed value creates a bitemporal assertion version and preserves history",async()=>{const repo=new MemoryEvidenceRepository();const pipeline=new NormalizationPipeline(repo,policy);const first=await pipeline.process(input("observation-1"));const second=await pipeline.process(input("observation-2","ns2.example.com"));assert.equal(second.assertion.version,2);assert.equal(second.assertion.supersedesAssertionId,first.assertion.assertionId);assert.equal(repo.assertions.length,2);repo.projections.clear();repo.rebuildProjections();assert.equal(repo.projections.values().next().value.version,2)});
test("invalid evidence is quarantined before assertions are created",async()=>{const repo=new MemoryEvidenceRepository();const pipeline=new NormalizationPipeline(repo,policy);await assert.rejects(()=>pipeline.process({...input("observation-1"),validTo:"2020-01-01T00:00:00Z"}),EvidenceQuarantineError);assert.equal(repo.quarantined[0].stage,"validate");assert.equal(repo.assertions.length,0)});
