import assert from "node:assert/strict";
import { FindingAccessError, FindingConflictError, FindingService, FindingValidationError } from "../lib/workspace/findings.ts";
const now="2026-07-24T00:00:00.000Z", evidence={id:"evidence-1",label:"Registry extract",source:"Registry",capturedAt:now};
const actor=(role="analyst")=>({userId:"user-a",organizationId:"org-a",role,name:"Alex",email:"a@example.com"});
class Store{constructor(){this.findings=[]}async list(){return{findings:this.findings.map(item=>({id:item.id,publicId:item.publicId,title:item.title,narrative:item.narrative,severity:item.severity,confidence:item.confidence,tags:item.tags,evidence:item.evidence,version:item.version,createdAt:item.createdAt,updatedAt:item.updatedAt})),evidence:[evidence]}}async create(a,caseId,input){const item={id:"internal-finding",publicId:"finding-1",caseId,organizationId:a.organizationId,...input,evidence:[evidence],version:1,createdBy:a.userId,updatedBy:a.userId,createdAt:now,updatedAt:now};this.findings=[item];return item}async update(a,caseId,id,input){const item=this.findings.find(f=>f.publicId===id);if(!item)return null;if(item.version!==input.version)return"conflict";Object.assign(item,input,{version:item.version+1});return item}async delete(a,caseId,id,version){const item=this.findings.find(f=>f.publicId===id);if(!item)return null;if(item.version!==version)return"conflict";this.findings=[];return"deleted"}}
const store=new Store(),service=new FindingService(store),valid={title:"Ownership mismatch",narrative:"The registry owner differs from the submitted owner.",severity:"high",confidence:"high",tags:["Ownership","ownership"],evidenceIds:[evidence.id]};
const created=await service.create(actor(),"case-1",valid);assert.equal(created.publicId,"finding-1");assert.deepEqual(created.tags,["ownership"]);assert.equal("organizationId" in created,false);assert.equal((await service.list(actor(),"case-1")).findings.length,1);
await assert.rejects(()=>service.create(actor("viewer"),"case-1",valid),FindingAccessError);await assert.rejects(()=>service.create(actor(),"case-1",{...valid,evidenceIds:[]}),FindingValidationError);await assert.rejects(()=>service.create(actor(),"case-1",{...valid,narrative:"short"}),FindingValidationError);
const updated=await service.update(actor(),"case-1","finding-1",{...valid,title:"Confirmed mismatch",version:1});assert.equal(updated.version,2);await assert.rejects(()=>service.update(actor(),"case-1","finding-1",{...valid,version:1}),FindingConflictError);await service.delete(actor(),"case-1","finding-1",2);assert.equal(store.findings.length,0);
console.log("findings workspace behavioral tests passed");
