import test from "node:test";import assert from "node:assert/strict";import {MemoryKnowledgeRepository,KnowledgeResolutionPipeline} from "../lib/knowledge/index.ts";
const policy={policyKey:"canonical-majority",version:"1",supportedTaxonomyKeys:["*"],supportedSubjectTypes:["*"],priority:100,deterministicRules:{},confidenceRules:{},conflictBehavior:"dispute",supersessionBehavior:"append",enabled:true};
const assertion=(assertionId,value,taxonomy="organization.country",subjectId="subject-1")=>({assertionId,assertionKey:`${subjectId}:${taxonomy}`,version:1,taxonomy,subjectId,value,provenance:{},confidence:{sourceReliability:.9,extractionQuality:.9,corroboration:.9,freshness:.9,overall:.9},validFrom:"2026-07-26T00:00:00Z",validTo:null,recordedAt:"2026-07-26T00:00:00Z",supersedesAssertionId:null,policyVersion:"evidence-1",canonicalValueHash:String(value)});
const setup=(values)=>{const r=new MemoryKnowledgeRepository();r.policies.push(policy);r.assertions.push(...values.map((v,i)=>assertion(`assertion-${i}`,v)));return {r,p:new KnowledgeResolutionPipeline({assertions:r,facts:r,relationships:r,candidates:r,conflicts:r,projections:r,policies:r,events:r},()=>"2026-07-26T12:00:00Z")};};
test("creates a current fact with mandatory provenance",async()=>{const {r,p}=setup(["IL"]);await p.rebuild({workspaceId:"workspace-1",subjectId:"subject-1"});assert.equal(r.facts[0].resolutionStatus,"current");assert.deepEqual(r.facts[0].provenance.map(x=>x.assertionId),["assertion-0"]);});
test("keeps conflicting assertions visible and disputes the fact",async()=>{const {r,p}=setup(["IL","GB"]);await p.rebuild({workspaceId:"workspace-1"});assert.equal(r.facts[0].resolutionStatus,"disputed");assert.equal(r.conflicts[0].assertionIds.length,2);assert.ok(r.conflicts[0].severity>0);});
test("reruns are deterministic and projections are disposable",async()=>{const {r,p}=setup(["IL","IL"]);const first=await p.rebuild({workspaceId:"workspace-1"});const factId=first[0].facts[0].factId;await r.clear({workspaceId:"workspace-1"});const second=await p.rebuild({workspaceId:"workspace-1"});assert.equal(second[0].facts[0].factId,factId);assert.equal(r.facts.length,1);assert.ok(await r.get("subject-1"));});
test("policy versions create distinct ledger conclusions",async()=>{const {r,p}=setup(["IL"]);await p.rebuild({workspaceId:"workspace-1"});r.policies[0]={...policy,version:"2"};await p.rebuild({workspaceId:"workspace-1"});assert.equal(r.facts.length,2);assert.notEqual(r.facts[0].factId,r.facts[1].factId);});
test("taxonomy rebuild only resolves the requested taxonomy",async()=>{const {r,p}=setup(["IL"]);r.assertions.push(assertion("name-1","Example","organization.name"));const result=await p.rebuild({workspaceId:"workspace-1",taxonomyKey:"organization.country"});assert.deepEqual(result[0].facts.map(f=>f.taxonomyKey),["organization.country"]);});
