import test from "node:test";
import assert from "node:assert/strict";
import { SubjectResolutionService, normalizeDomain, normalizeWebsiteUrl } from "../lib/platformCore/subjects.ts";
import { transitionJob, retryDelayMs, InvalidJobTransitionError } from "../lib/platformCore/jobs.ts";
import { evidenceFreshness, providerCacheKey } from "../lib/platformCore/evidence.ts";
import { estimateProviderCost, summarizeUsage } from "../lib/platformCore/costs.ts";

class Store{subjects=new Map();identifiers=[];async findIdentifier(workspaceId,type,value){return this.identifiers.find(i=>i.identifierType===type&&i.normalizedValue===value&&this.subjects.get(i.subjectId)?.workspaceId===workspaceId)||null}async getSubject(id){return this.subjects.get(id)||null}async createSubject(s){this.subjects.set(s.subjectId,s)}async attachIdentifier(i){const old=this.identifiers.find(x=>x.subjectId===i.subjectId&&x.identifierType===i.identifierType&&x.normalizedValue===i.normalizedValue);if(old)return old;this.identifiers.push(i);return i}}
test("website identifiers normalize deterministically",()=>{assert.equal(normalizeDomain("HTTPS://Example.COM.:443/path"),"example.com");assert.equal(normalizeWebsiteUrl("http://Example.com:80/a#x"),"http://example.com/a")});
test("equivalent domains resolve once while uncertain businesses remain separate",async()=>{const store=new Store(),service=new SubjectResolutionService(store,()=>new Date("2026-01-01"));const a=await service.resolve({subjectType:"domain",value:"Example.com.",workspaceId:"w"});const b=await service.resolve({subjectType:"website",value:"https://example.com/path",workspaceId:"w"});assert.equal(a.subject.subjectId,b.subject.subjectId);assert.equal(store.identifiers.length,1);const c=await service.resolve({subjectType:"business",value:"Acme",workspaceId:"w"});const d=await service.resolve({subjectType:"business",value:"Acme",workspaceId:"w"});assert.notEqual(c.subject.subjectId,d.subject.subjectId)});
const job={investigationJobId:"j",subjectId:"s",workspaceId:"w",requestedByUserId:"u",investigationType:"website",status:"queued",priority:1,attemptCount:0,maxAttempts:3,idempotencyKey:"k",currentStage:null,createdAt:"",queuedAt:"",startedAt:null,completedAt:null,failedAt:null,nextRetryAt:null,leaseOwner:null,leaseExpiresAt:null,sanitizedFailureCode:null,sanitizedFailureMessage:null,metadata:{}};
test("job transitions reject rerunning terminal work",()=>{const running=transitionJob(job,"running");const done=transitionJob(running,"completed");assert.throws(()=>transitionJob(done,"running"),InvalidJobTransitionError);assert.equal(retryDelayMs(20),3600000)});
test("evidence freshness uses evidence-specific TTLs",()=>{const now=new Date("2026-01-03T00:00:00Z");assert.equal(evidenceFreshness("whois",new Date("2026-01-01"),now),"fresh");assert.equal(evidenceFreshness("dns",new Date("2026-01-01"),now),"expired");assert.equal(evidenceFreshness("custom",now,now),"unknown")});
test("cache keys include parameters and tenant scope",()=>{const base={provider:"dns",collectorVersion:"1",normalizedTarget:"example.com",requestType:"lookup",workspaceId:"w1"};assert.notEqual(providerCacheKey({...base,parameters:{type:"A"}}),providerCacheKey({...base,parameters:{type:"MX"}}));assert.notEqual(providerCacheKey({...base,parameters:{type:"A"}}),providerCacheKey({...base,workspaceId:"w2",parameters:{type:"A"}}))});
test("usage totals preserve unknown cost and cache attribution",()=>{assert.equal(estimateProviderCost({kind:"unknown"}),null);const out=summarizeUsage([{investigationJobId:"j",workspaceId:"w",provider:"dns",outcome:"completed",cacheHit:false,estimatedCostUsd:.1,actualCostUsd:null,requestStartedAt:""},{investigationJobId:"j",workspaceId:"w",provider:"dns",outcome:"failed",cacheHit:true,estimatedCostUsd:null,actualCostUsd:.2,requestStartedAt:""}]);assert.ok(Math.abs(out.totalCostUsd-.3)<Number.EPSILON);assert.equal(out.failedCallCostUsd,.2);assert.equal(out.cacheHits,1)});
