import test from "node:test";
import assert from "node:assert/strict";
import { evaluateFeature } from "../lib/platformCore/entitlements.ts";
import { priceUsage, selectPricingPolicy, validateCostRecord } from "../lib/platformCore/billing.ts";
import { summarizeWorkspaceUsage } from "../lib/platformCore/usage.ts";

const policy={policyId:"standard",version:2,currency:"USD",effectiveFrom:"2026-01-01T00:00:00Z",rules:[{ruleId:"dns",costSource:"external_provider",billingUnit:"provider",provider:"dns",unitPrice:{amount:.02,currency:"USD"}}]};
test("pricing is selected by effective date and remains configuration driven",()=>{assert.equal(selectPricingPolicy([{...policy,version:1},policy],new Date("2026-02-01"))?.version,2);assert.deepEqual(priceUsage(policy,{costSource:"external_provider",billingUnit:"provider",provider:"dns",quantity:3}),{amount:.06,currency:"USD"});assert.equal(priceUsage(policy,{costSource:"ai_model",billingUnit:"provider",quantity:1}),null)});
test("collector costs require complete attribution and one currency",()=>{assert.doesNotThrow(()=>validateCostRecord({executionId:"e",investigationId:"i",workspaceId:"w",provider:"dns",collector:"website_intelligence",costSource:"external_provider",billingUnit:"provider",quantity:1,estimatedCost:{amount:.02,currency:"USD"},actualCost:null,billableCost:{amount:.03,currency:"USD"},internalPlatformCost:{amount:.01,currency:"USD"},pricingPolicyId:"p",pricingPolicyVersion:2}));assert.throws(()=>validateCostRecord({executionId:"",investigationId:"i",workspaceId:"w",provider:null,collector:"c",costSource:"storage",billingUnit:"observation",quantity:1,estimatedCost:{amount:0,currency:"USD"},actualCost:null,billableCost:{amount:0,currency:"USD"},internalPlatformCost:{amount:0,currency:"USD"},pricingPolicyId:"p",pricingPolicyVersion:1}))});
test("workspace usage reports limits without assuming a plan",()=>{const summary=summarizeWorkspaceUsage([{metric:"investigation",quantity:3,occurredAt:"2026-07-10",cost:2},{metric:"monitoring_execution",quantity:4,occurredAt:"2026-07-11"}],[{metric:"investigation",limit:5}],{start:"2026-07-01",end:"2026-08-01",currency:"USD"});assert.equal(summary.investigationsRemaining,2);assert.equal(summary.monitoringExecutions,4);assert.equal(summary.monthlyTotals.cost,2)});
test("generic entitlements support new feature keys and limits as data",()=>{const entitlements=[{featureKey:"website_intelligence",enabled:true,limit:2,unit:"investigation"}];assert.deepEqual(evaluateFeature(entitlements,{featureKey:"website_intelligence",currentUsage:1}),{allowed:true,reason:"granted"});assert.equal(evaluateFeature(entitlements,{featureKey:"website_intelligence",currentUsage:2}).reason,"limit_reached");assert.equal(evaluateFeature(entitlements,{featureKey:"future_feature"}).reason,"missing_entitlement")});
