import test from "node:test";
import assert from "node:assert/strict";
import { CancellationManager, CollectorPipelineRunner, CollectorRegistry, CollectorRuntime, MemoryCollectorCache, MemoryExecutionRepository, MemoryMetrics, ProviderHealthTracker, snapshotFromPipeline } from "../lib/collectorRuntime/index.ts";
import { alertsFromSnapshots } from "../lib/continuousMonitoring/service.ts";
import { MemoryEvidenceRepository } from "../lib/evidenceV2/index.ts";

const subject={subjectId:"subject-1",subjectType:"domain",canonicalName:"example.com",displayName:"example.com",status:"active",workspaceId:"workspace-1",visibility:"private",mergedIntoSubjectId:null,metadata:{},createdAt:"2026-07-28T00:00:00Z",updatedAt:"2026-07-28T00:00:00Z"};
const identifier={identifierId:"id-1",subjectId:"subject-1",identifierType:"domain",normalizedValue:"example.com",displayValue:"example.com",source:"user",verificationStatus:"unverified",firstSeenAt:"2026-07-28T00:00:00Z",lastSeenAt:"2026-07-28T00:00:00Z",metadata:{}};
const context={subject,identifiers:[identifier],workspace:{workspaceId:"workspace-1"},investigation:{investigationId:"investigation-1"},pricing:{currency:"USD",category:"standard"},permissions:["investigation"],cancellationToken:new CancellationManager(),logger:{info(){},warn(){},error(){}},metrics:new MemoryMetrics(),evidenceRepository:new MemoryEvidenceRepository()};
const definition=(collectorKey,dependencies=[])=>({collectorKey,version:"1.0.0",capability:collectorKey,supportedSubjectTypes:["domain"],supportedIdentifierTypes:["domain"],requiredProviders:[],requiredEntitlements:[],pricingCategory:"standard",timeoutMs:100,retryPolicy:{maxAttempts:1,baseDelayMs:0,maxDelayMs:0},priority:1,dependencies,healthStatus:"healthy"});
const output=(category,value)=>({observations:[{observationId:crypto.randomUUID(),observationType:category,observationKey:category,value,observedAt:"2026-07-28T00:00:00Z",validFrom:"2026-07-28T00:00:00Z",metadata:{alertCategory:category}}],metrics:{},warnings:[],errors:[],executionCost:{amount:0,currency:"USD"}});
const plan={planId:"plan-1",investigationId:"investigation-1",createdAt:"2026-07-28T00:00:00Z",collectors:[{collectorKey:"dns",version:"1.0.0",priority:1,dependencies:[]},{collectorKey:"ssl",version:"1.0.0",priority:1,dependencies:[]},{collectorKey:"score",version:"1.0.0",priority:1,dependencies:["dns"]}]};

test("pipeline runs independent providers in parallel and honors dependencies",async()=>{let active=0,maxActive=0;const collector=(key,deps,category,value)=>({definition:definition(key,deps),async validate(){},async collect(){active++;maxActive=Math.max(maxActive,active);await new Promise(resolve=>setTimeout(resolve,10));active--;return output(category,value);}});const registry=new CollectorRegistry().register(collector("dns",[],"dns",["ns1"])).register(collector("ssl",[],"ssl","valid")).register(collector("score",["dns"],"trust_score",75));const runner=new CollectorPipelineRunner(new CollectorRuntime(registry,{repository:new MemoryExecutionRepository()}),{concurrency:2});const result=await runner.run({plan,context,idempotencyPrefix:"cycle-1",leaseOwner:"worker"});assert.equal(result.status,"completed");assert.equal(maxActive,2);assert.deepEqual(result.collectors.map(item=>item.status),["succeeded","succeeded","succeeded"]);assert.equal(result.auditLog.at(0).type,"pipeline_started");assert.equal(result.auditLog.at(-1).type,"pipeline_completed");});
test("cache avoids a second provider call",async()=>{let calls=0;const registry=new CollectorRegistry().register({definition:definition("dns"),async validate(){},async collect(){calls++;return output("dns",["ns1"]);}});const runner=new CollectorPipelineRunner(new CollectorRuntime(registry,{repository:new MemoryExecutionRepository()}),{cache:new MemoryCollectorCache(),cacheTtlMs:1000});const single={...plan,collectors:[plan.collectors[0]]};await runner.run({plan:single,context,idempotencyPrefix:"one",leaseOwner:"worker"});const second=await runner.run({plan:single,context,idempotencyPrefix:"two",leaseOwner:"worker"});assert.equal(calls,1);assert.equal(second.collectors[0].cached,true);});
test("provider failures update health and skip dependent providers",async()=>{const health=new ProviderHealthTracker(1);const registry=new CollectorRegistry().register({definition:definition("dns"),async validate(){},async collect(){throw new Error("offline");}}).register({definition:definition("score",["dns"]),async validate(){},async collect(){return output("trust_score",50);}});const reduced={...plan,collectors:[plan.collectors[0],plan.collectors[2]]};const result=await new CollectorPipelineRunner(new CollectorRuntime(registry,{repository:new MemoryExecutionRepository()}),{health}).run({plan:reduced,context,idempotencyPrefix:"failure",leaseOwner:"worker"});assert.equal(result.status,"failed");assert.equal(result.collectors[1].status,"skipped");assert.equal(health.get("dns").status,"disabled");});
test("pipeline observations create a real snapshot and snapshot comparison alerts",()=>{const run={pipelineRunId:"run-1",investigationId:"investigation-1",startedAt:"2026-07-28T00:00:00Z",completedAt:"2026-07-28T00:01:00Z",status:"completed",auditLog:[],collectors:[{collectorKey:"score",status:"succeeded",execution:null,cached:false,error:null,output:output("trust_score",70)},{collectorKey:"dns",status:"succeeded",execution:null,cached:false,error:null,output:output("dns",["ns2"])}]};const current=snapshotFromPipeline({run,monitoredEntityId:"monitor-1",previousTrustScore:80});const previous={id:"old",monitoredEntityId:"monitor-1",trustScore:80,capturedAt:"2026-07-27T00:00:00Z",values:{dns:["ns1"]}};const entity={id:"monitor-1",workspaceId:"workspace-1",reportId:"report-1",company:"Acme",target:"example.com",status:"active",frequency:"daily",currentTrustScore:80,lastScanAt:null,lastSuccessfulCycleAt:null,createdAt:"2026-07-27T00:00:00Z"};const alerts=alertsFromSnapshots({entity,previous,current});assert.equal(current.trustScore,70);assert.deepEqual(alerts.map(item=>item.category).sort(),["dns","trust_score"]);assert.equal(alerts.find(item=>item.category==="trust_score").severity,"high");});
