export type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
export type EvidenceProvider = { providerId:string; key:string; name:string; status:"active"|"retired"; metadata:Record<string,Json> };
export type EvidenceSource = { sourceId:string; providerId:string; key:string; name:string; kind:string; schemaVersion:number; status:"active"|"retired"; metadata:Record<string,Json> };
export type SourceInstance = { sourceInstanceId:string; sourceId:string; externalReference:string|null; acquiredAt:string; effectiveAt:string; payloadReference:string|null; payloadHash:string; collectorKey:string; collectorVersion:string; metadata:Record<string,Json> };
export type ObservationInput = { observationId:string; sourceInstanceId:string; subjectId:string; investigationId:string|null; observationType:string; key:string; value:Json; observedAt:string; validFrom:string; validTo:string|null; metadata?:Record<string,Json> };
export type Observation = ObservationInput & { recordedAt:string; status:"accepted" };
export type ConfidenceComponents = { sourceReliability:number; extractionQuality:number; corroboration:number; freshness:number; overall:number };
export type Assertion = { assertionId:string; assertionKey:string; version:number; taxonomy:string; subjectId:string; value:Json; provenance:Record<string,Json>; confidence:ConfidenceComponents; validFrom:string; validTo:string|null; recordedAt:string; supersedesAssertionId:string|null; policyVersion:string; canonicalValueHash:string };
export type EvidenceLink = { evidenceLinkId:string; assertionId:string; observationId:string; role:"supporting"|"contradicting"|"context"; createdAt:string };
export type QuarantinedEvidence = { quarantineId:string; observation:ObservationInput; stage:NormalizationStage; reasonCode:string; message:string; quarantinedAt:string };
export type CurrentAssertion = Assertion & { projectedAt:string };
export type NormalizationStage = "accept"|"validate"|"policy"|"canonicalize"|"taxonomy"|"deduplicate"|"confidence"|"append"|"project"|"outbox";
export type AssertionCandidate = Pick<Assertion,"assertionKey"|"taxonomy"|"subjectId"|"value"|"provenance"|"validFrom"|"validTo"> & { observationIds:string[]; confidence?:Partial<Omit<ConfidenceComponents,"overall">> };
export type NormalizationPolicy = { version:string; allowedObservationTypes:ReadonlySet<string>; taxonomyFor(observation:Observation):string|null; canonicalize(observation:Observation):Json; assertionKey(observation:Observation,taxonomy:string,value:Json):string; confidence(observation:Observation):Omit<ConfidenceComponents,"overall"> };
export interface EvidenceRepository { appendObservation(value:Observation):Promise<void>; appendAssertion(value:Assertion):Promise<void>; appendLinks(value:EvidenceLink[]):Promise<void>; quarantine(value:QuarantinedEvidence):Promise<void>; findAssertion(assertionKey:string,canonicalValueHash:string):Promise<Assertion|null>; latestAssertion(assertionKey:string):Promise<Assertion|null>; replaceProjection(value:CurrentAssertion):Promise<void>; appendOutbox(event:{eventId:string;type:string; aggregateId:string; payload:Record<string,Json>; occurredAt:string}):Promise<void>; }
