import { cookies } from "next/headers";
import { defaultLocale, isLocale, type Locale } from "@/lib/i18n";

export const workspaceCopy: Record<Locale, {
  productName: string; workspace: string; cases: string; alerts: string; monitoring: string; evidence: string; timeline: string; skipToContent: string;
  queueEyebrow: string; queueTitle: string; queueDescription: string; newCase: string; casesCount: string; case: string; priority: string; owner: string; due: string; alertsLabel: string; updated: string; unassigned: string; noDueDate: string;
}> = {
  en: { productName: "ShadowScore", workspace: "Workspace", cases: "Cases", alerts: "Alerts", monitoring: "Monitoring", evidence: "Evidence", timeline: "Timeline", skipToContent: "Skip to content", queueEyebrow: "Case queue", queueTitle: "Active cases", queueDescription: "Review current investigations and their next actions.", newCase: "New case", casesCount: "cases", case: "Case", priority: "Priority", owner: "Owner", due: "Due", alertsLabel: "Open alerts", updated: "Updated", unassigned: "Unassigned", noDueDate: "No due date" },
  he: { productName: "ShadowScore", workspace: "סביבת עבודה", cases: "תיקים", alerts: "התראות", monitoring: "ניטור", evidence: "ראיות", timeline: "ציר זמן", skipToContent: "מעבר לתוכן", queueEyebrow: "תור תיקים", queueTitle: "תיקים פעילים", queueDescription: "סקירת חקירות פעילות והפעולות הבאות שלהן.", newCase: "תיק חדש", casesCount: "תיקים", case: "תיק", priority: "עדיפות", owner: "אחראי", due: "תאריך יעד", alertsLabel: "התראות פתוחות", updated: "עודכן", unassigned: "ללא הקצאה", noDueDate: "ללא תאריך יעד" },
  ar: { productName: "ShadowScore", workspace: "مساحة العمل", cases: "الحالات", alerts: "التنبيهات", monitoring: "المراقبة", evidence: "الأدلة", timeline: "الخط الزمني", skipToContent: "انتقل إلى المحتوى", queueEyebrow: "قائمة الحالات", queueTitle: "الحالات النشطة", queueDescription: "راجع التحقيقات الحالية والإجراءات التالية فيها.", newCase: "حالة جديدة", casesCount: "حالات", case: "الحالة", priority: "الأولوية", owner: "المالك", due: "الموعد", alertsLabel: "تنبيهات مفتوحة", updated: "تم التحديث", unassigned: "غير معيّن", noDueDate: "لا يوجد موعد" },
  es: { productName: "ShadowScore", workspace: "Espacio de trabajo", cases: "Casos", alerts: "Alertas", monitoring: "Monitoreo", evidence: "Evidencia", timeline: "Cronología", skipToContent: "Ir al contenido", queueEyebrow: "Cola de casos", queueTitle: "Casos activos", queueDescription: "Revise las investigaciones actuales y sus siguientes acciones.", newCase: "Nuevo caso", casesCount: "casos", case: "Caso", priority: "Prioridad", owner: "Responsable", due: "Vencimiento", alertsLabel: "Alertas abiertas", updated: "Actualizado", unassigned: "Sin asignar", noDueDate: "Sin vencimiento" },
  fr: { productName: "ShadowScore", workspace: "Espace de travail", cases: "Dossiers", alerts: "Alertes", monitoring: "Surveillance", evidence: "Éléments", timeline: "Chronologie", skipToContent: "Aller au contenu", queueEyebrow: "File des dossiers", queueTitle: "Dossiers actifs", queueDescription: "Examinez les enquêtes en cours et leurs prochaines actions.", newCase: "Nouveau dossier", casesCount: "dossiers", case: "Dossier", priority: "Priorité", owner: "Responsable", due: "Échéance", alertsLabel: "Alertes ouvertes", updated: "Mis à jour", unassigned: "Non attribué", noDueDate: "Aucune échéance" },
  de: { productName: "ShadowScore", workspace: "Arbeitsbereich", cases: "Fälle", alerts: "Warnungen", monitoring: "Überwachung", evidence: "Belege", timeline: "Zeitleiste", skipToContent: "Zum Inhalt springen", queueEyebrow: "Fallwarteschlange", queueTitle: "Aktive Fälle", queueDescription: "Prüfen Sie aktuelle Untersuchungen und ihre nächsten Schritte.", newCase: "Neuer Fall", casesCount: "Fälle", case: "Fall", priority: "Priorität", owner: "Verantwortlich", due: "Fällig", alertsLabel: "Offene Warnungen", updated: "Aktualisiert", unassigned: "Nicht zugewiesen", noDueDate: "Kein Fälligkeitsdatum" },
};

export async function getWorkspaceLocale() {
  const localeCookie = (await cookies()).get("shadowscore_locale")?.value;
  const locale = isLocale(localeCookie) ? localeCookie : defaultLocale;
  return { locale, copy: workspaceCopy[locale] };
}
