import { createHash } from "node:crypto";
import { DEFAULT_TRUST_POLICY } from "./policy";
import { computeTrust } from "./scoring";
import type { TrustAlert, TrustEvent, TrustPolicy, TrustSignal, TrustSnapshot } from "./types";
const eventId=(value:string)=>`evt_${createHash("sha256").update(value).digest("hex").slice(0,20)}`;

export class TrustIntelligenceEngine{
  private signals:TrustSignal[]=[]; private snapshots:TrustSnapshot[]=[]; private alerts:TrustAlert[]=[]; private events:TrustEvent[]=[];
  private policy:TrustPolicy;
  constructor(policy:TrustPolicy=DEFAULT_TRUST_POLICY,seed:TrustSignal[]=[]){this.policy=policy;this.signals=[...seed];}
  recordSignal(signal:TrustSignal,now=signal.observedAt){if(this.signals.some(item=>item.signalId===signal.signalId))return this.current(signal.entityId);this.signals.push(structuredClone(signal));this.append(signal.entityId,"SignalRecorded",now,{signal});return this.recompute(signal.entityId,now,`New ${signal.factor.replaceAll("_"," ")} evidence`);}
  recompute(entityId:string,now:string,reason="Evidence changed"){const previous=this.current(entityId);const snapshot=computeTrust(entityId,this.signals.filter(signal=>signal.entityId===entityId),{now,policy:this.policy,previous,reason});if(previous?.snapshotId===snapshot.snapshotId)return previous;this.snapshots.push(snapshot);this.append(entityId,"TrustComputed",now,{snapshot});this.detectAlerts(previous,snapshot);return snapshot;}
  current(entityId:string){return this.snapshots.filter(item=>item.entityId===entityId).at(-1)??null;}
  history(entityId:string){return this.snapshots.filter(item=>item.entityId===entityId).map((snapshot,index,list)=>({...snapshot,delta:index?snapshot.overall-list[index-1].overall:0}));}
  drivers(entityId:string){const snapshot=this.current(entityId);if(!snapshot)return null;return Object.fromEntries(Object.entries(snapshot.scores).map(([dimension,score])=>[dimension,{positive:score.positiveEvidence,negative:score.negativeEvidence,missing:score.missingEvidence,why:score.why}]));}
  recommendation(entityId:string){const snapshot=this.current(entityId);return snapshot?{recommendation:snapshot.recommendation,overall:snapshot.overall,confidence:snapshot.confidence,policyVersion:snapshot.policyVersion}:null;}
  activeAlerts(entityId:string){return this.alerts.filter(alert=>alert.entityId===entityId);}
  eventLog(){return structuredClone(this.events);}
  replay(events:TrustEvent[]){this.signals=[];this.snapshots=[];this.alerts=[];this.events=[];for(const event of events){if(event.type==="SignalRecorded")this.signals.push(structuredClone(event.payload.signal as TrustSignal));else if(event.type==="TrustComputed")this.snapshots.push(structuredClone(event.payload.snapshot as TrustSnapshot));else this.alerts.push(structuredClone(event.payload.alert as TrustAlert));this.events.push(structuredClone(event));}return this;}
  private append(entityId:string,type:TrustEvent["type"],occurredAt:string,payload:Record<string,unknown>){this.events.push({eventId:eventId(JSON.stringify({entityId,type,occurredAt,payload,index:this.events.length})),entityId,type,occurredAt,payload,schemaVersion:1});}
  private detectAlerts(previous:TrustSnapshot|null,snapshot:TrustSnapshot){const candidates:Array<{type:TrustAlert["type"];severity:TrustAlert["severity"];explanation:string;evidenceReferences:string[]}>=[];if(previous&&snapshot.overall<=previous.overall-this.policy.alertDropThreshold)candidates.push({type:"TrustDropped",severity:"high",explanation:`Overall trust fell ${previous.overall-snapshot.overall} points.`,evidenceReferences:[]});if(previous&&snapshot.overall>=previous.overall+this.policy.alertDropThreshold)candidates.push({type:"TrustRecovered",severity:"low",explanation:`Overall trust recovered ${snapshot.overall-previous.overall} points.`,evidenceReferences:[]});for(const driver of Object.values(snapshot.scores).flatMap(score=>score.negativeEvidence)){const map:Record<string,TrustAlert["type"]>={sanctions:"ComplianceIssueDetected",regulatory_findings:"ComplianceIssueDetected",shared_infrastructure:"HighRiskRelationship",suspension_history:"MarketplaceSuspended",fraud_exposure:"FraudSignalDetected",exposed_services:"WebsiteCompromised"};if(map[driver.factor]&&driver.strength>=.7)candidates.push({type:map[driver.factor],severity:driver.strength>=.9?"critical":"high",explanation:driver.description,evidenceReferences:driver.evidenceReferences});}for(const item of candidates){const alert:{alertId:string}&Omit<TrustAlert,"alertId">={alertId:`alert_${eventId(`${snapshot.snapshotId}:${item.type}`).slice(4)}`,entityId:snapshot.entityId,createdAt:snapshot.computedAt,snapshotId:snapshot.snapshotId,...item};if(this.alerts.some(existing=>existing.alertId===alert.alertId))continue;this.alerts.push(alert);this.append(snapshot.entityId,item.type,snapshot.computedAt,{alert});}}
}
