"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import ShadowScoreLayout from "@/app/components/ShadowScoreLayout";
import { TechnicalValue, useLocale } from "@/components/LocaleProvider";
import type { EvidenceCategory, InvestigationDetail } from "@/lib/investigation";

const categoryTone: Record<EvidenceCategory, string> = { Identity: "bg-sky-400", Payments: "bg-red-400", Marketplace: "bg-amber-400", Infrastructure: "bg-violet-400" };

export function InvestigationDetailsWorkspace({ detail }: { detail: InvestigationDetail }) {
  const { locale } = useLocale();
  const [category, setCategory] = useState<EvidenceCategory | "All">("All");
  const [selectedEvidence, setSelectedEvidence] = useState(detail.evidence[0]?.id);
  const [notes, setNotes] = useState<string[]>([]);
  const [note, setNote] = useState("");
  const [decision, setDecision] = useState<"Pending review" | "Escalate" | "Restrict" | "Approve with controls">(decisionFor(detail));
  const evidence = useMemo(() => detail.evidence.filter((item) => category === "All" || item.category === category), [category, detail.evidence]);
  const selected = detail.evidence.find((item) => item.id === selectedEvidence) || evidence[0];
  const isRtl = locale === "ar" || locale === "he";

  function addNote(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!note.trim()) return;
    setNotes((items) => [note.trim(), ...items]);
    setNote("");
  }

  return <ShadowScoreLayout><main className="mx-auto max-w-[1600px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
    <nav aria-label="Breadcrumb" className="flex items-center gap-2 text-sm text-zinc-500"><Link href="/dashboard" className="hover:text-sky-200">Command center</Link><span>/</span><Link href="/investigations" className="hover:text-sky-200">Investigations</Link><span>/</span><TechnicalValue>{detail.reference}</TechnicalValue></nav>
    <header className="mt-5 border-b border-white/10 pb-6"><div className="flex flex-wrap items-start justify-between gap-5"><div><div className="flex flex-wrap items-center gap-3"><p className="ui-label">Investigation Details</p><span className="risk-status">{detail.risk} risk</span><span className="audit-status">{detail.priority} priority</span></div><h1 className="mt-2 text-3xl font-black tracking-tight text-white sm:text-4xl">{detail.investigation.target}</h1><div className="mt-3 flex flex-wrap gap-x-5 gap-y-1 text-sm text-zinc-400"><span><TechnicalValue>{detail.reference}</TechnicalValue></span><span>Assigned to {detail.assignedTo}</span><span>Updated {new Date(detail.investigation.updatedAt).toLocaleString("en-GB", { timeZone: "UTC" })} UTC</span></div></div><div className="flex flex-wrap gap-3"><a href="#audit-trail" className="min-h-11 rounded-xl border border-white/15 px-4 py-3 text-sm font-bold text-zinc-200 hover:border-sky-400/50">View audit trail</a><button onClick={() => setDecision("Escalate")} className="min-h-11 rounded-xl bg-red-600 px-4 py-3 text-sm font-bold text-white hover:bg-red-500">Escalate case</button></div></div></header>

    <section className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1.65fr)_minmax(320px,.75fr)]">
      <div className="space-y-5">
        <section aria-labelledby="executive-summary" className="audit-surface p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="ui-label">Executive summary</p><h2 id="executive-summary" className="mt-1 text-2xl font-black text-white">Decision context</h2></div><span className="text-sm font-bold text-red-300">Confidence {detail.investigation.verificationScore ?? 0}%</span></div><p className="mt-4 max-w-4xl text-sm leading-7 text-zinc-300">{detail.summary}</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><SummaryMetric label="Evidence attached" value={`${detail.evidence.length}`} detail="References attached to this case" /><SummaryMetric label="Connected entities" value={`${detail.entities.length}`} detail="Entities in this case graph" /><SummaryMetric label="Decision state" value={decision} detail={`${detail.priority} priority`}/></div></section>

        <section aria-labelledby="evidence-explorer" className="audit-surface p-5 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="ui-label">Evidence explorer</p><h2 id="evidence-explorer" className="mt-1 text-2xl font-black text-white">Records and source references</h2></div><div className="flex flex-wrap gap-2" aria-label="Filter evidence">{(["All", "Identity", "Payments", "Marketplace", "Infrastructure"] as const).map((item) => <button key={item} onClick={() => setCategory(item)} aria-pressed={category === item} className={`rounded-lg px-3 py-2 text-xs font-bold ${category === item ? "bg-sky-500 text-slate-950" : "border border-white/10 text-zinc-300 hover:bg-white/5"}`}>{item}</button>)}</div></div><div className="mt-5 grid gap-4 lg:grid-cols-[1.15fr_.85fr]"><div className="space-y-2">{evidence.length ? evidence.map((item) => <button key={item.id} onClick={() => setSelectedEvidence(item.id)} className={`w-full rounded-xl border p-4 text-start ${selected?.id === item.id ? "border-sky-400/55 bg-sky-500/10" : "border-white/10 bg-black/25 hover:bg-white/5"}`}><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-white">{item.title}</p><p className="mt-1 text-sm text-zinc-400">{item.source} · <TechnicalValue>{item.id}</TechnicalValue></p></div><span className={`mt-1 h-2.5 w-2.5 rounded-full ${categoryTone[item.category]}`} /></div></button>) : <EmptyEvidenceState />}</div>{selected && <article className="rounded-xl border border-white/10 bg-black/25 p-4"><div className="flex items-center justify-between gap-2"><span className="ui-label">Selected record</span><span className="text-xs font-bold text-emerald-300">{selected.reliability} reliability</span></div><h3 className="mt-3 font-bold text-white">{selected.title}</h3><p className="mt-2 text-sm leading-6 text-zinc-300">{selected.detail}</p><dl className="mt-5 space-y-3 text-sm"><DetailRow label="Source" value={selected.source} /><DetailRow label="Observed" value={selected.observedAt} /><DetailRow label="Attachment" value={selected.attachment} technical /></dl><button className="mt-5 text-sm font-bold text-sky-300 hover:text-sky-200">Open source reference</button></article>}</div></section>

        <section aria-labelledby="relationship-graph" className="audit-surface p-5 sm:p-6"><p className="ui-label">Entity relationship graph</p><h2 id="relationship-graph" className="mt-1 text-2xl font-black text-white">Connected entities</h2><div className="investigation-radar relative mt-5 h-[330px] overflow-hidden rounded-2xl border border-white/10 bg-black/30" dir="ltr">{detail.entities.length ? <><div className="absolute inset-0 opacity-60"><span className="absolute left-[22%] top-[35%] h-px w-[31%] rotate-[-36deg] bg-sky-300/50" /><span className="absolute left-[26%] top-[58%] h-px w-[27%] rotate-[24deg] bg-red-300/70" /><span className="absolute left-[59%] top-[56%] h-px w-[29%] rotate-[-28deg] bg-red-300/70" /></div>{detail.entities.map((entity) => <div key={entity.id} className={`absolute ${entity.position} entity-node max-w-36 rounded-xl border px-3 py-2 ${entity.risk ? "border-red-400/60 bg-red-950/75" : "border-sky-400/45 bg-slate-950/85"}`}><p className="truncate text-sm font-bold text-white">{entity.name}</p><p className="mt-0.5 text-xs text-zinc-400">{entity.kind}</p></div>)}<div className="absolute bottom-3 left-3 right-3 flex flex-wrap gap-2 text-xs text-zinc-400">{detail.relationships.map((item) => <span key={`${item.from}-${item.to}`} className={`rounded-full border px-2 py-1 ${item.risky ? "border-red-400/35 text-red-200" : "border-white/15"}`}>{item.label}</span>)}</div></> : <EmptyEvidenceState />}</div></section>

        <section aria-labelledby="investigation-timeline" className="timeline-surface"><p className="ui-label">Investigation timeline</p><h2 id="investigation-timeline" className="mt-1 text-2xl font-black text-white">How the case developed</h2>{detail.timeline.length ? <ol className="timeline-list mt-6">{detail.timeline.map((item) => <li key={`${item.time}-${item.title}`} className="timeline-item"><span className={`timeline-marker ${item.type === "risk" ? "timeline-marker-risk" : ""}`} /><div className="flex justify-between gap-4"><h3 className="font-bold text-white">{item.title}</h3><TechnicalValue><time className="text-xs text-zinc-500">{item.time} UTC</time></TechnicalValue></div><p className="mt-1 text-sm leading-6 text-zinc-400">{item.detail}</p></li>)}</ol> : <EmptyEvidenceState />}</section>
      </div>

      <aside className="space-y-5"><section className="audit-surface p-5"><p className="ui-label">Why this risk?</p><h2 className="mt-1 text-xl font-black text-white">Explainability</h2><ol className="mt-5 space-y-4">{detail.reasons.map((reason, index) => <li key={reason.title} className="border-l-2 border-red-400/70 pl-3"><div className="flex justify-between gap-2"><h3 className="font-bold text-white">{index + 1}. {reason.title}</h3><span className="text-xs font-bold text-red-300">{reason.weight}</span></div><p className="mt-1 text-sm leading-6 text-zinc-400">{reason.detail}</p></li>)}</ol></section>
        <section className="audit-surface p-5"><p className="ui-label">Confidence breakdown</p><h2 className="mt-1 text-xl font-black text-white">By evidence category</h2><div className="mt-5 space-y-4">{detail.confidence.map((item) => <div key={item.category}><div className="flex justify-between gap-3 text-sm"><span className="font-bold text-zinc-200">{item.category}</span><span className="evidence-value text-zinc-300">{item.score}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><div className={`${categoryTone[item.category]} h-full rounded-full`} style={{ width: `${item.score}%` }} /></div><p className="mt-1 text-xs leading-5 text-zinc-500">{item.evidence} records. {item.note}</p></div>)}</div></section>
        <section className="audit-surface p-5"><p className="ui-label">Decision panel</p><h2 className="mt-1 text-xl font-black text-white">Analyst recommendation</h2><p className="mt-3 text-sm leading-6 text-zinc-400">Current decision: <span className="font-bold text-white">{decision}</span></p><div className="mt-4 grid gap-2">{(["Restrict", "Escalate", "Approve with controls"] as const).map((item) => <button key={item} onClick={() => setDecision(item)} className={`min-h-11 rounded-xl border px-3 text-start text-sm font-bold ${decision === item ? "border-sky-400/55 bg-sky-500/10 text-sky-100" : "border-white/10 text-zinc-300 hover:bg-white/5"}`}>{item}</button>)}</div><p className="mt-4 text-xs leading-5 text-zinc-500">Choosing a decision records the analyst intent locally. Provider-backed decision submission will use the same case boundary.</p></section>
        <section className="audit-surface p-5"><p className="ui-label">Analyst notes</p><h2 className="mt-1 text-xl font-black text-white">Working record</h2><form onSubmit={addNote} className="mt-4"><label className="sr-only" htmlFor="analyst-note">Add analyst note</label><textarea id="analyst-note" value={note} onChange={(event) => setNote(event.target.value)} placeholder="Add a note for the investigation team" className="min-h-24 w-full rounded-xl border border-white/10 bg-black/30 p-3 text-sm text-white placeholder:text-zinc-600 focus:outline-none focus:ring-2 focus:ring-sky-300" /><button className="mt-2 min-h-10 rounded-lg bg-sky-500 px-3 text-sm font-bold text-slate-950 hover:bg-sky-400">Add note</button></form><div className="mt-5 space-y-3">{notes.map((item, index) => <article key={`${item}-${index}`} className="rounded-xl border border-white/10 bg-black/25 p-3"><p className="text-sm leading-6 text-zinc-300">{item}</p><p className="mt-2 text-xs text-zinc-500">{detail.assignedTo} · just now</p></article>)}</div></section>
      </aside>
    </section>
    <section id="audit-trail" className="audit-surface mt-5 p-5 sm:p-6"><p className="ui-label">Investigation audit trail</p><h2 className="mt-1 text-2xl font-black text-white">Recorded activity</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[640px] text-start text-sm"><thead className="border-b border-white/10 text-xs uppercase tracking-wider text-zinc-500"><tr><th className="pb-3 font-bold">Time</th><th className="pb-3 font-bold">Actor</th><th className="pb-3 font-bold">Action</th><th className="pb-3 font-bold">Detail</th></tr></thead><tbody>{detail.audit.map((item) => <tr key={`${item.time}-${item.action}`} className="border-b border-white/5 last:border-0"><td className="py-3 text-zinc-400"><TechnicalValue>{item.time}</TechnicalValue></td><td className="py-3 font-bold text-zinc-200">{item.actor}</td><td className="py-3 text-zinc-200">{item.action}</td><td className="py-3 text-zinc-400">{item.detail}</td></tr>)}</tbody></table></div></section>
    {isRtl && <p className="mt-4 text-xs text-zinc-600">Technical identifiers and source values retain their original direction.</p>}
  </main></ShadowScoreLayout>;
}

function SummaryMetric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-xl border border-white/10 bg-black/25 p-4"><p className="text-xs font-bold uppercase tracking-wider text-zinc-500">{label}</p><p className="mt-2 text-2xl font-black text-white">{value}</p><p className="mt-1 text-xs leading-5 text-zinc-500">{detail}</p></div>; }
function DetailRow({ label, value, technical = false }: { label: string; value: string; technical?: boolean }) { return <div className="flex justify-between gap-3"><dt className="text-zinc-500">{label}</dt><dd className="text-end text-zinc-300">{technical ? <TechnicalValue>{value}</TechnicalValue> : value}</dd></div>; }
function EmptyEvidenceState() { return <p className="mt-5 rounded-xl border border-dashed border-white/15 p-4 text-sm text-zinc-400">No evidence available yet.</p>; }
function decisionFor(detail: InvestigationDetail): "Pending review" | "Escalate" | "Restrict" | "Approve with controls" { return detail.risk === "Critical" ? "Restrict" : detail.risk === "High" ? "Escalate" : "Pending review"; }
