import type { Decision, DecisionConfidence, DecisionOutcome, DecisionRisk, Finding } from "./domain";
import type { WorkspaceActor } from "./actor";
export type LinkedFindingDto=Pick<Finding,"publicId"|"title"|"severity"|"confidence">;
export type DecisionDto=Omit<Decision,"caseId"|"organizationId"|"createdBy"|"updatedBy"|"findings">&{findings:LinkedFindingDto[]};
export type DecisionInput={outcome:DecisionOutcome;rationale:string;risk:DecisionRisk;confidence:DecisionConfidence;recommendedActions:string[];conditions:string[];findingIds:string[]};
export type UpdateDecisionInput=DecisionInput&{version:number};
export type DecisionWorkspaceDto={decision:DecisionDto|null;availableFindings:LinkedFindingDto[]};
export class DecisionValidationError extends Error{} export class DecisionAccessError extends Error{} export class DecisionNotFoundError extends Error{} export class DecisionConflictError extends Error{}
export interface DecisionStore{get(actor:WorkspaceActor,caseId:string):Promise<DecisionWorkspaceDto|null>;create(actor:WorkspaceActor,caseId:string,input:DecisionInput):Promise<Decision|null>;update(actor:WorkspaceActor,caseId:string,input:UpdateDecisionInput):Promise<Decision|"conflict"|null>}
const writable=new Set(["owner","manager","analyst"]),outcomes=new Set(["pass","proceed_with_verification","review","fail","no_decision"]),risks=new Set(["low","medium","high","critical"]),confidences=new Set(["low","medium","high"]),id=/^[A-Za-z0-9_-]{1,128}$/;
function validate(i:DecisionInput|UpdateDecisionInput){if(!outcomes.has(i.outcome))throw new DecisionValidationError("Outcome is invalid.");if(typeof i.rationale!=="string"||i.rationale.trim().length<10||i.rationale.trim().length>10000)throw new DecisionValidationError("Rationale must contain 10 to 10,000 characters.");if(!risks.has(i.risk))throw new DecisionValidationError("Risk level is invalid.");if(!confidences.has(i.confidence))throw new DecisionValidationError("Confidence is invalid.");if(!Array.isArray(i.findingIds)||i.findingIds.some(v=>typeof v!=="string"||!id.test(v))||(i.outcome!=="no_decision"&&i.findingIds.length<1))throw new DecisionValidationError("Select at least one finding for this outcome.");for(const [value,label] of [[i.recommendedActions,"Recommended actions"],[i.conditions,"Conditions"]] as const)if(!Array.isArray(value)||value.length>50||value.some(v=>typeof v!=="string"||!v.trim()||v.trim().length>500))throw new DecisionValidationError(`${label} are invalid.`);if("version" in i&&(!Number.isInteger(i.version)||i.version<1))throw new DecisionValidationError("Version is invalid.")}
const clean=(i:DecisionInput)=>({...i,rationale:i.rationale.trim(),findingIds:[...new Set(i.findingIds)],recommendedActions:[...new Set(i.recommendedActions.map(v=>v.trim()))],conditions:[...new Set(i.conditions.map(v=>v.trim()))]});
const dto=(d:Decision):DecisionDto=>({id:d.id,publicId:d.publicId,outcome:d.outcome,rationale:d.rationale,risk:d.risk,confidence:d.confidence,recommendedActions:d.recommendedActions,conditions:d.conditions,findings:d.findings.map(({publicId,title,severity,confidence})=>({publicId,title,severity,confidence})),version:d.version,createdAt:d.createdAt,updatedAt:d.updatedAt});
export class DecisionService{private store:DecisionStore;constructor(store:DecisionStore){this.store=store;}async get(a:WorkspaceActor,c:string){if(!id.test(c))throw new DecisionValidationError("Case identifier is invalid.");const r=await this.store.get(a,c);if(!r)throw new DecisionNotFoundError("Case not found.");return r}async create(a:WorkspaceActor,c:string,i:DecisionInput){if(!writable.has(a.role))throw new DecisionAccessError("This role cannot create decisions.");validate(i);const r=await this.store.create(a,c,clean(i));if(!r)throw new DecisionNotFoundError("Case or finding not found, or a current decision already exists.");return dto(r)}async update(a:WorkspaceActor,c:string,i:UpdateDecisionInput){if(!writable.has(a.role))throw new DecisionAccessError("This role cannot update decisions.");validate(i);const r=await this.store.update(a,c,{...clean(i),version:i.version});if(r==="conflict")throw new DecisionConflictError("Decision was changed by another request.");if(!r)throw new DecisionNotFoundError("Decision, case, or finding not found.");return dto(r)}}
