import type { WorkspaceActor } from "./actor";
import type { EvidenceItemSummary, Finding } from "./domain";
import type { FindingInput, FindingStore, FindingsWorkspaceDto, UpdateFindingInput } from "./findings";

type Request = <T>(path: string, init?: RequestInit, token?: string) => Promise<T>;
type FindingRow = { id: string; public_id: string; case_id: string; organization_id: string; title: string; narrative: string; severity: Finding["severity"]; confidence: Finding["confidence"]; tags: string[]; version: number; created_by: string; updated_by: string; created_at: string; updated_at: string; evidence_items?: Array<{ evidence_items: EvidenceRow }> };
type EvidenceRow = { id: string; label: string; source: string; captured_at: string };
const evidenceDto = (row: EvidenceRow): EvidenceItemSummary => ({ id: row.id, label: row.label, source: row.source, capturedAt: row.captured_at });
const findingDto = (row: FindingRow): Finding => ({ id: row.id, publicId: row.public_id, caseId: row.case_id, organizationId: row.organization_id, title: row.title, narrative: row.narrative, severity: row.severity, confidence: row.confidence, tags: row.tags ?? [], evidence: (row.evidence_items ?? []).map((link) => evidenceDto(link.evidence_items)), version: row.version, createdBy: row.created_by, updatedBy: row.updated_by, createdAt: row.created_at, updatedAt: row.updated_at });
const select = "id,public_id,case_id,organization_id,title,narrative,severity,confidence,tags,version,created_by,updated_by,created_at,updated_at,evidence_items:finding_evidence(evidence_items(id,label,source,captured_at))";
export class FindingRepository implements FindingStore {
  private readonly request: Request;
  private readonly token: string;
  constructor(request: Request, token: string) { this.request = request; this.token = token; }
  private async case(actor: WorkspaceActor, publicId: string) { return (await this.request<{ id: string }[]>(`/rest/v1/cases?select=id&public_id=eq.${encodeURIComponent(publicId)}&organization_id=eq.${encodeURIComponent(actor.organizationId)}&limit=1`, {}, this.token))[0]; }
  async list(actor: WorkspaceActor, publicId: string): Promise<FindingsWorkspaceDto | null> { const found = await this.case(actor, publicId); if (!found) return null; const [findings, evidence] = await Promise.all([this.request<FindingRow[]>(`/rest/v1/findings?select=${select}&case_id=eq.${found.id}&organization_id=eq.${actor.organizationId}&order=updated_at.desc`, {}, this.token), this.request<EvidenceRow[]>(`/rest/v1/evidence_items?select=id,label,source,captured_at&case_id=eq.${found.id}&organization_id=eq.${actor.organizationId}&order=captured_at.desc`, {}, this.token)]); return { findings: findings.map(findingDto), evidence: evidence.map(evidenceDto) }; }
  async create(actor: WorkspaceActor, caseId: string, input: FindingInput) { const rows = await this.request<FindingRow[]>("/rest/v1/rpc/create_finding", { method: "POST", body: JSON.stringify({ p_case_public_id: caseId, p_title: input.title, p_narrative: input.narrative, p_severity: input.severity, p_confidence: input.confidence, p_tags: input.tags, p_evidence_ids: input.evidenceIds }) }, this.token); return rows[0] ? this.hydrate(actor, rows[0].public_id, caseId) : null; }
  async update(actor: WorkspaceActor, caseId: string, findingId: string, input: UpdateFindingInput) { const rows = await this.request<FindingRow[]>("/rest/v1/rpc/update_finding", { method: "POST", body: JSON.stringify({ p_case_public_id: caseId, p_finding_public_id: findingId, p_expected_version: input.version, p_title: input.title, p_narrative: input.narrative, p_severity: input.severity, p_confidence: input.confidence, p_tags: input.tags, p_evidence_ids: input.evidenceIds }) }, this.token); if (!rows[0]) return "conflict" as const; return this.hydrate(actor, findingId, caseId); }
  async delete(_actor: WorkspaceActor, caseId: string, findingId: string, version: number) { const result = await this.request<boolean>("/rest/v1/rpc/delete_finding", { method: "POST", body: JSON.stringify({ p_case_public_id: caseId, p_finding_public_id: findingId, p_expected_version: version }) }, this.token); return result ? "deleted" as const : "conflict" as const; }
  private async hydrate(actor: WorkspaceActor, findingId: string, caseId: string) { const found = await this.case(actor, caseId); if (!found) return null; const rows = await this.request<FindingRow[]>(`/rest/v1/findings?select=${select}&case_id=eq.${found.id}&public_id=eq.${encodeURIComponent(findingId)}&limit=1`, {}, this.token); return rows[0] ? findingDto(rows[0]) : null; }
}
