import { resolve4, resolve6, resolveMx, resolveNs, resolveSoa, resolveTxt } from "node:dns/promises";
import { connect } from "node:tls";
import { registerWebsiteModule } from "./registry";
import type { WebsiteEvidence, WebsiteFinding, WebsiteScanContext, WebsiteScanModule } from "./types";
const now = () => new Date().toISOString();
const ev = (id: string, label: string, value: unknown, source: string): WebsiteEvidence => ({ id, label, value: Array.isArray(value) ? value.join(", ") || "Not published" : String(value || "Not published"), source, observedAt: now() });
const finding = (id: string, title: string, statement: string, severity: WebsiteFinding["severity"], evidence: WebsiteEvidence[], businessImpact: string, recommendation: string): WebsiteFinding => ({ id, title, statement, severity, evidenceIds: evidence.map((item) => item.id), businessImpact, recommendation });
async function within<T>(promise: Promise<T>, ms: number) { return Promise.race([promise, new Promise<T>((_, reject) => setTimeout(() => reject(new Error("Timed out")), ms))]); }
async function page(context: WebsiteScanContext, path = "/") { const fetcher = context.fetch || fetch; return within(fetcher(`https://${context.target}${path}`, { redirect: "follow", signal: AbortSignal.timeout(context.timeoutMs || 5000), headers: { "user-agent": "ShadowScore Website Intelligence/1.0" } }), context.timeoutMs || 5000); }
function simple(id: WebsiteScanModule["id"], name: string, source: string, scan: WebsiteScanModule["scan"]) { return registerWebsiteModule({ id, name, source, scan }); }

simple("domain", "Domain Intelligence", "RDAP public registry", async (c) => { const response = await within((c.fetch || fetch)(`https://rdap.org/domain/${c.target}`, { signal: AbortSignal.timeout(c.timeoutMs || 5000), headers: { "user-agent": "ShadowScore Website Intelligence/1.0" } }), c.timeoutMs || 5000); const data = await response.json() as Record<string, unknown>; const events = Array.isArray(data.events) ? data.events as Array<Record<string, string>> : []; const created = events.find((item) => item.eventAction === "registration")?.eventDate || "Not published"; const expires = events.find((item) => item.eventAction === "expiration")?.eventDate || "Not published"; const evidence = [ev("domain:created", "Registration date", created, "rdap.org"), ev("domain:expires", "Expiration date", expires, "rdap.org"), ev("domain:nameservers", "Name servers", (data.nameservers as Array<Record<string, string>> || []).map((n) => n.ldhName), "rdap.org")]; const ageDays = created === "Not published" ? NaN : (Date.now() - Date.parse(created)) / 86400000; const findings = Number.isFinite(ageDays) && ageDays < 30 ? [finding("domain:recent", "Recently registered domain", "The domain was registered within the last 30 days.", "medium", evidence.slice(0, 1), "Recently registered domains require additional verification before high-value transactions.", "Confirm the business identity and payment details through an independent channel.")] : []; return { status: "completed", confidence: 0.9, evidence, findings, executiveSummary: findings.length ? findings[0].businessImpact : "Domain registration evidence is available." }; });

simple("dns", "DNS Intelligence", "Authoritative DNS resolver", async (c) => { const queries: Array<[string, Promise<unknown>]> = [["A", resolve4(c.target)], ["AAAA", resolve6(c.target)], ["MX", resolveMx(c.target)], ["TXT", resolveTxt(c.target)], ["NS", resolveNs(c.target)], ["SOA", resolveSoa(c.target)]]; const settled = await Promise.all(queries.map(async ([label, query]) => [label, await query.catch(() => [])] as const)); const evidence = settled.map(([label, value]) => ev(`dns:${label.toLowerCase()}`, `${label} records`, value, "DNS resolver")); const txt = String(settled.find(([label]) => label === "TXT")?.[1] || ""); const email = [ev("dns:spf", "SPF record", /v=spf1/i.test(txt) ? "Published" : "Not published", "DNS TXT record"), ev("dns:dmarc", "DMARC record", await resolveTxt(`_dmarc.${c.target}`).then((v) => /v=DMARC1/i.test(String(v)) ? "Published" : "Not published").catch(() => "Not published"), "DNS TXT record")]; return { status: "completed", confidence: 0.85, evidence: [...evidence, ...email], findings: [], executiveSummary: "DNS records were collected as website evidence." }; });

simple("ssl", "SSL/TLS Intelligence", "TLS handshake", async (c) => { const cert = await within(new Promise<Record<string, unknown>>((resolveCert, reject) => { const socket = connect({ host: c.target, port: 443, servername: c.target, rejectUnauthorized: false }, () => { const certificate = socket.getPeerCertificate() as unknown as Record<string, unknown>; socket.end(); resolveCert(certificate); }); socket.once("error", reject); }), c.timeoutMs || 5000); const evidence = [ev("ssl:issuer", "Certificate issuer", (cert.issuer as Record<string, string>)?.O, "TLS handshake"), ev("ssl:expires", "Certificate expiration", cert.valid_to, "TLS handshake")]; const expired = Date.parse(String(cert.valid_to)) < Date.now(); const findings = expired ? [finding("ssl:expired", "TLS certificate has expired", "The website certificate is expired.", "high", evidence, "An expired certificate can interrupt customer access and reduce trust in the website.", "Renew the certificate and confirm the full certificate chain.")] : []; return { status: "completed", confidence: 0.9, evidence, findings, executiveSummary: expired ? findings[0].businessImpact : "A current TLS certificate was presented during the check." }; });

simple("http", "HTTP Intelligence", "Website response", async (c) => { const response = await page(c); const evidence = [ev("http:status", "HTTPS response status", response.status, "HTTPS response"), ev("http:compression", "Compression", response.headers.get("content-encoding") || "Not published", "HTTPS response"), ev("http:protocol", "HTTP protocol", response.headers.get("alt-svc")?.includes("h3") ? "HTTP/3 advertised" : "Not published", "HTTPS response")]; const findings = !response.ok ? [finding("http:status", "HTTP response needs review", `The website returned HTTP ${response.status}.`, "medium", evidence.slice(0, 1), "An unreliable website can disrupt customer journeys and reduce conversion confidence.", "Review the response status and redirect configuration.")] : []; return { status: "completed", confidence: 0.9, evidence, findings, executiveSummary: findings.length ? findings[0].businessImpact : "The website returned a successful HTTPS response." }; });

simple("security_headers", "Security Headers", "HTTPS response headers", async (c) => { const r = await page(c); const names = ["content-security-policy", "strict-transport-security", "x-frame-options", "x-content-type-options", "referrer-policy", "permissions-policy"]; const evidence = names.map((name) => ev(`headers:${name}`, name, r.headers.get(name) || "Not published", "HTTPS response headers")); const missing = evidence.filter((item) => item.value === "Not published"); const findings = missing.length ? [finding("headers:missing", "Security headers need review", `${missing.length} recommended browser security headers were not published.`, "low", missing, "Browser protections may be less consistent for customers using the website.", "Review the missing browser security headers with the website team.")] : []; return { status: "completed", confidence: 0.9, evidence, findings, executiveSummary: findings.length ? findings[0].businessImpact : "Recommended browser security headers were published." }; });
simple("technology", "Website Technology", "Website HTML", async (c) => { const html = await (await page(c)).text(); const tech = [["Shopify", /cdn\.shopify|shopify/i], ["WooCommerce", /woocommerce/i], ["Magento", /magento/i], ["WordPress", /wp-content|wordpress/i], ["Next.js", /_next\//i], ["React", /react/i], ["Vue", /vue/i], ["Angular", /ng-version/i]].filter(([, pattern]) => (pattern as RegExp).test(html)).map(([name]) => name); const evidence = [ev("technology:detected", "Detected website technologies", tech, "Website HTML")]; return { status: "completed", confidence: tech.length ? 0.75 : 0.35, evidence, findings: [], executiveSummary: tech.length ? `Website technology evidence indicates ${tech.join(", ")}.` : "No supported website technology signature was identified." }; });
simple("infrastructure", "Infrastructure", "DNS resolver", async (c) => { const [v4, v6] = await Promise.all([resolve4(c.target).catch(() => []), resolve6(c.target).catch(() => [])]); const evidence = [ev("infrastructure:ipv4", "IPv4 addresses", v4, "DNS resolver"), ev("infrastructure:ipv6", "IPv6 addresses", v6, "DNS resolver")]; return { status: "completed", confidence: v4.length || v6.length ? 0.8 : 0.2, evidence, findings: [], executiveSummary: v4.length || v6.length ? "Network address evidence was collected for the website." : "No network address was available from DNS." }; });
simple("email", "Email Security", "DNS TXT records", async (c) => { const txt = await resolveTxt(c.target).catch(() => []); const dmarc = await resolveTxt(`_dmarc.${c.target}`).catch(() => []); const evidence = [ev("email:spf", "SPF", /v=spf1/i.test(String(txt)) ? "Published" : "Not published", "DNS TXT record"), ev("email:dmarc", "DMARC", /v=DMARC1/i.test(String(dmarc)) ? "Published" : "Not published", "DNS TXT record"), ev("email:dkim", "DKIM", "Selector-specific check requires a known selector", "DNS TXT record")]; const missing = evidence.filter((item) => /SPF|DMARC/.test(item.label) && item.value === "Not published"); const findings = missing.length ? [finding("email:protection", "Email authentication needs review", "SPF or DMARC was not published for this domain.", "medium", missing, "The email domain is more vulnerable to phishing and impersonation.", "Publish and enforce SPF and DMARC, then validate DKIM for each sending service.")] : []; return { status: "completed", confidence: 0.8, evidence, findings, executiveSummary: findings.length ? findings[0].businessImpact : "Core email authentication records were published." }; });
simple("reputation", "Reputation", "Local indicator assessment", async () => { const evidence = [ev("reputation:availability", "Reputation provider", "No configured blacklist or threat-intelligence provider", "Website Intelligence configuration")]; return { status: "unavailable", confidence: 0, evidence, findings: [finding("reputation:unavailable", "Reputation evidence is unavailable", "No configured reputation provider was available during this investigation.", "info", evidence, "An evidence gap remains for known malware and phishing indicators.", "Use an approved threat-intelligence provider before relying on reputation evidence.")], executiveSummary: "Reputation provider evidence was unavailable." }; });
simple("quality", "Website Quality", "Website response", async (c) => { const r = await page(c); const html = await r.text(); const checks = [["robots.txt", await page(c, "/robots.txt").then((x) => x.ok ? "Published" : "Not published").catch(() => "Not published")], ["sitemap.xml", await page(c, "/sitemap.xml").then((x) => x.ok ? "Published" : "Not published").catch(() => "Not published")], ["Favicon", /rel=["'](?:shortcut )?icon/i.test(html) ? "Published" : "Not published"], ["Description metadata", /name=["']description/i.test(html) ? "Published" : "Not published"], ["Canonical URL", /rel=["']canonical/i.test(html) ? "Published" : "Not published"], ["OpenGraph metadata", /property=["']og:/i.test(html) ? "Published" : "Not published"], ["Structured data", /application\/ld\+json/i.test(html) ? "Published" : "Not published"]] as const; const evidence = checks.map(([label, value]) => ev(`quality:${label}`, label, value, "Website HTML")); const missing = evidence.filter((item) => item.value === "Not published"); const findings = missing.length ? [finding("quality:indicators", "Website trust indicators need review", `${missing.length} website quality indicators were not published.`, "low", missing, "Missing trust indicators can make business information harder for customers and partners to verify.", "Publish accurate website metadata and discovery files that reflect the current business identity.")] : []; return { status: "completed", confidence: 0.8, evidence, findings, executiveSummary: findings.length ? findings[0].businessImpact : "Core website quality indicators were published." }; });
simple("screenshot", "Screenshot Engine", "Website Intelligence configuration", async () => { const evidence = [ev("screenshot:availability", "Screenshot capture", "No approved browser capture provider is configured", "Website Intelligence configuration")]; return { status: "unavailable", confidence: 0, evidence, findings: [finding("screenshot:unavailable", "Screenshot evidence is unavailable", "Desktop and mobile screenshots could not be captured in this environment.", "info", evidence, "A visual evidence gap remains in the investigation record.", "Configure an approved browser capture provider to retain desktop and mobile visual evidence.")], executiveSummary: "Screenshot evidence was unavailable." }; });
