import { supabaseFetch } from "../supabase";
import type { WebsiteAlert, WebsiteAlertRepository, WebsiteAlertStatus } from "./alerts";
type AlertRow = Record<string, string | null>;
function fromRow(row: AlertRow): WebsiteAlert { return { id: row.id!, tenantId: row.user_id!, domain: row.domain!, category: row.category as WebsiteAlert["category"], severity: row.severity as WebsiteAlert["severity"], field: row.field!, previousValue: row.previous_value, currentValue: row.current_value, detectedAt: row.detected_at!, explanation: row.explanation!, recommendedAction: row.recommended_action!, evidenceSource: row.evidence_source!, currentScanId: row.current_scan_id!, previousScanId: row.previous_scan_id!, status: row.status as WebsiteAlertStatus }; }
export class SupabaseWebsiteAlertRepository implements WebsiteAlertRepository {
  constructor(private readonly userId: string, private readonly accessToken: string) {}
  async list(tenantId: string) { if (tenantId !== this.userId) throw new Error("Tenant access denied."); return (await supabaseFetch<AlertRow[]>("/rest/v1/website_alerts?select=*&order=detected_at.desc", {}, this.accessToken)).map(fromRow); }
  async appendMany(alerts: WebsiteAlert[]) { if (alerts.some((item) => item.tenantId !== this.userId)) throw new Error("Tenant access denied."); if (!alerts.length) return; await supabaseFetch("/rest/v1/website_alerts?on_conflict=id", { method: "POST", headers: { Prefer: "resolution=ignore-duplicates" }, body: JSON.stringify(alerts.map((item) => ({ id: item.id, user_id: item.tenantId, domain: item.domain, category: item.category, severity: item.severity, field: item.field, previous_value: item.previousValue, current_value: item.currentValue, detected_at: item.detectedAt, explanation: item.explanation, recommended_action: item.recommendedAction, evidence_source: item.evidenceSource, current_scan_id: item.currentScanId, previous_scan_id: item.previousScanId, status: item.status }))) }, this.accessToken); }
  async updateStatus(tenantId: string, id: string, status: WebsiteAlertStatus) { if (tenantId !== this.userId) throw new Error("Tenant access denied."); await supabaseFetch(`/rest/v1/website_alerts?id=eq.${encodeURIComponent(id)}&user_id=eq.${encodeURIComponent(this.userId)}`, { method: "PATCH", body: JSON.stringify({ status }) }, this.accessToken); }
}
