import { supabaseFetch } from "../supabase";
import { normalizeWatchlistDomain, type WebsiteMonitoringStatus, type WebsiteWatchlistEntry, type WebsiteWatchlistRepository, type WebsiteWatchlistScanMetadata } from "./watchlist";
type Row = { id:string; user_id:string; domain:string; monitoring_status:WebsiteMonitoringStatus; created_at:string; last_scanned_at:string|null; latest_risk_level:WebsiteWatchlistEntry["latestRiskLevel"]; latest_change_count:number; next_scan_at:string|null };
const map=(row:Row):WebsiteWatchlistEntry=>({id:row.id,tenantId:row.user_id,domain:row.domain,status:row.monitoring_status,createdAt:row.created_at,lastScannedAt:row.last_scanned_at,latestRiskLevel:row.latest_risk_level,latestChangeCount:row.latest_change_count,nextScanAt:row.next_scan_at});
export class SupabaseWebsiteWatchlistRepository implements WebsiteWatchlistRepository {
  constructor(private readonly userId:string,private readonly accessToken:string){}
  async list(tenantId:string){this.assert(tenantId);return(await supabaseFetch<Row[]>(`/rest/v1/website_watchlist?user_id=eq.${encodeURIComponent(this.userId)}&select=*&order=created_at.desc`,{},this.accessToken)).map(map)}
  async add(tenantId:string,input:string){this.assert(tenantId);return map(await supabaseFetch<Row[]>("/rest/v1/website_watchlist",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({user_id:this.userId,domain:normalizeWatchlistDomain(input)})},this.accessToken).then(rows=>rows[0]))}
  async setStatus(tenantId:string,id:string,status:WebsiteMonitoringStatus){this.assert(tenantId);const rows=await supabaseFetch<Row[]>(`/rest/v1/website_watchlist?id=eq.${encodeURIComponent(id)}&user_id=eq.${encodeURIComponent(this.userId)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({monitoring_status:status})},this.accessToken);if(!rows.length)throw new Error("Watchlist entry not found.")}
  async remove(tenantId:string,id:string){this.assert(tenantId);const rows=await supabaseFetch<Row[]>(`/rest/v1/website_watchlist?id=eq.${encodeURIComponent(id)}&user_id=eq.${encodeURIComponent(this.userId)}`,{method:"DELETE",headers:{Prefer:"return=representation"}},this.accessToken);if(!rows.length)throw new Error("Watchlist entry not found.")}
  async updateScanMetadata(tenantId:string,domain:string,metadata:WebsiteWatchlistScanMetadata){this.assert(tenantId);await supabaseFetch(`/rest/v1/website_watchlist?user_id=eq.${encodeURIComponent(this.userId)}&domain=eq.${encodeURIComponent(normalizeWatchlistDomain(domain))}`,{method:"PATCH",body:JSON.stringify({last_scanned_at:metadata.lastScannedAt,latest_risk_level:metadata.latestRiskLevel,latest_change_count:metadata.latestChangeCount,next_scan_at:metadata.nextScanAt})},this.accessToken)}
  private assert(tenant:string){if(tenant!==this.userId)throw new Error("Tenant access denied.")}
}
