export const locales = ["en", "he", "ar", "es", "fr", "de"] as const;
export type Locale = (typeof locales)[number];
export const defaultLocale: Locale = "en";
export const rtlLocales: readonly Locale[] = ["he", "ar"];
export const localeNames: Record<Locale, string> = { en: "English", he: "עברית", ar: "العربية", es: "Español", fr: "Français", de: "Deutsch" };
export const isLocale = (value: string | undefined): value is Locale => !!value && (locales as readonly string[]).includes(value);
export const directionForLocale = (locale: Locale) => rtlLocales.includes(locale) ? "rtl" : "ltr";

const en = {
  nav: { investigations: "Investigations", reports: "Reports", monitoring: "Monitoring", plans: "Plans", workspace: "Workspace", account: "Account", signIn: "Sign in", start: "Start investigation", menu: "Open navigation menu", language: "Language" },
  positioning: { eyebrow: "AI Business Due Diligence", headline: "AI Business Due Diligence before you trust, pay, partner, or invest.", description: "ShadowScore investigates business identity, website signals, public evidence, contradictions, and evidence gaps, then produces a source-backed executive recommendation.", disclaimer: "ShadowScore provides evidence-based decision support. It does not provide legal, financial, regulatory, credit, sanctions, or compliance approval." },
  intake: { title: "Start with one target", description: "Investigate a business, company, website, domain, supplier, manufacturer, merchant, marketplace seller, business partner, vendor, payment counterparty, or investment target.", field: "Company name, website, domain, seller profile, merchant or supplier name, email, or evidence", coverage: "Provider coverage depends on the target and available evidence. Evidence gaps and unavailable providers are shown in the report." },
  report: { brief: "Executive decision brief", recommendation: "Recommendation", decisionBasis: "Decision basis", verifiedFacts: "Verified facts", materialConcerns: "Material concerns", evidenceGaps: "Evidence gaps", businessImpact: "Business impact", actions: "Recommended actions", findings: "Business findings", assessment: "Assessment summary", status: "Investigation status", website: "Website Intelligence", provenance: "Evidence and source provenance", prepared: "Brief prepared", reviewed: "Reviewed", evidenceConfidence: "Evidence confidence", noInformation: "No additional information is recorded.", originalEvidence: "Original evidence" },
  scorecard: { "Website Intelligence": "Website Intelligence", "Security Posture": "Security Posture", "Identity Confidence": "Identity Confidence", "Infrastructure Maturity": "Infrastructure Maturity", "Business Trust": "Business Trust", "Overall ShadowScore": "Overall ShadowScore", strong: "Strong", adequate: "Adequate", limited: "Limited", needs_review: "Needs review", unavailable: "Unavailable" },
};
type Dictionary = typeof en;
type DeepPartial<T> = { [P in keyof T]?: T[P] extends object ? DeepPartial<T[P]> : T[P] };
const translations: Record<Exclude<Locale, "en">, DeepPartial<Dictionary>> = {
  he: { nav: { investigations: "חקירות", reports: "דוחות", monitoring: "ניטור", plans: "תוכניות", workspace: "סביבת עבודה", account: "חשבון", signIn: "כניסה", start: "התחלת חקירה", language: "שפה" }, positioning: { eyebrow: "בדיקת נאותות עסקית מבוססת AI", headline: "בדיקת נאותות עסקית לפני שנותנים אמון, משלמים, משתפים פעולה או משקיעים.", description: "ShadowScore בודקת זהות עסקית, אותות אתר, ראיות ציבוריות, סתירות ופערי ראיות, ומפיקה המלצה ניהולית המבוססת על מקורות." }, intake: { title: "התחילו עם יעד אחד", description: "בדקו עסק, חברה, אתר, דומיין, ספק, יצרן, סוחר, מוכר בזירה, שותף עסקי, ספק שירות, צד לתשלום או יעד השקעה." }, report: { brief: "תמצית החלטה ניהולית", recommendation: "המלצה", verifiedFacts: "עובדות מאומתות", materialConcerns: "חששות מהותיים", evidenceGaps: "פערי ראיות", actions: "פעולות מומלצות", provenance: "ראיות ומקורן", originalEvidence: "ראיה מקורית" }, scorecard: { strong: "חזק", adequate: "מספק", limited: "מוגבל", needs_review: "נדרשת בדיקה", unavailable: "לא זמין" } },
  ar: { nav: { investigations: "التحقيقات", reports: "التقارير", monitoring: "المراقبة", plans: "الخطط", workspace: "مساحة العمل", account: "الحساب", signIn: "تسجيل الدخول", start: "بدء تحقيق", language: "اللغة" }, positioning: { eyebrow: "العناية الواجبة التجارية بالذكاء الاصطناعي", headline: "العناية الواجبة التجارية قبل الثقة أو الدفع أو الشراكة أو الاستثمار.", description: "يفحص ShadowScore هوية الشركة وإشارات الموقع والأدلة العامة والتناقضات وفجوات الأدلة، ثم يقدم توصية تنفيذية مدعومة بالمصادر." }, intake: { title: "ابدأ بهدف واحد", description: "تحقق من نشاط تجاري أو شركة أو موقع أو نطاق أو مورد أو مصنع أو تاجر أو بائع سوق أو شريك أو مورد خدمة أو طرف دفع أو هدف استثماري." }, report: { brief: "موجز قرار تنفيذي", recommendation: "التوصية", verifiedFacts: "حقائق مؤكدة", materialConcerns: "مخاوف جوهرية", evidenceGaps: "فجوات الأدلة", actions: "إجراءات موصى بها", provenance: "الأدلة ومصدرها", originalEvidence: "الدليل الأصلي" }, scorecard: { strong: "قوي", adequate: "كافٍ", limited: "محدود", needs_review: "يتطلب مراجعة", unavailable: "غير متاح" } },
  es: { positioning: { eyebrow: "Debida diligencia empresarial con IA", headline: "Debida diligencia empresarial antes de confiar, pagar, asociarse o invertir.", description: "ShadowScore investiga la identidad empresarial, señales del sitio web, evidencia pública, contradicciones y vacíos de evidencia, y genera una recomendación ejecutiva respaldada por fuentes." }, intake: { title: "Empiece con un objetivo", description: "Investigue una empresa, sitio web, dominio, proveedor, fabricante, comerciante, vendedor de marketplace, socio, proveedor, contraparte de pago u objetivo de inversión." }, report: { brief: "Resumen ejecutivo de decisión", recommendation: "Recomendación", verifiedFacts: "Hechos verificados", materialConcerns: "Preocupaciones materiales", evidenceGaps: "Vacíos de evidencia", actions: "Acciones recomendadas", provenance: "Evidencia y procedencia de fuentes", originalEvidence: "Evidencia original" }, scorecard: { strong: "Sólido", adequate: "Adecuado", limited: "Limitado", needs_review: "Requiere revisión", unavailable: "No disponible" } },
  fr: { positioning: { eyebrow: "Diligence commerciale par IA", headline: "Une diligence commerciale avant de faire confiance, payer, vous associer ou investir.", description: "ShadowScore examine l'identité de l'entreprise, les signaux du site, les preuves publiques, les contradictions et les lacunes, puis produit une recommandation exécutive sourcée." }, intake: { title: "Commencez avec une cible", description: "Examinez une entreprise, un site, un domaine, un fournisseur, un fabricant, un marchand, un vendeur de place de marché, un partenaire, un prestataire, une contrepartie de paiement ou une cible d'investissement." }, report: { brief: "Synthèse décisionnelle", recommendation: "Recommandation", verifiedFacts: "Faits vérifiés", materialConcerns: "Préoccupations importantes", evidenceGaps: "Lacunes de preuve", actions: "Actions recommandées", provenance: "Preuves et provenance des sources", originalEvidence: "Preuve d'origine" }, scorecard: { strong: "Solide", adequate: "Adéquat", limited: "Limité", needs_review: "À examiner", unavailable: "Indisponible" } },
  de: { positioning: { eyebrow: "KI-gestützte Unternehmensprüfung", headline: "Unternehmensprüfung, bevor Sie vertrauen, zahlen, zusammenarbeiten oder investieren.", description: "ShadowScore untersucht Geschäftsidentität, Website-Signale, öffentliche Belege, Widersprüche und Beleglücken und erstellt eine quellenbasierte Managementempfehlung." }, intake: { title: "Mit einem Ziel beginnen", description: "Prüfen Sie ein Unternehmen, eine Website, Domain, einen Lieferanten, Hersteller, Händler, Marktplatzverkäufer, Partner, Dienstleister, Zahlungsgegenpartei oder ein Investitionsziel." }, report: { brief: "Management-Entscheidungsübersicht", recommendation: "Empfehlung", verifiedFacts: "Verifizierte Fakten", materialConcerns: "Wesentliche Bedenken", evidenceGaps: "Beleglücken", actions: "Empfohlene Maßnahmen", provenance: "Belege und Quellenherkunft", originalEvidence: "Originalbeleg" }, scorecard: { strong: "Stark", adequate: "Angemessen", limited: "Begrenzt", needs_review: "Prüfung erforderlich", unavailable: "Nicht verfügbar" } },
};
function merge<T>(base: T, patch?: DeepPartial<T>): T { if (!patch) return base; const result = { ...base } as T; for (const key of Object.keys(patch) as Array<keyof T>) { const value = patch[key]; if (value && typeof value === "object" && !Array.isArray(value)) result[key] = merge(base[key], value as DeepPartial<T[typeof key]>); else if (value !== undefined) result[key] = value as T[typeof key]; } return result; }
export function getDictionary(locale: Locale): Dictionary { return merge(en, locale === "en" ? undefined : translations[locale]); }
export function formatDateTime(value: string | undefined, locale: Locale) { if (!value) return getDictionary(locale).report.noInformation; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short" }).format(date); }
export function formatNumber(value: number, locale: Locale) { return new Intl.NumberFormat(locale).format(value); }
export function formatCurrency(value: number, currency: string, locale: Locale) { return new Intl.NumberFormat(locale, { style: "currency", currency }).format(value); }
