export const locales = ["en", "he", "ar", "es", "fr", "de"] as const;
export type Locale = (typeof locales)[number];
export const defaultLocale: Locale = "en";
export const rtlLocales: readonly Locale[] = ["he", "ar"];
export const localeNames: Record<Locale, string> = { en: "English", he: "עברית", ar: "العربية", es: "Español", fr: "Français", de: "Deutsch" };
export const isLocale = (value: string | undefined): value is Locale => !!value && (locales as readonly string[]).includes(value);
export const directionForLocale = (locale: Locale) => rtlLocales.includes(locale) ? "rtl" : "ltr";

const en = {
  nav: { investigations: "Investigations", reports: "Reports", monitoring: "Monitoring", plans: "Plans", workspace: "Workspace", account: "Account", signIn: "Sign in", start: "Start investigation", menu: "Open navigation menu", language: "Language" },
  positioning: { eyebrow: "AI Business Due Diligence", headline: "AI Business Due Diligence before you trust, pay, partner, or invest.", description: "ShadowScore investigates business identity, website signals, public evidence, contradictions, and evidence gaps, then produces a source-backed executive recommendation.", disclaimer: "ShadowScore provides evidence-based decision support. It does not provide legal, financial, regulatory, credit, sanctions, or compliance approval." },
  intake: { title: "Start with one target", description: "Investigate a business, company, website, domain, supplier, manufacturer, merchant, marketplace seller, business partner, vendor, payment counterparty, or investment target.", field: "Company name, website, domain, seller profile, merchant or supplier name, email, or evidence", coverage: "Provider coverage depends on the target and available evidence. Evidence gaps and unavailable providers are shown in the report." },
  report: { brief: "Executive decision brief", recommendation: "Recommendation", decisionBasis: "Decision basis", verifiedFacts: "Verified facts", materialConcerns: "Material concerns", evidenceGaps: "Evidence gaps", businessImpact: "Business impact", actions: "Recommended actions", findings: "Business findings", assessment: "Assessment summary", status: "Investigation status", website: "Website Intelligence", provenance: "Evidence and source provenance", prepared: "Brief prepared", reviewed: "Reviewed", evidenceConfidence: "Evidence confidence", noInformation: "No additional information is recorded.", originalEvidence: "Original evidence" },
  scorecard: { "Website Intelligence": "Website Intelligence", "Security Posture": "Security Posture", "Identity Confidence": "Identity Confidence", "Infrastructure Maturity": "Infrastructure Maturity", "Business Trust": "Business Trust", "Overall ShadowScore": "Overall ShadowScore", strong: "Strong", adequate: "Adequate", limited: "Limited", needs_review: "Needs review", unavailable: "Unavailable" },
};
type Dictionary = typeof en;

const translations: Record<Exclude<Locale, "en">, Dictionary> = {
  he: {
    nav: { investigations: "חקירות", reports: "דוחות", monitoring: "ניטור", plans: "תוכניות", workspace: "סביבת עבודה", account: "חשבון", signIn: "כניסה", start: "התחלת חקירה", menu: "פתיחת תפריט הניווט", language: "שפה" },
    positioning: { eyebrow: "בדיקת נאותות עסקית מבוססת AI", headline: "בדיקת נאותות עסקית לפני שנותנים אמון, משלמים, משתפים פעולה או משקיעים.", description: "ShadowScore בודקת זהות עסקית, אותות אתר, ראיות ציבוריות, סתירות ופערי ראיות, ומפיקה המלצה ניהולית המבוססת על מקורות.", disclaimer: "ShadowScore מספקת תמיכה בקבלת החלטות המבוססת על ראיות. היא אינה מספקת אישור משפטי, פיננסי, רגולטורי, אשראי, סנקציות או ציות." },
    intake: { title: "התחילו עם יעד אחד", description: "בדקו עסק, חברה, אתר, דומיין, ספק, יצרן, סוחר, מוכר בזירה, שותף עסקי, ספק שירות, צד לתשלום או יעד השקעה.", field: "שם חברה, אתר, דומיין, פרופיל מוכר, שם סוחר או ספק, דוא״ל או ראיה", coverage: "כיסוי הספקים תלוי ביעד ובראיות הזמינות. פערי ראיות וספקים שאינם זמינים מוצגים בדוח." },
    report: { brief: "תמצית החלטה ניהולית", recommendation: "המלצה", decisionBasis: "בסיס ההחלטה", verifiedFacts: "עובדות מאומתות", materialConcerns: "חששות מהותיים", evidenceGaps: "פערי ראיות", businessImpact: "השפעה עסקית", actions: "פעולות מומלצות", findings: "ממצאים עסקיים", assessment: "סיכום ההערכה", status: "סטטוס החקירה", website: "מודיעין אתר", provenance: "ראיות ומקורן", prepared: "מועד הכנת התמצית", reviewed: "נבדק", evidenceConfidence: "רמת אמון בראיות", noInformation: "לא נרשם מידע נוסף.", originalEvidence: "ראיה מקורית" },
    scorecard: { "Website Intelligence": "מודיעין אתר", "Security Posture": "עמדת אבטחה", "Identity Confidence": "אמון בזהות", "Infrastructure Maturity": "בשלות תשתית", "Business Trust": "אמון עסקי", "Overall ShadowScore": "ShadowScore כולל", strong: "חזק", adequate: "מספק", limited: "מוגבל", needs_review: "נדרשת בדיקה", unavailable: "לא זמין" },
  },
  ar: {
    nav: { investigations: "التحقيقات", reports: "التقارير", monitoring: "المراقبة", plans: "الخطط", workspace: "مساحة العمل", account: "الحساب", signIn: "تسجيل الدخول", start: "بدء تحقيق", menu: "فتح قائمة التنقل", language: "اللغة" },
    positioning: { eyebrow: "العناية الواجبة التجارية بالذكاء الاصطناعي", headline: "العناية الواجبة التجارية قبل الثقة أو الدفع أو الشراكة أو الاستثمار.", description: "يفحص ShadowScore هوية الشركة وإشارات الموقع والأدلة العامة والتناقضات وفجوات الأدلة، ثم يقدم توصية تنفيذية مدعومة بالمصادر.", disclaimer: "يوفر ShadowScore دعماً لاتخاذ القرار يستند إلى الأدلة. ولا يقدم موافقة قانونية أو مالية أو تنظيمية أو ائتمانية أو متعلقة بالعقوبات أو الامتثال." },
    intake: { title: "ابدأ بهدف واحد", description: "تحقق من نشاط تجاري أو شركة أو موقع أو نطاق أو مورد أو مصنع أو تاجر أو بائع سوق أو شريك أو مورد خدمة أو طرف دفع أو هدف استثماري.", field: "اسم الشركة أو الموقع أو النطاق أو ملف البائع أو اسم التاجر أو المورد أو البريد الإلكتروني أو الدليل", coverage: "تعتمد تغطية المزوّدين على الهدف والأدلة المتاحة. تظهر فجوات الأدلة والمزوّدون غير المتاحين في التقرير." },
    report: { brief: "موجز قرار تنفيذي", recommendation: "التوصية", decisionBasis: "أساس القرار", verifiedFacts: "حقائق مؤكدة", materialConcerns: "مخاوف جوهرية", evidenceGaps: "فجوات الأدلة", businessImpact: "الأثر التجاري", actions: "إجراءات موصى بها", findings: "نتائج تجارية", assessment: "ملخص التقييم", status: "حالة التحقيق", website: "معلومات الموقع", provenance: "الأدلة ومصدرها", prepared: "تم إعداد الموجز", reviewed: "تمت المراجعة", evidenceConfidence: "موثوقية الأدلة", noInformation: "لا توجد معلومات إضافية مسجلة.", originalEvidence: "الدليل الأصلي" },
    scorecard: { "Website Intelligence": "معلومات الموقع", "Security Posture": "الوضع الأمني", "Identity Confidence": "موثوقية الهوية", "Infrastructure Maturity": "نضج البنية التحتية", "Business Trust": "الثقة التجارية", "Overall ShadowScore": "نتيجة ShadowScore الإجمالية", strong: "قوي", adequate: "كافٍ", limited: "محدود", needs_review: "يتطلب مراجعة", unavailable: "غير متاح" },
  },
  es: {
    nav: { investigations: "Investigaciones", reports: "Informes", monitoring: "Monitoreo", plans: "Planes", workspace: "Espacio de trabajo", account: "Cuenta", signIn: "Iniciar sesión", start: "Iniciar investigación", menu: "Abrir menú de navegación", language: "Idioma" },
    positioning: { eyebrow: "Debida diligencia empresarial con IA", headline: "Debida diligencia empresarial antes de confiar, pagar, asociarse o invertir.", description: "ShadowScore investiga la identidad empresarial, señales del sitio web, evidencia pública, contradicciones y vacíos de evidencia, y genera una recomendación ejecutiva respaldada por fuentes.", disclaimer: "ShadowScore ofrece apoyo para decisiones basado en evidencia. No proporciona aprobación legal, financiera, regulatoria, crediticia, de sanciones ni de cumplimiento." },
    intake: { title: "Empiece con un objetivo", description: "Investigue una empresa, sitio web, dominio, proveedor, fabricante, comerciante, vendedor de marketplace, socio, proveedor, contraparte de pago u objetivo de inversión.", field: "Nombre de empresa, sitio web, dominio, perfil de vendedor, nombre de comerciante o proveedor, correo electrónico o evidencia", coverage: "La cobertura de proveedores depende del objetivo y de la evidencia disponible. Los vacíos de evidencia y los proveedores no disponibles aparecen en el informe." },
    report: { brief: "Resumen ejecutivo de decisión", recommendation: "Recomendación", decisionBasis: "Base de la decisión", verifiedFacts: "Hechos verificados", materialConcerns: "Preocupaciones materiales", evidenceGaps: "Vacíos de evidencia", businessImpact: "Impacto empresarial", actions: "Acciones recomendadas", findings: "Hallazgos empresariales", assessment: "Resumen de la evaluación", status: "Estado de la investigación", website: "Inteligencia del sitio web", provenance: "Evidencia y procedencia de fuentes", prepared: "Resumen preparado", reviewed: "Revisado", evidenceConfidence: "Confianza en la evidencia", noInformation: "No hay información adicional registrada.", originalEvidence: "Evidencia original" },
    scorecard: { "Website Intelligence": "Inteligencia del sitio web", "Security Posture": "Postura de seguridad", "Identity Confidence": "Confianza en la identidad", "Infrastructure Maturity": "Madurez de la infraestructura", "Business Trust": "Confianza empresarial", "Overall ShadowScore": "ShadowScore general", strong: "Sólido", adequate: "Adecuado", limited: "Limitado", needs_review: "Requiere revisión", unavailable: "No disponible" },
  },
  fr: {
    nav: { investigations: "Enquêtes", reports: "Rapports", monitoring: "Surveillance", plans: "Forfaits", workspace: "Espace de travail", account: "Compte", signIn: "Se connecter", start: "Démarrer une enquête", menu: "Ouvrir le menu de navigation", language: "Langue" },
    positioning: { eyebrow: "Diligence commerciale par IA", headline: "Une diligence commerciale avant de faire confiance, payer, vous associer ou investir.", description: "ShadowScore examine l'identité de l'entreprise, les signaux du site, les preuves publiques, les contradictions et les lacunes, puis produit une recommandation exécutive sourcée.", disclaimer: "ShadowScore fournit une aide à la décision fondée sur des preuves. Il ne fournit pas d'approbation juridique, financière, réglementaire, de crédit, de sanctions ou de conformité." },
    intake: { title: "Commencez avec une cible", description: "Examinez une entreprise, un site, un domaine, un fournisseur, un fabricant, un marchand, un vendeur de place de marché, un partenaire, un prestataire, une contrepartie de paiement ou une cible d'investissement.", field: "Nom de l'entreprise, site, domaine, profil vendeur, nom du marchand ou du fournisseur, e-mail ou preuve", coverage: "La couverture des fournisseurs dépend de la cible et des preuves disponibles. Les lacunes de preuve et les fournisseurs indisponibles apparaissent dans le rapport." },
    report: { brief: "Synthèse décisionnelle", recommendation: "Recommandation", decisionBasis: "Base de la décision", verifiedFacts: "Faits vérifiés", materialConcerns: "Préoccupations importantes", evidenceGaps: "Lacunes de preuve", businessImpact: "Impact commercial", actions: "Actions recommandées", findings: "Constats commerciaux", assessment: "Synthèse de l'évaluation", status: "Statut de l'enquête", website: "Renseignement du site web", provenance: "Preuves et provenance des sources", prepared: "Synthèse préparée", reviewed: "Révisé", evidenceConfidence: "Fiabilité des preuves", noInformation: "Aucune information supplémentaire n'est enregistrée.", originalEvidence: "Preuve d'origine" },
    scorecard: { "Website Intelligence": "Renseignement du site web", "Security Posture": "Posture de sécurité", "Identity Confidence": "Confiance dans l'identité", "Infrastructure Maturity": "Maturité de l'infrastructure", "Business Trust": "Confiance commerciale", "Overall ShadowScore": "ShadowScore global", strong: "Solide", adequate: "Adéquat", limited: "Limité", needs_review: "À examiner", unavailable: "Indisponible" },
  },
  de: {
    nav: { investigations: "Untersuchungen", reports: "Berichte", monitoring: "Überwachung", plans: "Tarife", workspace: "Arbeitsbereich", account: "Konto", signIn: "Anmelden", start: "Untersuchung starten", menu: "Navigationsmenü öffnen", language: "Sprache" },
    positioning: { eyebrow: "KI-gestützte Unternehmensprüfung", headline: "Unternehmensprüfung, bevor Sie vertrauen, zahlen, zusammenarbeiten oder investieren.", description: "ShadowScore untersucht Geschäftsidentität, Website-Signale, öffentliche Belege, Widersprüche und Beleglücken und erstellt eine quellenbasierte Managementempfehlung.", disclaimer: "ShadowScore unterstützt evidenzbasierte Entscheidungen. Es bietet keine rechtliche, finanzielle, regulatorische, kreditbezogene, sanktionsbezogene oder Compliance-Freigabe." },
    intake: { title: "Mit einem Ziel beginnen", description: "Prüfen Sie ein Unternehmen, eine Website, Domain, einen Lieferanten, Hersteller, Händler, Marktplatzverkäufer, Partner, Dienstleister, Zahlungsgegenpartei oder ein Investitionsziel.", field: "Firmenname, Website, Domain, Verkäuferprofil, Händler- oder Lieferantenname, E-Mail oder Beleg", coverage: "Die Anbieterabdeckung hängt vom Ziel und den verfügbaren Belegen ab. Beleglücken und nicht verfügbare Anbieter werden im Bericht angezeigt." },
    report: { brief: "Management-Entscheidungsübersicht", recommendation: "Empfehlung", decisionBasis: "Entscheidungsgrundlage", verifiedFacts: "Verifizierte Fakten", materialConcerns: "Wesentliche Bedenken", evidenceGaps: "Beleglücken", businessImpact: "Geschäftliche Auswirkungen", actions: "Empfohlene Maßnahmen", findings: "Geschäftliche Erkenntnisse", assessment: "Zusammenfassung der Bewertung", status: "Status der Untersuchung", website: "Website-Intelligence", provenance: "Belege und Quellenherkunft", prepared: "Übersicht erstellt", reviewed: "Geprüft", evidenceConfidence: "Vertrauen in die Belege", noInformation: "Es sind keine weiteren Informationen erfasst.", originalEvidence: "Originalbeleg" },
    scorecard: { "Website Intelligence": "Website-Intelligence", "Security Posture": "Sicherheitsstatus", "Identity Confidence": "Identitätsvertrauen", "Infrastructure Maturity": "Infrastrukturreife", "Business Trust": "Geschäftsvertrauen", "Overall ShadowScore": "Gesamter ShadowScore", strong: "Stark", adequate: "Angemessen", limited: "Begrenzt", needs_review: "Prüfung erforderlich", unavailable: "Nicht verfügbar" },
  },
};

export function getDictionary(locale: Locale): Dictionary { return locale === "en" ? en : translations[locale]; }
export function formatDateTime(value: string | undefined, locale: Locale) { if (!value) return getDictionary(locale).report.noInformation; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short" }).format(date); }
export function formatNumber(value: number, locale: Locale) { return new Intl.NumberFormat(locale).format(value); }
export function formatCurrency(value: number, currency: string, locale: Locale) { return new Intl.NumberFormat(locale, { style: "currency", currency }).format(value); }
