import type { Metadata } from "next";
import Link from "next/link";
import { JsonLd } from "../components/MarketingPage";
import { pageMetadata } from "../lib/seo";

export const metadata: Metadata = pageMetadata({ title: "Business Due Diligence Methodology | ShadowScore", description: "Learn how ShadowScore identifies targets, collects source-backed evidence, handles contradictions, and communicates confidence and limitations.", path: "/methodology" });
const workflow = ["Business", "Identity", "Evidence", "Analysis", "Decision", "Report"];
const steps = ["Target identification", "Identity resolution", "Source collection", "Evidence provenance", "Cross-source comparison", "Contradiction handling", "Missing evidence", "Risk assessment", "Confidence assessment", "Human review where applicable", "Limitations"];

export default function Methodology() {
  return <main className="min-h-screen bg-[#07111f] px-6 py-20 text-slate-100"><JsonLd data={{ "@context": "https://schema.org", "@type": "Article", headline: "ShadowScore methodology", about: "Business due diligence methodology" }} /><article className="mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-sky-300">Methodology</p><h1 className="mt-5 max-w-4xl text-5xl font-black">Source-backed business due diligence methodology</h1><p className="mt-6 max-w-3xl text-xl leading-8 text-slate-300">ShadowScore turns available source records into a clear review of identity, evidence, uncertainty, and recommended next actions.</p>
    <section className="mt-12 rounded-3xl border border-sky-300/20 bg-sky-300/[.04] p-6 sm:p-8" aria-labelledby="workflow-title"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-sky-300">Investigation flow</p><h2 id="workflow-title" className="mt-2 text-2xl font-bold">From business input to a decision-ready report</h2></div><p className="max-w-md text-sm leading-6 text-slate-400">Each stage preserves the context needed for the next one.</p></div><ol className="mt-8 grid gap-2 sm:grid-cols-6" aria-label="Business investigation workflow">{workflow.map((stage, index) => <li key={stage} className="relative flex items-center gap-3 sm:block"><div className="flex min-h-20 flex-1 items-center justify-center rounded-2xl border border-white/10 bg-[#0a1728] px-3 text-center font-bold">{stage}</div>{index < workflow.length - 1 && <span aria-hidden="true" className="text-xl text-sky-300 sm:absolute sm:-right-2.5 sm:top-7 sm:z-10">↓</span>}</li>)}</ol></section>
    <ol className="mt-14 grid gap-4 sm:grid-cols-2">{steps.map((step, i) => <li key={step} className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><span className="text-sky-300">{String(i + 1).padStart(2, "0")}</span><h2 className="mt-3 text-xl font-bold">{step}</h2></li>)}</ol><section className="mt-14 space-y-4 rounded-3xl border border-white/10 p-7 text-slate-300"><h2 className="text-2xl font-bold text-white">Limits and evidence integrity</h2><p>Missing information is not automatically negative. Confidence and risk are independent. Public information can be incomplete or outdated, and findings depend on source availability.</p><p>ShadowScore does not guarantee third-party outcomes, payment recovery, account approval, investment performance, or legal outcomes.</p></section><Link href="/intake" className="mt-10 inline-flex rounded-full bg-sky-400 px-6 py-3 font-bold text-slate-950">Start due diligence</Link></article></main>;
}
