import { previousSuccessful, readHistory, readJson, RELEASE_BASELINE_PATH, trend } from "./qualityStore.mjs";

function byTarget(run) { return new Map((run?.targets || []).map((t)=>[t.target,t])); }
function metricDelta(current, previous, key) { const c = current?.summary?.[key]; const p = previous?.summary?.[key]; return typeof c === "number" && typeof p === "number" ? Math.round((c-p)*10)/10 : null; }
function addAlert(alerts, target, type, classification, detail) { alerts.push({ target, type, classification, ...detail }); }
export function compareQuality(latest, history = readHistory()) {
  const previous = previousSuccessful(history, latest.run.id); const release = readJson(RELEASE_BASELINE_PATH); const alerts = [];
  if (previous) {
    if (metricDelta(latest, previous, "passRate") < 0) addAlert(alerts, "ALL", "PASS rate decreased", "product_regression", { previous: previous.summary.passRate, current: latest.summary.passRate, exactChange: `${previous.summary.passRate}% → ${latest.summary.passRate}%` });
    if (metricDelta(latest, previous, "averageEvidenceCoverage") < -10) addAlert(alerts, "ALL", "Evidence coverage dropped materially", "product_regression", { previous: previous.summary.averageEvidenceCoverage, current: latest.summary.averageEvidenceCoverage, exactChange: `${previous.summary.averageEvidenceCoverage}% → ${latest.summary.averageEvidenceCoverage}%` });
    if (metricDelta(latest, previous, "providerCompletionRate") < -5) addAlert(alerts, "ALL", "Provider reliability dropped", "product_regression", { previous: previous.summary.providerCompletionRate, current: latest.summary.providerCompletionRate, exactChange: `${previous.summary.providerCompletionRate}% → ${latest.summary.providerCompletionRate}%` });
    const prevTargets = byTarget(previous);
    for (const cur of latest.targets) { const prev = prevTargets.get(cur.target); if (!prev) continue;
      if (prev.organizationResolved && prev.currentResult !== "Unknown" && cur.currentResult === "Unknown") addAlert(alerts, cur.target, "Previously resolved identity became Unknown", "product_regression", { previous: prev.currentResult, current: cur.currentResult, exactChange: `${prev.currentResult} → Unknown` });
      if (cur.unsupportedStatements.length > prev.unsupportedStatements.length) addAlert(alerts, cur.target, "Unsupported identity appeared", "product_regression", { previous: prev.unsupportedStatements, current: cur.unsupportedStatements, exactChange: "unsupported statement count increased" });
      if (cur.identityContradictions.length > prev.identityContradictions.length) addAlert(alerts, cur.target, "New contradiction appeared", "product_regression", { previous: prev.identityContradictions, current: cur.identityContradictions, exactChange: "identity contradiction count increased" });
      if (prev.decision !== cur.decision && prev.evidenceCoverage === cur.evidenceCoverage) addAlert(alerts, cur.target, "Decision changed without meaningful evidence change", "product_regression", { previous: prev.decision, current: cur.decision, exactChange: `${prev.decision} → ${cur.decision}` });
      if (cur.environmentFailures.length > prev.environmentFailures.length) addAlert(alerts, cur.target, "Temporary public-source outage", "environment_failure", { previous: prev.environmentFailures, current: cur.environmentFailures, exactChange: "environment failure count increased" });
    }
  }
  if (latest.summary.productionPipelineFailed) addAlert(alerts, "ALL", "Production pipeline failed", "product_regression", { previous: false, current: true, exactChange: "latest validation has REVIEW or CONFIRMED RISK targets" });
  const meaningful = alerts.filter((a)=>a.classification === "product_regression");
  latest.summary.regressionCount = meaningful.length;
  latest.regressions = meaningful;
  latest.environmentAlerts = alerts.filter((a)=>a.classification === "environment_failure");
  latest.manualReviewQueue = meaningful.map((a)=>({ target: a.target, previousResult: a.previous, currentResult: a.current, exactChange: a.exactChange, suspectedCause: a.type, relevantEvidenceOrDiagnostics: latest.targets.find((t)=>t.target===a.target)?.diagnostics || latest.summary, recommendedNextInvestigationStep: a.target === "ALL" ? "Inspect aggregate validation artifacts and compare target-level diagnostics." : "Re-run target validation, inspect provider diagnostics, and verify authoritative evidence availability." }));
  return { latest, comparisons: { previousSuccessfulRun: previous ? { runId: previous.run.id, passRateDelta: metricDelta(latest, previous, "passRate"), evidenceCoverageDelta: metricDelta(latest, previous, "averageEvidenceCoverage"), providerCompletionDelta: metricDelta(latest, previous, "providerCompletionRate") } : null, lastMergedRelease: release ? { runId: release.run.id, passRateDelta: metricDelta(latest, release, "passRate"), evidenceCoverageDelta: metricDelta(latest, release, "averageEvidenceCoverage") } : null, sevenDayTrend: trend(history, 7, latest), thirtyDayTrend: trend(history, 30, latest) } };
}
export function dashboardModel(compared) { const l = compared.latest; return { generatedAt: new Date().toISOString(), metrics: { currentPassRate: { value: l.summary.passRate, label: "derived", unit: "percent" }, previousPassRate: { value: compared.comparisons.previousSuccessfulRun ? l.summary.passRate - compared.comparisons.previousSuccessfulRun.passRateDelta : null, label: "derived", unit: "percent" }, organizationResolutionRate: { value: l.summary.organizationResolutionSuccessRate, label: "measured", unit: "percent" }, averageEvidenceCoverage: { value: l.summary.averageEvidenceCoverage, label: "derived", unit: "percent" }, httpSuccessRate: { value: l.summary.httpAcquisitionSuccessRate, label: "measured", unit: "percent", note: "No HTTP acquisition metrics are emitted by validate:live-truth authoritative provider results." }, providerReliability: { value: l.summary.providerCompletionRate, label: "measured", unit: "percent" }, regressionCount: { value: l.summary.regressionCount, label: "derived" }, unresolvedIdentityCount: { value: l.targets.filter((t)=>t.currentResult === "Unknown").length, label: "measured" }, unsupportedStatementCount: { value: l.summary.unsupportedStatementCount, label: "measured" }, targetsRequiringHumanReview: { value: l.manualReviewQueue.length, label: "derived" } }, comparisons: compared.comparisons, manualReviewQueue: l.manualReviewQueue, environmentAlerts: l.environmentAlerts, targets: l.targets } }
