import "server-only";
import { createHash } from "node:crypto";
import type { CasePriority, CaseStatus } from "../domain";
import { WorkspaceHttpError, type WorkspaceActor } from "./auth";
import { WorkspaceRepository } from "./repository";
const repo=new WorkspaceRepository(); const priorities=new Set<CasePriority>(["low","normal","high","critical"]); const statuses=new Set<CaseStatus>(["draft","active","awaiting_input","under_review","monitoring","closed","archived"]);
function text(v:unknown,max:number){return typeof v==="string"&&v.trim()&&v.trim().length<=max?v.trim():null;}
function key(v:string|null){if(!v||v.length>255)throw new WorkspaceHttpError(400,"idempotency_key_required");return v;}
function hash(v:unknown){return createHash("sha256").update(JSON.stringify(v)).digest("hex");}
export async function listCases(actor:WorkspaceActor, query:URLSearchParams){const limit=Math.min(Math.max(Number(query.get("limit"))||25,1),100); try{return await repo.listCases(actor,{status:query.get("status") as CaseStatus||undefined,owner:query.get("owner")||undefined,priority:query.get("priority") as CasePriority||undefined,query:query.get("query")||undefined,cursor:query.get("cursor")||undefined,limit});}catch{throw new WorkspaceHttpError(400,"invalid_cursor");}}
export async function getCase(actor:WorkspaceActor,id:string){const c=await repo.getCase(actor,id);if(!c)throw new WorkspaceHttpError(404,"case_not_found");return serialize(c);}
export async function createCase(actor:WorkspaceActor,body:Record<string, unknown>,idempotencyKey:string|null){const title=text(body.title,240), investigationId=text(body.investigationId,240);if(!title||!investigationId||!priorities.has(body.priority))throw new WorkspaceHttpError(400,"validation_error");const input={investigation_id:investigationId,title,priority:body.priority,owner_id:typeof body.ownerId==='string'?body.ownerId:null,due_at:typeof body.dueAt==='string'?body.dueAt:null,idempotency_key:key(idempotencyKey),request_hash:hash(body)};return repo.createCase(actor,input);}
export async function updateCase(actor:WorkspaceActor,id:string,body:Record<string, unknown>,idempotencyKey:string|null){if(!Number.isInteger(body.version)||body.version<1)throw new WorkspaceHttpError(400,"validation_error");if(body.priority&&!priorities.has(body.priority)||body.status&&!statuses.has(body.status))throw new WorkspaceHttpError(400,"validation_error");try{return await repo.updateCase(actor,id,{public_id:id,version:body.version,title:body.title===undefined?null:text(body.title,240),status:body.status??null,priority:body.priority??null,owner_id:body.ownerId??null,due_at:body.dueAt??null,idempotency_key:key(idempotencyKey),request_hash:hash(body)});}catch(e){if(String(e).includes("case_version_conflict"))throw new WorkspaceHttpError(409,"case_version_conflict");throw e;}}
function serialize(c:{ public_id:string; title:string; investigation_id:string; status:CaseStatus; priority:CasePriority; owner_id:string|null; due_at:string|null; updated_at:string; version:number }){return {id:c.public_id,title:c.title,target:c.investigation_id,status:c.status,priority:c.priority,ownerId:c.owner_id,dueAt:c.due_at,updatedAt:c.updated_at,version:c.version};}
