"use client";

import ShadowScoreLayout from "../../components/ShadowScoreLayout";
import { useLocale } from "../../components/LocaleProvider";
import { getUserPageCopy } from "../../lib/i18n";

export default function ExampleReport() {
  const { locale } = useLocale();
  const page = getUserPageCopy(locale).example;
  const sections = [page.summary, page.verified, page.contradictions, page.unknowns, page.impact, page.next, page.appendix];
  return <ShadowScoreLayout><main className="bg-zinc-100 px-4 py-10 text-zinc-900 sm:px-6 lg:py-16"><article className="mx-auto max-w-5xl rounded-[2.5rem] border border-zinc-200 bg-[#fbfaf7] px-6 py-10 shadow-[0_30px_120px_rgba(0,0,0,0.32)] sm:px-10 lg:px-16 lg:py-16"><header className="grid gap-10 border-b border-zinc-200 pb-12 lg:grid-cols-[1fr_17rem]"><div><div className="text-xs font-bold uppercase tracking-[0.32em] text-red-700">{page.eyebrow}</div><h1 className="mt-5 max-w-3xl text-5xl font-black tracking-[-0.04em] text-zinc-950 lg:text-7xl">{page.title}</h1><p className="mt-6 max-w-3xl text-xl leading-9 text-zinc-600">{page.description}</p></div><aside className="rounded-3xl border border-zinc-200 bg-white p-6"><div className="text-xs font-bold uppercase tracking-[0.22em] text-zinc-500">{page.reportId}</div><div className="mt-3 text-2xl font-black text-zinc-950">SS-2026-DEMO-001</div><dl className="mt-8 space-y-5 text-sm"><div><dt className="text-zinc-500">{page.subject}</dt><dd className="mt-1 font-bold text-zinc-950">{page.subjectValue}</dd></div><div><dt className="text-zinc-500">{page.audience}</dt><dd className="mt-1 font-bold text-zinc-950">{page.audienceValue}</dd></div><div><dt className="text-zinc-500">{page.status}</dt><dd className="mt-1 font-bold text-red-700">{page.statusValue}</dd></div></dl></aside></header><section className="mt-12 rounded-[2rem] bg-zinc-950 p-8 text-white"><div className="text-sm font-bold uppercase tracking-[0.25em] text-red-200">{page.outcome}</div><h2 className="mt-5 text-3xl font-black">{page.recommendation}</h2><p className="mt-5 max-w-3xl text-xl font-bold leading-8">{page.decision}</p><div className="mt-7 text-sm text-zinc-300">{page.confidence}: <strong>{page.confidenceValue}</strong></div></section><div className="mt-12 grid gap-4 md:grid-cols-2">{sections.map((section, index) => <section key={section} className="rounded-3xl border border-zinc-200 bg-white p-6"><div className="text-xs font-bold uppercase tracking-[0.22em] text-zinc-500">{String(index + 1).padStart(2, "0")}</div><h2 className="mt-3 text-2xl font-black text-zinc-950">{section}</h2></section>)}</div></article></main></ShadowScoreLayout>;
}
