import type { Locale } from "@/lib/i18n";

const he: Record<string, string> = {
  "Decision intelligence": "מודיעין לקבלת החלטות",
  "Good morning": "בוקר טוב",
  Today: "היום",
  "investigations are ready for a final decision.":
    "חקירות מוכנות להחלטה סופית.",
  "monitoring alerts require immediate review.":
    "התראות ניטור דורשות בדיקה מיידית.",
  "Portfolio risk increased by": "סיכון התיק עלה ב־",
  "Estimated review time": "זמן בדיקה משוער",
  minutes: "דקות",
  "Recommended first action": "פעולה ראשונה מומלצת",
  "Review INV-1042 before processing additional payments.":
    "בדקו את INV-1042 לפני עיבוד תשלומים נוספים.",
  "Start investigation": "התחלת חקירה",
  "Executive overview": "סקירה ניהולית",
  "Active investigations": "חקירות פעילות",
  "assigned to you": "מוקצות לך",
  "Open alerts": "התראות פתוחות",
  "require review now": "דורשות בדיקה כעת",
  "High-risk cases": "מקרים בסיכון גבוה",
  "ready for decision": "מוכנים להחלטה",
  "Entities monitored": "ישויות במעקב",
  "changed today": "השתנו היום",
  "Reports awaiting review": "דוחות ממתינים לבדיקה",
  "Oldest: 4 hours": "הוותיק ביותר: 4 שעות",
  "Average confidence": "רמת ביטחון ממוצעת",
  "Across active cases": "בכל המקרים הפעילים",
  "New evidence, 24h": "ראיות חדשות, 24 שעות",
  "Added to 12 investigations": "נוספו ל־12 חקירות",
  "Priority work": "עבודה בעדיפות",
  "Analyst queue": "תור האנליסט",
  "Show queue": "הצגת התור",
  "Preview empty state": "הצגת מצב ריק",
  "Search investigations": "חיפוש חקירות",
  "Search name or ID": "חיפוש שם או מזהה",
  "Filter by risk": "סינון לפי סיכון",
  "Sort queue": "מיון התור",
  "All risk": "כל רמות הסיכון",
  "Sort: priority": "מיון: עדיפות",
  "Sort: latest update": "מיון: עדכון אחרון",
  "Sort: confidence": "מיון: רמת ביטחון",
  Investigation: "חקירה",
  Risk: "סיכון",
  Confidence: "רמת ביטחון",
  Status: "סטטוס",
  Owner: "אחראי",
  Evidence: "ראיות",
  "Next action": "הפעולה הבאה",
  "No investigations match this view": "אין חקירות התואמות לתצוגה זו",
  "Change a filter or search term to return to active work.":
    "שנו סינון או מונח חיפוש כדי לחזור לעבודה הפעילה.",
  "Clear filters": "ניקוי מסננים",
  "Intelligence feed": "עדכונים מודיעיניים",
  "Recent activity": "פעילות אחרונה",
  "Risk overview": "סקירת סיכון",
  "Decision context": "הקשר להחלטה",
  "Risk distribution": "התפלגות סיכון",
  "high or critical": "גבוהים או קריטיים",
  "In review": "בבדיקה",
  Monitoring: "ניטור",
  "Risk trend, 7 days": "מגמת סיכון, 7 ימים",
  "Monitoring alerts": "התראות ניטור",
  "Changes requiring attention": "שינויים הדורשים תשומת לב",
  "Open monitoring": "פתיחת ניטור",
  "Business impact": "השפעה עסקית",
  "Immediate review recommended.": "מומלצת בדיקה מיידית.",
  "No immediate action recommended.": "לא מומלצת פעולה מיידית.",
  Acknowledged: "אושר",
  Acknowledge: "אישור",
  "Saved views": "תצוגות שמורות",
  "Return to work": "חזרה לעבודה",
  "Recent investigations": "חקירות אחרונות",
  "Evidence at a glance": "סקירת ראיות",
  "View all": "הצגת הכול",
  "Open case": "פתיחת התיק",
  Reason: "סיבה",
  "Linked payment account": "חשבון תשלום מקושר",
  "Marketplace abuse": "שימוש לרעה בזירת מסחר",
  "Identity conflict": "סתירה בזהות",
  "Confidence reflects evidence quality, provider agreement and source reliability.":
    "רמת הביטחון משקפת את איכות הראיות, הסכמה בין ספקים ואמינות המקורות.",
  Critical: "קריטי",
  High: "גבוה",
  Medium: "בינוני",
  Low: "נמוך",
  "Ready for decision": "מוכן להחלטה",
  "Collecting evidence": "איסוף ראיות",
  items: "פריטים",
  You: "אתה",
  "minutes ago": "דקות",
  "hr ago": "שעות",
  Yesterday: "אתמול",
};

export function dashboardText(locale: Locale, value: string) {
  return locale === "he" ? he[value] || value : value;
}

export function dashboardGreeting(locale: Locale, name: string) {
  return `${dashboardText(locale, "Good morning")}, ${name}.`;
}
