import type { Metadata } from "next";
import { createDemoTrustEngine, DEMO_TRUST_ENTITY_ID, TRUST_DIMENSIONS } from "@/lib/trustIntelligence";
import styles from "./trust-intelligence.module.css";
export const metadata:Metadata={title:"Trust Intelligence | ShadowScore",description:"Review evidence-backed trust scores, changes, alerts, and recommendations."};
const labels:Record<string,string>={identity:"Identity",operational:"Operational",financial:"Financial",compliance:"Compliance",marketplace:"Marketplace",cyber:"Cyber",reputation:"Reputation",relationships:"Relationships",evidenceQuality:"Evidence quality"};
export default function TrustIntelligencePage(){const engine=createDemoTrustEngine(),snapshot=engine.current(DEMO_TRUST_ENTITY_ID)!,history=engine.history(DEMO_TRUST_ENTITY_ID).slice(-6),alerts=engine.activeAlerts(DEMO_TRUST_ENTITY_ID);const positives=TRUST_DIMENSIONS.flatMap(key=>snapshot.scores[key].positiveEvidence.map(driver=>({...driver,dimension:key}))).sort((a,b)=>b.contribution-a.contribution).slice(0,4),negatives=TRUST_DIMENSIONS.flatMap(key=>snapshot.scores[key].negativeEvidence.map(driver=>({...driver,dimension:key}))).sort((a,b)=>a.contribution-b.contribution).slice(0,4),missing=TRUST_DIMENSIONS.flatMap(key=>snapshot.scores[key].missingEvidence.map(factor=>({dimension:key,factor}))).slice(0,7);return <main className={styles.shell}>
  <header className={styles.header}><div><p className={styles.eyebrow}>TRUST INTELLIGENCE / POLICY 1.0</p><h1>Atlas Commerce Ltd.</h1><p>Evidence-backed trust assessment for the resolved organization.</p></div><div className={styles.status}><span/>Assessment current</div></header>
  <section className={styles.hero}>
    <article className={styles.overall}><div className={styles.ring} style={{"--score":snapshot.overall} as React.CSSProperties}><div><strong>{snapshot.overall}</strong><span>Overall trust</span></div></div><div><p className={styles.eyebrow}>DECISION RECOMMENDATION</p><h2>{snapshot.recommendation}</h2><p>{Math.round(snapshot.confidence*100)}% confidence across {snapshot.inputSignalIds.length} active evidence signals.</p><small>{snapshot.policyVersion} · {snapshot.computationVersion}</small></div></article>
    <article className={styles.trend}><div className={styles.title}><div><span>TRUST TIMELINE</span><h2>Score history</h2></div><b>{history.at(-1)!.delta>=0?"+":""}{history.at(-1)!.delta} latest</b></div><div className={styles.chart}>{history.map((item,index)=><div className={styles.point} key={item.snapshotId}><span>{item.overall}</span><i style={{height:`${item.overall}%`}}/><small>{new Date(item.computedAt).toLocaleDateString("en-US",{month:"short",day:"numeric"})}</small>{index<history.length-1&&<em/>}</div>)}</div><p>{snapshot.changeReason}. Historical results remain linked to their policy and evidence inputs.</p></article>
  </section>
  <section className={styles.scores} aria-label="Category trust scores">{TRUST_DIMENSIONS.map(key=><article key={key}><div><span>{labels[key]}</span><b>{Math.round(snapshot.scores[key].confidence*100)}% confidence</b></div><strong>{snapshot.scores[key].score}</strong><div className={styles.bar}><i style={{width:`${snapshot.scores[key].score}%`}}/></div><p>{snapshot.scores[key].why}</p></article>)}</section>
  <section className={styles.details}>
    <article><div className={styles.title}><div><span>KEY DRIVERS</span><h2>Positive signals</h2></div><b>{positives.length}</b></div><ul>{positives.map(item=><li key={item.signalId}><i className={styles.good}>+</i><div><strong>{item.description}</strong><small>{labels[item.dimension]} · +{item.contribution} points · {Math.round(item.freshness*100)}% fresh</small></div></li>)}</ul></article>
    <article><div className={styles.title}><div><span>RISK DRIVERS</span><h2>Negative signals</h2></div><b>{negatives.length}</b></div><ul>{negatives.map(item=><li key={item.signalId}><i className={styles.bad}>−</i><div><strong>{item.description}</strong><small>{labels[item.dimension]} · {item.contribution} points · {item.evidenceReferences[0]}</small></div></li>)}</ul></article>
    <article><div className={styles.title}><div><span>COVERAGE GAPS</span><h2>Missing evidence</h2></div><b>{missing.length}</b></div><ul>{missing.map(item=><li key={`${item.dimension}-${item.factor}`}><i className={styles.neutral}>?</i><div><strong>{item.factor.replaceAll("_"," ")}</strong><small>{labels[item.dimension]} evidence is not available.</small></div></li>)}</ul></article>
  </section>
  <section className={styles.alerts}><div className={styles.title}><div><span>ACTIVE ALERTS</span><h2>Events requiring attention</h2></div><b>{alerts.length}</b></div>{alerts.length?alerts.map(alert=><article key={alert.alertId}><span>{alert.severity}</span><div><strong>{alert.type.replace(/([A-Z])/g," $1").trim()}</strong><p>{alert.explanation}</p></div><time>{alert.createdAt.slice(0,10)}</time></article>):<p className={styles.empty}>No active trust alerts.</p>}</section>
</main>}
