import type { ProviderEvidence, ProviderFinding, ProviderResult } from "../providers/types";
import type { EvidenceCategory, EvidenceStatus, ProviderFindingLike } from "./types";

const NEGATIVE_TERMS = ["confirmed", "verified", "known", "malicious", "phishing", "fraud", "enforcement", "counterfeit", "blocked", "suspended"];
const MISSING_TERMS = ["missing", "not include", "incomplete", "not observed"];

export function categoryToStatus(category: EvidenceCategory): EvidenceStatus { return category === "Verified" ? "observed" : category === "Missing" ? "missing" : category === "Negative" ? "negative" : category === "Unavailable" ? "unavailable" : category === "Not Applicable" ? "not_applicable" : "not_checked"; }
export function classifyProviderEvidence(evidence: ProviderEvidence): EvidenceCategory { const text = `${evidence.id} ${evidence.label} ${evidence.value || ""}`.toLowerCase(); if (evidence.type === "placeholder") return "Not Checked"; if (!evidence.value || evidence.value.toLowerCase() === "unavailable") return "Unavailable"; if (MISSING_TERMS.some((term) => text.includes(term))) return "Missing"; return "Verified"; }
export function classifyProviderFinding(finding: ProviderFindingLike): EvidenceCategory { const text = `${finding.id} ${finding.title} ${finding.description}`.toLowerCase(); if ((finding.severity === "critical" || finding.severity === "high") && NEGATIVE_TERMS.some((term) => text.includes(term))) return "Negative"; if (MISSING_TERMS.some((term) => text.includes(term))) return "Missing"; return "Verified"; }
export function classifyProviderResult(result: ProviderResult): EvidenceCategory { if (result.status === "failed") return "Unavailable"; if (result.status === "skipped") return "Unavailable"; if (result.metadata.integrationStatus === "not_connected" || result.metadata.lookupPerformed === false) return "Unavailable"; return "Verified"; }
export function confidenceFor(category: EvidenceCategory, result?: ProviderResult, severity?: ProviderFinding["severity"]) { const weight = typeof result?.metadata.providerConfidenceWeight === "number" ? Math.max(0, Math.min(1, result.metadata.providerConfidenceWeight)) : 1; const base = category === "Negative" ? (severity === "critical" ? 95 : severity === "high" ? 90 : 75) : category === "Verified" ? (result?.status === "completed" ? 85 : 65) : 100; return Math.round(base * weight); }
