import type { ProviderCategory } from "../providers/types";
import type { EvidenceItem, EvidenceSummary } from "./types";
const CATEGORIES = ["Verified", "Missing", "Negative", "Unavailable", "Not Checked", "Not Applicable"] as const;
export function summarizeEvidence(items: EvidenceItem[], providerCategories: Record<string, ProviderCategory | "unknown"> = {}): EvidenceSummary {
  const byCategory = (category: EvidenceItem["category"]) => items.filter((item) => item.category === category);
  const counts = Object.fromEntries(CATEGORIES.map((category) => [category, byCategory(category).length])) as EvidenceSummary["counts"];
  const providers = Array.from(new Set(items.map((item) => item.provider)));
  return { verifiedEvidence: byCategory("Verified"), missingVerification: byCategory("Missing"), negativeFindings: byCategory("Negative"), unavailableProviders: byCategory("Unavailable"), notYetChecked: byCategory("Not Checked"), counts, examples: { evidenceItems: items.slice(0, 3), summary: { counts } }, providerMapping: providers.map((provider) => ({ provider, category: providerCategories[provider] || "unknown", producedEvidence: items.filter((item) => item.provider === provider).length, statuses: Array.from(new Set(items.filter((item) => item.provider === provider).map((item) => item.status))) })), decisionMapping: [{ evidenceCategory: "Verified", decisionUse: "Increases verification coverage and confidence only." }, { evidenceCategory: "Missing", decisionUse: "Routes to review when coverage is insufficient; never counts as negative evidence." }, { evidenceCategory: "Negative", decisionUse: "Can block/pass fail only when explicit verified negative evidence exists." }, { evidenceCategory: "Unavailable", decisionUse: "Explains provider outage or failed retrieval; never treated as failed verification." }, { evidenceCategory: "Not Checked", decisionUse: "Explains planned or placeholder checks that were not run; never inferred as unknown risk." }, { evidenceCategory: "Not Applicable", decisionUse: "Hidden from primary decision previews and has no effect on decisions." }], architecture: ["Providers return raw ProviderResult objects.", "Evidence Builder normalizes provider output into canonical Evidence Items.", "Decision Engine consumes Evidence Items instead of raw provider output.", "Report Pipeline stores and displays Evidence Summary instead of raw evidence interpretations."], knownGaps: ["Placeholder providers still represent future integrations as Not Checked evidence.", "Legacy risk text analysis remains available for narrative context but canonical decision mapping is evidence-item driven.", "Provider-specific ownership validation will improve as production data sources replace placeholders."] };
}
