-- Platform Core Phase 2, Wave 4. Append-only knowledge ledgers and disposable projections.
create table public.resolution_policies(policy_id uuid primary key default gen_random_uuid(),policy_key text not null,version text not null,supported_taxonomy_keys text[] not null default '{*}',supported_subject_types text[] not null default '{*}',priority integer not null default 0,deterministic_rules jsonb not null default '{}',confidence_rules jsonb not null default '{}',conflict_behavior text not null check(conflict_behavior in('dispute','unresolved')),supersession_behavior text not null default 'append' check(supersession_behavior='append'),enabled boolean not null default true,created_at timestamptz not null default now(),unique(policy_key,version));
create table public.identity_candidates(candidate_id text primary key,workspace_id uuid not null references public.organizations(id) on delete restrict,left_subject_id uuid not null references public.subjects(subject_id) on delete restrict,right_subject_id uuid not null references public.subjects(subject_id) on delete restrict,candidate_type text not null check(candidate_type in('possible_match','probable_match','exact_match','possible_relationship','possible_split','conflict')),policy_key text not null,policy_version text not null,confidence numeric not null check(confidence between 0 and 1),status text not null check(status in('open','accepted','rejected','superseded','expired')),explanation text not null,created_at timestamptz not null default now(),resolved_at timestamptz,resolution text,check(left_subject_id<>right_subject_id),unique(workspace_id,left_subject_id,right_subject_id,policy_key,policy_version));
create table public.resolved_facts(fact_id text primary key,workspace_id uuid not null references public.organizations(id) on delete restrict,subject_id uuid not null references public.subjects(subject_id) on delete restrict,taxonomy_key text not null,canonical_value jsonb not null,canonical_value_hash text not null,confidence numeric not null check(confidence between 0 and 1),resolution_status text not null check(resolution_status in('current','disputed','superseded','unresolved','rejected')),policy_key text not null,policy_version text not null,valid_from timestamptz not null,valid_to timestamptz,created_at timestamptz not null default now(),superseded_by_fact_id text references public.resolved_facts(fact_id) on delete restrict,unique(workspace_id,subject_id,taxonomy_key,canonical_value_hash,policy_key,policy_version));
create table public.knowledge_conflicts(conflict_id text primary key,workspace_id uuid not null references public.organizations(id) on delete restrict,subject_id uuid not null references public.subjects(subject_id) on delete restrict,taxonomy_key text not null,severity numeric not null check(severity between 0 and 1),status text not null check(status in('open','resolved','superseded','accepted_variance')),policy_key text not null,policy_version text not null,explanation text not null,created_at timestamptz not null default now());
create table public.relationships(relationship_id text primary key,workspace_id uuid not null references public.organizations(id) on delete restrict,source_subject_id uuid not null references public.subjects(subject_id) on delete restrict,target_subject_id uuid references public.subjects(subject_id) on delete restrict,target_reference jsonb,relationship_type text not null,direction text not null check(direction in('directed','bidirectional')),confidence numeric not null check(confidence between 0 and 1),policy_key text not null,policy_version text not null,valid_from timestamptz not null,valid_to timestamptz,status text not null check(status in('current','disputed','superseded','rejected','unresolved')),created_at timestamptz not null default now(),superseded_by_relationship_id text references public.relationships(relationship_id) on delete restrict,check((target_subject_id is null)<>(target_reference is null)),unique(workspace_id,source_subject_id,target_subject_id,relationship_type,policy_key,policy_version));
create table public.fact_assertions(fact_id text not null references public.resolved_facts(fact_id) on delete restrict,assertion_id uuid not null references public.evidence_assertions(assertion_id) on delete restrict,contribution_type text not null check(contribution_type in('supports','contradicts','supersedes','contextualizes')),contribution_weight numeric not null check(contribution_weight between 0 and 1),created_at timestamptz not null default now(),primary key(fact_id,assertion_id,contribution_type));
create table public.relationship_assertions(relationship_id text not null references public.relationships(relationship_id) on delete restrict,assertion_id uuid not null references public.evidence_assertions(assertion_id) on delete restrict,contribution_type text not null check(contribution_type in('supports','contradicts','supersedes','contextualizes')),contribution_weight numeric not null check(contribution_weight between 0 and 1),created_at timestamptz not null default now(),primary key(relationship_id,assertion_id,contribution_type));
create table public.identity_candidate_assertions(candidate_id text not null references public.identity_candidates(candidate_id) on delete restrict,assertion_id uuid not null references public.evidence_assertions(assertion_id) on delete restrict,contribution_type text not null check(contribution_type in('supports','contradicts')),created_at timestamptz not null default now(),primary key(candidate_id,assertion_id));
create table public.conflict_assertions(conflict_id text not null references public.knowledge_conflicts(conflict_id) on delete restrict,assertion_id uuid not null references public.evidence_assertions(assertion_id) on delete restrict,created_at timestamptz not null default now(),primary key(conflict_id,assertion_id));
create table public.knowledge_projection(subject_id uuid primary key references public.subjects(subject_id) on delete cascade,workspace_id uuid not null references public.organizations(id) on delete cascade,payload jsonb not null,projected_at timestamptz not null default now());
create table public.knowledge_graph_nodes(node_id text primary key,workspace_id uuid not null references public.organizations(id) on delete cascade,subject_id uuid references public.subjects(subject_id) on delete cascade,node_type text not null,payload jsonb not null,projected_at timestamptz not null default now());
create table public.knowledge_graph_edges(edge_id text primary key,workspace_id uuid not null references public.organizations(id) on delete cascade,relationship_id text not null references public.relationships(relationship_id) on delete cascade,source_node_id text not null references public.knowledge_graph_nodes(node_id) on delete cascade,target_node_id text not null references public.knowledge_graph_nodes(node_id) on delete cascade,relationship_type text not null,confidence numeric not null,provenance_summary jsonb not null,projected_at timestamptz not null default now());
create table public.knowledge_resolution_runs(run_id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.organizations(id) on delete restrict,subject_id uuid references public.subjects(subject_id) on delete restrict,taxonomy_key text,scope text not null check(scope in('full','subject','taxonomy')),policy_versions text[] not null,status text not null check(status in('running','completed','failed')),created_at timestamptz not null default now(),completed_at timestamptz);
create table public.knowledge_events(event_id text primary key,workspace_id uuid not null references public.organizations(id) on delete restrict,event_type text not null,aggregate_id text not null,payload jsonb not null,occurred_at timestamptz not null,published_at timestamptz);
create index resolved_facts_current_idx on public.resolved_facts(workspace_id,subject_id,taxonomy_key,resolution_status); create index relationships_current_idx on public.relationships(workspace_id,source_subject_id,relationship_type,status); create index conflicts_active_idx on public.knowledge_conflicts(workspace_id,subject_id,status); create index candidates_subject_idx on public.identity_candidates(workspace_id,left_subject_id,right_subject_id,status);
create or replace function public.reject_knowledge_ledger_mutation() returns trigger language plpgsql as $$ begin raise exception 'knowledge history is append-only'; end $$;
do $$ declare t text; begin foreach t in array array['identity_candidates','resolved_facts','knowledge_conflicts','relationships','fact_assertions','relationship_assertions','identity_candidate_assertions','conflict_assertions','knowledge_resolution_runs','knowledge_events'] loop execute format('create trigger %I_append_only before update or delete on public.%I for each row execute function public.reject_knowledge_ledger_mutation()',t,t); end loop; end $$;
do $$ declare t text; begin foreach t in array array['resolution_policies','identity_candidates','resolved_facts','knowledge_conflicts','relationships','fact_assertions','relationship_assertions','identity_candidate_assertions','conflict_assertions','knowledge_projection','knowledge_graph_nodes','knowledge_graph_edges','knowledge_resolution_runs','knowledge_events'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
-- Ledger writes have no authenticated policy. Resolution workers use the service role.
create policy resolution_policy_read on public.resolution_policies for select to authenticated using(enabled);
do $$ declare t text; begin foreach t in array array['identity_candidates','resolved_facts','knowledge_conflicts','relationships','knowledge_projection','knowledge_graph_nodes','knowledge_graph_edges','knowledge_resolution_runs','knowledge_events'] loop execute format('create policy %I_workspace_read on public.%I for select to authenticated using(workspace_id in(select organization_id from public.organization_memberships where user_id=auth.uid() and status=''active''))',t,t); end loop; end $$;
create policy fact_assertions_read on public.fact_assertions for select to authenticated using(exists(select 1 from public.resolved_facts f where f.fact_id=fact_id and f.workspace_id in(select organization_id from public.organization_memberships where user_id=auth.uid() and status='active')));
create policy relationship_assertions_read on public.relationship_assertions for select to authenticated using(exists(select 1 from public.relationships r where r.relationship_id=relationship_id and r.workspace_id in(select organization_id from public.organization_memberships where user_id=auth.uid() and status='active')));
