-- Platform Core Phase 1. Durable subjects, investigations, evidence, usage, and audit history.
create table public.subjects (
  subject_id uuid primary key default gen_random_uuid(), subject_type text not null check(subject_type in ('domain','website','business','marketplace_account','email','phone','person','payment_account','social_account','wallet','ip_address','unknown')),
  canonical_name text not null, display_name text not null, status text not null default 'active' check(status in ('active','merged','archived')), workspace_id uuid references public.organizations(id) on delete cascade,
  visibility text not null default 'private' check(visibility in ('private','public')), merged_into_subject_id uuid references public.subjects(subject_id) on delete restrict, metadata jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  check((visibility='private' and workspace_id is not null) or visibility='public'), check((status='merged')=(merged_into_subject_id is not null))
);
create table public.subject_identifiers (
  identifier_id uuid primary key default gen_random_uuid(), subject_id uuid not null references public.subjects(subject_id) on delete cascade, identifier_type text not null, normalized_value text not null, display_value text not null, source text not null,
  verification_status text not null default 'unverified' check(verification_status in ('unverified','verified','disputed')), first_seen_at timestamptz not null default now(), last_seen_at timestamptz not null default now(), metadata jsonb not null default '{}'
);
-- Strong web identifiers are unique inside a tenant. Weak identifiers intentionally have no resolution constraint.
create unique index subject_strong_identifier_tenant_uidx on public.subject_identifiers ((coalesce((metadata->>'workspace_id')::uuid,'00000000-0000-0000-0000-000000000000'::uuid)),identifier_type,normalized_value) where identifier_type in ('domain','normalized_url');
create index subject_identifiers_subject_idx on public.subject_identifiers(subject_id);

create table public.investigation_jobs (
 investigation_job_id uuid primary key default gen_random_uuid(), subject_id uuid not null references public.subjects(subject_id), workspace_id uuid references public.organizations(id) on delete cascade, requested_by_user_id uuid references auth.users(id) on delete set null, investigation_type text not null,
 status text not null default 'queued' check(status in ('queued','running','waiting_retry','completed','failed','cancelled')), priority smallint not null default 100, attempt_count integer not null default 0, max_attempts integer not null default 3 check(max_attempts between 1 and 10), idempotency_key text not null, current_stage text,
 created_at timestamptz not null default now(), queued_at timestamptz not null default now(), started_at timestamptz, completed_at timestamptz, failed_at timestamptz, next_retry_at timestamptz, lease_owner text, lease_expires_at timestamptz, sanitized_failure_code text, sanitized_failure_message text, metadata jsonb not null default '{}', updated_at timestamptz not null default now(), unique(workspace_id,idempotency_key)
);
create index investigation_claim_idx on public.investigation_jobs(priority,queued_at) where status in ('queued','waiting_retry');
create table public.investigation_stages (
 stage_id uuid primary key default gen_random_uuid(), investigation_job_id uuid not null references public.investigation_jobs(investigation_job_id) on delete cascade, stage_name text not null, status text not null default 'pending' check(status in ('pending','running','completed','failed','skipped','waiting_retry')), attempt_count integer not null default 0,
 started_at timestamptz, completed_at timestamptz, next_retry_at timestamptz, failure_code text, sanitized_failure_message text, input_reference text, output_reference text, metadata jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(investigation_job_id,stage_name)
);

create table public.evidence_observations (
 observation_id uuid primary key default gen_random_uuid(), subject_id uuid not null references public.subjects(subject_id), investigation_job_id uuid not null references public.investigation_jobs(investigation_job_id), provider text not null, evidence_type text not null, normalized_key text not null, normalized_value text, structured_value jsonb, confidence numeric check(confidence between 0 and 1),
 observed_at timestamptz not null, valid_from timestamptz not null, expires_at timestamptz, freshness_status text not null check(freshness_status in ('fresh','stale','expired','unknown')), source_reference text, raw_payload_reference text, provider_version text, collector_version text not null, policy_version text not null, created_at timestamptz not null default now(), metadata jsonb not null default '{}', unique(investigation_job_id,provider,normalized_key,observed_at)
);
create index evidence_subject_timeline_idx on public.evidence_observations(subject_id,observed_at desc);
create table public.provider_result_cache (
 cache_id uuid primary key default gen_random_uuid(), workspace_id uuid references public.organizations(id) on delete cascade, visibility text not null check(visibility in ('workspace','public')), cache_key text not null, provider text not null, collector_version text not null, normalized_target text not null, request_type text not null, parameters_hash text not null, result_reference text not null,
 created_at timestamptz not null default now(), expires_at timestamptz not null, status text not null check(status in ('completed','failed')), cost_metadata jsonb not null default '{}', provider_response_identifier text, safe_failure_code text, safe_failure_message text, unique(cache_key), check((visibility='workspace' and workspace_id is not null) or visibility='public')
);
create table public.provider_usage_events (
 usage_event_id uuid primary key default gen_random_uuid(), investigation_job_id uuid not null references public.investigation_jobs(investigation_job_id), stage_id uuid references public.investigation_stages(stage_id), subject_id uuid not null references public.subjects(subject_id), workspace_id uuid references public.organizations(id), provider text not null, operation text not null,
 request_started_at timestamptz not null, request_completed_at timestamptz, outcome text not null check(outcome in ('completed','failed','cancelled')), cache_hit boolean not null default false, external_request_id text, quantity numeric, unit text, estimated_cost_usd numeric, actual_cost_usd numeric, currency text not null default 'USD' check(currency='USD'), retry_number integer not null default 0, sanitized_error_code text, metadata jsonb not null default '{}', created_at timestamptz not null default now()
);
create index provider_usage_job_idx on public.provider_usage_events(investigation_job_id,provider);
create table public.platform_audit_events (
 audit_event_id uuid primary key default gen_random_uuid(), workspace_id uuid references public.organizations(id), actor_type text not null check(actor_type in ('user','worker','system')), actor_id text, event_type text not null, subject_id uuid references public.subjects(subject_id), investigation_job_id uuid references public.investigation_jobs(investigation_job_id), resource_type text, resource_id text, occurred_at timestamptz not null default now(), correlation_id text, previous_state jsonb, new_state jsonb, sanitized_metadata jsonb not null default '{}'
);
create index platform_audit_workspace_timeline_idx on public.platform_audit_events(workspace_id,occurred_at desc);

alter table public.reports add column if not exists subject_id uuid references public.subjects(subject_id) on delete set null;
alter table public.website_intelligence_scans add column if not exists subject_id uuid references public.subjects(subject_id) on delete set null;
alter table public.website_intelligence_scans add column if not exists investigation_job_id uuid references public.investigation_jobs(investigation_job_id) on delete set null;
create index website_scans_subject_idx on public.website_intelligence_scans(subject_id,scanned_at desc);

create or replace function public.normalize_platform_domain(value text) returns text language plpgsql immutable as $$
declare v text:=lower(trim(value)); begin v:=regexp_replace(v,'^[a-z][a-z0-9+.-]*://',''); v:=split_part(v,'/',1); v:=regexp_replace(v,':(80|443)$',''); v:=regexp_replace(v,'\.$',''); if v='' or position('.' in v)=0 then raise exception 'invalid domain' using errcode='22023'; end if; return v; end $$;

create or replace function public.enqueue_website_investigation(p_target text,p_idempotency_key text) returns table(investigation_job_id uuid,subject_id uuid,workspace_id uuid,requested_by_user_id uuid,investigation_type text,status text,priority smallint,attempt_count integer,max_attempts integer,idempotency_key text,current_stage text,created_at timestamptz,queued_at timestamptz,started_at timestamptz,completed_at timestamptz,failed_at timestamptz,next_retry_at timestamptz,lease_owner text,lease_expires_at timestamptz,sanitized_failure_code text,sanitized_failure_message text,metadata jsonb,created boolean) language plpgsql security invoker as $$
declare v_workspace uuid;v_subject uuid;v_job uuid;v_domain text:=public.normalize_platform_domain(p_target);v_created boolean:=false;
begin select organization_id into v_workspace from public.organization_memberships where user_id=auth.uid() and status='active' order by updated_at desc limit 1; if v_workspace is null then raise exception 'active membership required' using errcode='42501'; end if;
 select si.subject_id into v_subject from public.subject_identifiers si join public.subjects s using(subject_id) where s.workspace_id=v_workspace and si.identifier_type='domain' and si.normalized_value=v_domain limit 1;
 if v_subject is null then insert into public.subjects(subject_type,canonical_name,display_name,workspace_id) values('domain',v_domain,p_target,v_workspace) returning subjects.subject_id into v_subject; insert into public.subject_identifiers(subject_id,identifier_type,normalized_value,display_value,source,metadata) values(v_subject,'domain',v_domain,p_target,'investigation_request',jsonb_build_object('workspace_id',v_workspace)); insert into public.platform_audit_events(workspace_id,actor_type,actor_id,event_type,subject_id) values(v_workspace,'user',auth.uid()::text,'subject.created',v_subject); end if;
 select j.investigation_job_id into v_job from public.investigation_jobs j where j.workspace_id=v_workspace and j.idempotency_key=p_idempotency_key;
 if v_job is null then insert into public.investigation_jobs(subject_id,workspace_id,requested_by_user_id,investigation_type,idempotency_key,current_stage) values(v_subject,v_workspace,auth.uid(),'website_intelligence',p_idempotency_key,'subject_resolution') returning investigation_jobs.investigation_job_id into v_job; v_created:=true;
 insert into public.investigation_stages(investigation_job_id,stage_name,status,attempt_count,started_at,completed_at) select v_job,name,case when name='subject_resolution' then 'completed' else 'pending' end,case when name='subject_resolution' then 1 else 0 end,case when name='subject_resolution' then now() end,case when name='subject_resolution' then now() end from unnest(array['subject_resolution','provider_planning','evidence_collection','normalization','decision','report_generation','history_persistence','alert_generation','watchlist_update']) name;
 insert into public.platform_audit_events(workspace_id,actor_type,actor_id,event_type,subject_id,investigation_job_id,correlation_id) values(v_workspace,'user',auth.uid()::text,'investigation.created',v_subject,v_job,p_idempotency_key); end if;
 return query select j.investigation_job_id,j.subject_id,j.workspace_id,j.requested_by_user_id,j.investigation_type,j.status,j.priority,j.attempt_count,j.max_attempts,j.idempotency_key,j.current_stage,j.created_at,j.queued_at,j.started_at,j.completed_at,j.failed_at,j.next_retry_at,j.lease_owner,j.lease_expires_at,j.sanitized_failure_code,j.sanitized_failure_message,j.metadata,v_created from public.investigation_jobs j where j.investigation_job_id=v_job; end $$;

create or replace function public.claim_investigation_job(p_worker_id text,p_lease_seconds integer default 300) returns setof public.investigation_jobs language plpgsql security definer set search_path=public as $$ declare v_id uuid; begin select investigation_job_id into v_id from public.investigation_jobs where (status='queued' or (status='waiting_retry' and next_retry_at<=now()) or (status='running' and lease_expires_at<now())) and attempt_count<max_attempts order by priority,queued_at for update skip locked limit 1; if v_id is null then return; end if; update public.investigation_jobs set status='running',attempt_count=attempt_count+1,started_at=coalesce(started_at,now()),lease_owner=p_worker_id,lease_expires_at=now()+make_interval(secs=>p_lease_seconds),updated_at=now() where investigation_job_id=v_id; insert into public.platform_audit_events(workspace_id,actor_type,actor_id,event_type,subject_id,investigation_job_id) select workspace_id,'worker',p_worker_id,'worker.job_claimed',subject_id,investigation_job_id from public.investigation_jobs where investigation_job_id=v_id; return query select * from public.investigation_jobs where investigation_job_id=v_id; end $$;
revoke all on function public.claim_investigation_job(text,integer) from public,anon,authenticated;
create or replace function public.fail_or_retry_investigation_job(p_job_id uuid,p_worker_id text,p_failure_code text,p_failure_message text) returns void language plpgsql security definer set search_path=public as $$
declare v_attempt integer;v_max integer; begin select attempt_count,max_attempts into v_attempt,v_max from public.investigation_jobs where investigation_job_id=p_job_id and lease_owner=p_worker_id for update; if not found then return; end if;
 if v_attempt>=v_max then update public.investigation_jobs set status='failed',failed_at=now(),sanitized_failure_code=p_failure_code,sanitized_failure_message=left(p_failure_message,500),lease_owner=null,lease_expires_at=null,updated_at=now() where investigation_job_id=p_job_id;
 else update public.investigation_jobs set status='waiting_retry',next_retry_at=now()+make_interval(secs=>least(3600,30*power(2,greatest(0,v_attempt-1)))::integer),sanitized_failure_code=p_failure_code,sanitized_failure_message=left(p_failure_message,500),lease_owner=null,lease_expires_at=null,updated_at=now() where investigation_job_id=p_job_id; end if;
 insert into public.platform_audit_events(workspace_id,actor_type,actor_id,event_type,subject_id,investigation_job_id,sanitized_metadata) select workspace_id,'worker',p_worker_id,case when v_attempt>=v_max then 'investigation.failed' else 'investigation.retry_scheduled' end,subject_id,investigation_job_id,jsonb_build_object('failure_code',p_failure_code) from public.investigation_jobs where investigation_job_id=p_job_id; end $$;
revoke all on function public.fail_or_retry_investigation_job(uuid,text,text,text) from public,anon,authenticated;

alter table public.subjects enable row level security; alter table public.subject_identifiers enable row level security; alter table public.investigation_jobs enable row level security; alter table public.investigation_stages enable row level security; alter table public.evidence_observations enable row level security; alter table public.provider_result_cache enable row level security; alter table public.provider_usage_events enable row level security; alter table public.platform_audit_events enable row level security;
create policy subject_member_read on public.subjects for select to authenticated using(workspace_id in(select organization_id from public.organization_memberships where user_id=auth.uid() and status='active') or visibility='public');
create policy identifier_member_read on public.subject_identifiers for select to authenticated using(exists(select 1 from public.subjects s where s.subject_id=subject_identifiers.subject_id and (s.visibility='public' or s.workspace_id in(select organization_id from public.organization_memberships where user_id=auth.uid() and status='active'))));
create policy job_member_read on public.investigation_jobs for select to authenticated using(workspace_id in(select organization_id from public.organization_memberships where user_id=auth.uid() and status='active'));
create policy stage_member_read on public.investigation_stages for select to authenticated using(exists(select 1 from public.investigation_jobs j where j.investigation_job_id=investigation_stages.investigation_job_id and j.workspace_id in(select organization_id from public.organization_memberships where user_id=auth.uid() and status='active')));
create policy evidence_member_read on public.evidence_observations for select to authenticated using(exists(select 1 from public.investigation_jobs j where j.investigation_job_id=evidence_observations.investigation_job_id and j.workspace_id in(select organization_id from public.organization_memberships where user_id=auth.uid() and status='active')));
create policy usage_member_read on public.provider_usage_events for select to authenticated using(workspace_id in(select organization_id from public.organization_memberships where user_id=auth.uid() and status='active'));
create policy audit_member_read on public.platform_audit_events for select to authenticated using(workspace_id in(select organization_id from public.organization_memberships where user_id=auth.uid() and status='active'));
-- No authenticated update or delete policies exist for observations, usage, or audit events. Workers write with the service role.

-- Safe non-destructive backfill. It links domain history per workspace without merging private tenants.
insert into public.subjects(subject_type,canonical_name,display_name,workspace_id,metadata)
select 'domain',public.normalize_platform_domain(s.target),s.target,m.organization_id,jsonb_build_object('backfilled',true) from public.website_intelligence_scans s join lateral(select organization_id from public.organization_memberships where user_id=s.user_id and status='active' order by updated_at desc limit 1)m on true where not exists(select 1 from public.subjects x where x.workspace_id=m.organization_id and x.canonical_name=public.normalize_platform_domain(s.target));
insert into public.subject_identifiers(subject_id,identifier_type,normalized_value,display_value,source,metadata)
select s.subject_id,'domain',s.canonical_name,s.display_name,'historical_backfill',jsonb_build_object('workspace_id',s.workspace_id) from public.subjects s where s.metadata->>'backfilled'='true' on conflict do nothing;
alter table public.website_intelligence_scans disable trigger website_intelligence_scans_no_update;
update public.website_intelligence_scans scan set subject_id=s.subject_id from public.organization_memberships m,public.subjects s where scan.subject_id is null and m.user_id=scan.user_id and m.status='active' and s.workspace_id=m.organization_id and s.canonical_name=public.normalize_platform_domain(scan.target);
alter table public.website_intelligence_scans enable trigger website_intelligence_scans_no_update;
