-- Canonical Decision schema. Existing case, evidence, and finding tables are referenced only.
create table public.decisions (
 id uuid primary key default gen_random_uuid(), public_id text not null unique default encode(gen_random_bytes(12),'hex'),
 case_id uuid not null references public.cases(id) on delete cascade, organization_id uuid not null references public.organizations(id) on delete cascade,
 outcome text not null check(outcome in('pass','proceed_with_verification','review','fail','no_decision')),
 rationale text not null check(char_length(rationale) between 10 and 10000), risk_level text not null check(risk_level in('low','medium','high','critical')),
 confidence text not null check(confidence in('low','medium','high')), recommended_actions text[] not null default '{}', conditions text[] not null default '{}',
 version integer not null default 1 check(version>0), is_current boolean not null default true,
 created_by uuid not null references public.profiles(id), updated_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index decisions_one_current_per_case on public.decisions(case_id) where is_current;
create table public.decision_findings(decision_id uuid not null references public.decisions(id) on delete restrict,finding_id uuid not null references public.findings(id) on delete restrict,primary key(decision_id,finding_id));
create table public.decision_versions(id uuid primary key default gen_random_uuid(),decision_id uuid not null references public.decisions(id) on delete restrict,organization_id uuid not null references public.organizations(id),version integer not null,snapshot jsonb not null,recorded_at timestamptz not null default now(),unique(decision_id,version));
alter table public.decisions enable row level security;alter table public.decision_findings enable row level security;alter table public.decision_versions enable row level security;
create policy "Members read decisions" on public.decisions for select using(exists(select 1 from public.organization_memberships m where m.organization_id=decisions.organization_id and m.user_id=auth.uid() and m.status='active'));
create policy "Members read decision findings" on public.decision_findings for select using(exists(select 1 from public.decisions d join public.organization_memberships m on m.organization_id=d.organization_id where d.id=decision_findings.decision_id and m.user_id=auth.uid() and m.status='active'));
create policy "Members read decision versions" on public.decision_versions for select using(exists(select 1 from public.organization_memberships m where m.organization_id=decision_versions.organization_id and m.user_id=auth.uid() and m.status='active'));
create or replace function public.reject_immutable_decision_version() returns trigger language plpgsql as $$begin raise exception 'decision_versions_are_immutable';end$$;
create trigger decision_versions_immutable before update or delete on public.decision_versions for each row execute function public.reject_immutable_decision_version();
create or replace function public.decision_context(p_case_public_id text,p_finding_public_ids text[],p_outcome text) returns public.cases language plpgsql security definer set search_path=public,auth as $$declare c public.cases;n integer;begin select cases.* into c from public.cases join public.organization_memberships m on m.organization_id=cases.organization_id where cases.public_id=p_case_public_id and m.user_id=auth.uid() and m.status='active' and m.role in('owner','manager','analyst');if c.id is null then raise exception 'case_not_found';end if;if p_outcome<>'no_decision' and coalesce(array_length(p_finding_public_ids,1),0)=0 then raise exception 'finding_required';end if;select count(*) into n from public.findings where case_id=c.id and organization_id=c.organization_id and public_id=any(coalesce(p_finding_public_ids,'{}'));if n<>coalesce(array_length(p_finding_public_ids,1),0) then raise exception 'finding_not_found';end if;return c;end$$;
create or replace function public.create_decision(p_case_public_id text,p_outcome text,p_rationale text,p_risk_level text,p_confidence text,p_recommended_actions text[],p_conditions text[],p_finding_public_ids text[]) returns setof public.decisions language plpgsql security definer set search_path=public,auth as $$declare c public.cases;d public.decisions;begin c:=public.decision_context(p_case_public_id,p_finding_public_ids,p_outcome);if exists(select 1 from public.decisions where case_id=c.id and is_current)then raise exception 'current_decision_exists';end if;insert into public.decisions(case_id,organization_id,outcome,rationale,risk_level,confidence,recommended_actions,conditions,created_by,updated_by)values(c.id,c.organization_id,p_outcome,p_rationale,p_risk_level,p_confidence,p_recommended_actions,p_conditions,auth.uid(),auth.uid())returning * into d;insert into public.decision_findings select d.id,id from public.findings where case_id=c.id and public_id=any(coalesce(p_finding_public_ids,'{}'));insert into public.timeline_events(case_id,organization_id,event_type,actor_type,actor_id,payload,reference_ids)values(c.id,c.organization_id,'decision.created','user',auth.uid(),jsonb_build_object('title','Decision created','detail',p_outcome),array[d.id]);return next d;end$$;
create or replace function public.update_decision(p_case_public_id text,p_expected_version integer,p_outcome text,p_rationale text,p_risk_level text,p_confidence text,p_recommended_actions text[],p_conditions text[],p_finding_public_ids text[]) returns setof public.decisions language plpgsql security definer set search_path=public,auth as $$declare c public.cases;d public.decisions;old public.decisions;begin c:=public.decision_context(p_case_public_id,p_finding_public_ids,p_outcome);select * into old from public.decisions where case_id=c.id and is_current;insert into public.decision_versions(decision_id,organization_id,version,snapshot)select old.id,old.organization_id,old.version,to_jsonb(old) where old.version=p_expected_version on conflict do nothing;update public.decisions set outcome=p_outcome,rationale=p_rationale,risk_level=p_risk_level,confidence=p_confidence,recommended_actions=p_recommended_actions,conditions=p_conditions,version=version+1,updated_by=auth.uid(),updated_at=now()where id=old.id and version=p_expected_version returning * into d;if d.id is null then return;end if;delete from public.decision_findings where decision_id=d.id;insert into public.decision_findings select d.id,id from public.findings where case_id=c.id and public_id=any(coalesce(p_finding_public_ids,'{}'));insert into public.timeline_events(case_id,organization_id,event_type,actor_type,actor_id,payload,reference_ids)values(c.id,c.organization_id,'decision.updated','user',auth.uid(),jsonb_build_object('title','Decision updated','detail',p_outcome),array[d.id]);if old.outcome<>p_outcome then insert into public.timeline_events(case_id,organization_id,event_type,actor_type,actor_id,payload,reference_ids)values(c.id,c.organization_id,'decision.outcome_changed','user',auth.uid(),jsonb_build_object('title','Decision outcome changed','from',old.outcome,'to',p_outcome),array[d.id]);end if;return next d;end$$;
