import type { Metadata } from "next";
import { runtime, scheduler } from "@/lib/continuousResolution/demo";
import styles from "./runtime.module.css";

export const metadata:Metadata={title:"Entity Runtime | ShadowScore",description:"Monitor incremental entity resolution, event processing, workers, and identity projections."};
const format=(value:number,digits=0)=>value.toFixed(digits);

export default function EntityRuntimePage(){const metrics=runtime.metrics(scheduler.backlog,scheduler.activeWorkers),events=runtime.eventPage(null,8).data.toReversed(),jobs=scheduler.snapshot(),health=runtime.indexHealth();const cards=[
  ["Resolver Queue",String(metrics.queueBacklog),"jobs waiting"],["Events/sec",format(metrics.eventsPerSecond,1),"current sample"],["Average latency",`${format(metrics.averageLatencyMs,1)} ms`,"incremental updates"],["Confidence Drift",`${metrics.confidenceDrift>=0?"+":""}${format(metrics.confidenceDrift*100,1)}%`,"threshold changes"],["Background Workers",String(metrics.activeWorkers),"active now"],["Projection Cache",String(metrics.projectionCacheSize),"materialized entities"],["Candidate Index",String(metrics.indexedValues),"normalized values"],["Queue Backlog",String(metrics.queueBacklog),"retryable jobs"],["Merge Rate",`${format(metrics.mergeRate*100,1)}%`,"of runtime events"],["Split Rate",`${format(metrics.splitRate*100,1)}%`,"of runtime events"],
];return <main className={styles.shell}><header><div><p>ENTITY INTELLIGENCE / WAVE 5.1</p><h1>Continuous resolution runtime</h1><span>Track incremental resolution, event delivery, workers, and projection health.</span></div><b><i/>Runtime healthy</b></header><section className={styles.cards}>{cards.map(([label,value,note])=><article key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</section><div className={styles.grid}><section className={styles.panel}><div className={styles.title}><div><span>IMMUTABLE EVENT BUS</span><h2>Recent events</h2></div><b>Schema v1</b></div><div className={styles.events}>{events.map(event=><article key={event.eventId}><i className={styles[event.type]}/><div><strong>{event.type}</strong><span>{event.entityId??"Workspace event"}</span></div><time>{event.occurredAt.slice(11,19)}</time><code>#{event.sequence}</code></article>)}</div></section><section className={styles.panel}><div className={styles.title}><div><span>BACKGROUND PROCESSING</span><h2>Resolver queue</h2></div><b>{jobs.length} job</b></div>{jobs.map(job=><article className={styles.job} key={job.jobId}><div><strong>{job.reason.replaceAll("_"," ")}</strong><span>{job.entityId}</span></div><em>{job.status}</em><small>{job.attempts}/{job.maxAttempts} attempts</small></article>)}<div className={styles.worker}><i/><div><strong>Worker pool ready</strong><span>Jobs use idempotency keys and bounded retries.</span></div></div></section><section className={`${styles.panel} ${styles.wide}`}><div className={styles.title}><div><span>CANDIDATE GENERATION</span><h2>Identity index health</h2></div><b>{metrics.indexedValues} values</b></div><div className={styles.indexes}>{health.map(item=><article key={item.attribute}><div><span>{item.attribute.replaceAll("_"," ")}</span><strong>{item.values}</strong></div><progress max={Math.max(...health.map(row=>row.values),1)} value={item.values}/></article>)}</div></section></div></main>}
